import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const BC_SCOPE="https://api.businesscentral.dynamics.com/user_impersonation offline_access openid profile";
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}})}
function b64url(s:string){return s.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(s.length/4)*4,'=')}
function jwtClaims(token:string):Record<string,unknown>{try{return JSON.parse(atob(b64url(token.split('.')[1])))}catch{return {}}}
async function sha256(v:unknown){const bytes=new TextEncoder().encode(JSON.stringify(v));const hash=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,'0')).join('')}
async function bcGet(accessToken:string,url:string){const r=await fetch(url,{headers:{Authorization:`Bearer ${accessToken}`,Accept:'application/json'}});if(!r.ok){const t=await r.text().catch(()=>"");throw new Error(`Business Central ${r.status}: ${t.slice(0,500)}`)}return r.json()}
async function bcList(accessToken:string,url:string,maxPages=100){const out:any[]=[];let next:string|null=url;let pages=0;while(next&&pages<maxPages){const j=await bcGet(accessToken,next);out.push(...(Array.isArray(j?.value)?j.value:[]));next=j?.['@odata.nextLink']??null;pages++}return out}
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'POST required'},405);
 const url=Deno.env.get('SUPABASE_URL')!;const anon=Deno.env.get('SUPABASE_ANON_KEY')!;const service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const auth=req.headers.get('Authorization')??'';
 const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});const admin=createClient(url,service);const {data:{user}}=await userClient.auth.getUser();if(!user)return json({error:'unauthorized'},401);
 let body:any;try{body=await req.json()}catch{return json({error:'invalid_json'},400)}const connectionId=String(body.connection_id??'');const action=String(body.action??'sync');if(!connectionId)return json({error:'connection_id_required'},400);
 const {data:conn}=await admin.from('platform_connector_connections').select('id,organization_id,connector_id,variant_id,status,auth_status,credential_ref,settings,auth_metadata,sync_cursor').eq('id',connectionId).maybeSingle();if(!conn)return json({error:'connection_not_found'},404);
 const {data:membership}=await admin.from('organization_members').select('role,status').eq('organization_id',conn.organization_id).eq('user_id',user.id).eq('status','active').maybeSingle();if(!membership)return json({error:'organization_access_denied'},403);if(!['owner','admin','super_admin'].includes(String(membership.role??'')))return json({error:'admin_required'},403);
 const {data:connector}=await admin.from('platform_connectors').select('key').eq('id',conn.connector_id).single();const {data:variant}=await admin.from('platform_connector_variants').select('key').eq('id',conn.variant_id).single();if(connector?.key!=='microsoft_dynamics_365'||variant?.key!=='business_central')return json({error:'not_business_central_connection'},400);if(!conn.credential_ref)return json({error:'microsoft_authorization_required'},409);
 const {data:secret}=await admin.rpc('platform_get_connector_secret',{p_id:conn.credential_ref});if(!secret)return json({error:'credential_unavailable'},500);let token:any;try{token=JSON.parse(secret)}catch{return json({error:'invalid_credential_payload'},500)}try{token=await ensureToken(admin,conn.credential_ref,token)}catch(e){return json({error:'token_refresh_failed',detail:String(e)},401)}
 const tc=jwtClaims(token.access_token??'');const tenant=String(conn.auth_metadata?.tenant_id??tc.tid??'');if(!tenant)return json({error:'tenant_id_unavailable'},409);const environment=String(body.environment??conn.settings?.environment??'Production');const base=`https://api.businesscentral.dynamics.com/v2.0/${encodeURIComponent(tenant)}/${encodeURIComponent(environment)}/api/v2.0`;
 let companies:any[];try{companies=await bcList(token.access_token,`${base}/companies?$select=id,name,displayName,systemVersion,lastModifiedDateTime`)}catch(e){return json({error:'business_central_access_failed',detail:String(e),consent_hint:'Reconnect Microsoft with Business Central API permission and confirm the user has Business Central access.'},403)}
 if(action==='discover')return json({ok:true,tenant_id:tenant,environment,companies:companies.map(c=>({id:c.id,name:c.name,display_name:c.displayName,last_modified:c.lastModifiedDateTime}))});
 let companyId=String(body.company_id??conn.settings?.company_id??'');if(!companyId&&companies.length===1)companyId=String(companies[0].id);if(!companyId)return json({error:'company_selection_required',environment,companies:companies.map(c=>({id:c.id,name:c.name,display_name:c.displayName}))},409);const company=companies.find(c=>String(c.id)===companyId);if(!company)return json({error:'company_not_found',company_id:companyId},404);
 const jobType=String(body.sync_type??'full');const {data:job,error:je}=await admin.from('platform_sync_jobs').insert({connection_id:connectionId,job_type:`business_central_${jobType}`,direction:'inbound',status:'running',requested_by:user.id,started_at:new Date().toISOString(),cursor:{environment,company_id:companyId}}).select('id').single();if(je)return json({error:'sync_job_create_failed',detail:je.message},500);
 const stats:any={processed:0,updated:0,duplicates:0,failed:0,by_type:{}};
 try{
  const since=body.since??conn.sync_cursor?.business_central?.last_success_at??null;
  const resources=[
   {external:'customer',path:'customers',filterable:true,name:(x:any)=>x.displayName||x.number||x.id,occurred:(x:any)=>x.lastModifiedDateTime},
   {external:'item',path:'items',filterable:true,name:(x:any)=>x.displayName||x.description||x.number||x.id,occurred:(x:any)=>x.lastModifiedDateTime},
   {external:'salespersonPurchaser',path:'salespeoplePurchasers',filterable:true,name:(x:any)=>x.displayName||x.code||x.id,occurred:(x:any)=>x.lastModifiedDateTime},
   {external:'location',path:'locations',filterable:false,name:(x:any)=>x.displayName||x.code||x.id,occurred:(_x:any)=>null},
   {external:'itemLedgerEntry',path:'itemLedgerEntries',filterable:true,name:(x:any)=>`${x.itemNumber||'Item'} ${x.documentNumber||x.entryNumber||x.id}`,occurred:(x:any)=>x.lastModifiedDateTime||x.postingDate},
   {external:'salesOrder',path:'salesOrders',expand:'salesOrderLines',filterable:true,name:(x:any)=>x.number||x.externalDocumentNumber||x.id,occurred:(x:any)=>x.lastModifiedDateTime||x.orderDate},
   {external:'salesInvoice',path:'salesInvoices',expand:'salesInvoiceLines',filterable:true,name:(x:any)=>x.number||x.externalDocumentNumber||x.id,occurred:(x:any)=>x.lastModifiedDateTime||x.postingDate||x.invoiceDate}
  ];
  for(const rsrc of resources){const filter=since&&rsrc.filterable?`&$filter=lastModifiedDateTime gt ${encodeURIComponent(new Date(since).toISOString())}`:'';const expand=rsrc.expand?`&$expand=${rsrc.expand}`:'';const endpoint=`${base}/companies(${companyId})/${rsrc.path}?$top=200${expand}${filter}`;let rows:any[]=[];try{rows=await bcList(token.access_token,endpoint)}catch(e){stats.failed++;stats.by_type[rsrc.external]={error:String(e),processed:0};continue}const ts:any={processed:0,updated:0,duplicates:0,failed:0};
   for(const row of rows){try{const externalId=String(row.id??row.entryNumber??row.number??row.code??'');if(!externalId)continue;const payload={...row,_iq:{source:'microsoft_dynamics_365',variant:'business_central',tenant_id:tenant,environment,company_id:companyId,company_name:company.displayName||company.name}};const hash=await sha256(payload);const {data:ing,error:ie}=await admin.rpc('platform_ingest_connector_record',{p_connection_id:connectionId,p_external_entity_type:rsrc.external,p_external_id:externalId,p_canonical_name:String(rsrc.name(row)??externalId),p_payload:payload,p_payload_hash:hash,p_occurred_at:validDate(rsrc.occurred(row)),p_actor_id:user.id});if(ie)throw ie;ts.processed++;stats.processed++;if(ing?.duplicate){ts.duplicates++;stats.duplicates++}else{ts.updated++;stats.updated++}}catch{ts.failed++;stats.failed++}}stats.by_type[rsrc.external]=ts;
  }
  const now=new Date().toISOString();await admin.from('platform_connector_connections').update({status:'active',auth_status:'valid',settings:{...(conn.settings??{}),environment,company_id:companyId,company_name:company.displayName||company.name},sync_cursor:{...(conn.sync_cursor??{}),business_central:{last_success_at:now,environment,company_id:companyId}},last_sync_at:now,last_success_at:now,last_error:null,updated_at:now}).eq('id',connectionId);
  let performanceBridge:any=null;try{const br=await fetch(`${url}/functions/v1/transaction-performance-bridge`,{method:'POST',headers:{Authorization:auth,apikey:anon,'Content-Type':'application/json'},body:JSON.stringify({connection_id:connectionId,since})});performanceBridge=await br.json().catch(()=>({ok:false,status:br.status}));if(!br.ok)performanceBridge={ok:false,status:br.status,...performanceBridge};}catch(e){performanceBridge={ok:false,error:String(e)}}
  const jobStats={...stats,performance_bridge:performanceBridge};await admin.from('platform_sync_jobs').update({status:stats.failed?'partial':'success',stats:jobStats,completed_at:now}).eq('id',job.id);return json({ok:true,job_id:job.id,tenant_id:tenant,environment,company:{id:companyId,name:company.displayName||company.name},stats:jobStats});
 }catch(e){const now=new Date().toISOString();await admin.from('platform_sync_jobs').update({status:'failed',error_details:{message:String(e)},stats,completed_at:now}).eq('id',job.id);await admin.from('platform_connector_connections').update({status:'error',last_sync_at:now,last_error:String(e),updated_at:now}).eq('id',connectionId);return json({error:'business_central_sync_failed',detail:String(e),job_id:job.id,stats},500)}
});
function validDate(v:any){if(!v)return new Date().toISOString();const d=new Date(v);return Number.isNaN(d.valueOf())?new Date().toISOString():d.toISOString()}
async function ensureToken(admin:any,credentialRef:string,token:any){const c=jwtClaims(token.access_token??'');const exp=Number(c.exp??0)*1000;if(token.access_token&&exp>Date.now()+120000)return token;if(!token.refresh_token)throw new Error('refresh_token_missing');const clientId=Deno.env.get('MICROSOFT_CLIENT_ID');const clientSecret=Deno.env.get('MICROSOFT_CLIENT_SECRET');if(!clientId||!clientSecret)throw new Error('microsoft_client_credentials_not_configured');const tenant=String(token.tenant_id??c.tid??'organizations');const form=new URLSearchParams({client_id:clientId,client_secret:clientSecret,grant_type:'refresh_token',refresh_token:token.refresh_token,scope:BC_SCOPE});const r=await fetch(`https://login.microsoftonline.com/${encodeURIComponent(tenant)}/oauth2/v2.0/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form});const j=await r.json();if(!r.ok)throw new Error(j.error_description||j.error||`refresh ${r.status}`);const next={...token,...j,refresh_token:j.refresh_token||token.refresh_token,tenant_id:tenant,refreshed_at:new Date().toISOString()};const {error}=await admin.rpc('platform_update_connector_secret',{p_id:credentialRef,p_secret:JSON.stringify(next)});if(error)throw error;return next}
