import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}})}
function norm(v:any){return String(v??'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function email(v:any){return String(v??'').trim().toLowerCase()}
function first(p:any,fields:string[]){for(const f of fields||[]){const parts=f.split('.');let v=p;for(const x of parts)v=v?.[x];if(v!==undefined&&v!==null&&String(v).trim()!=='')return v}return null}
function similarity(a:any,b:any){const x=norm(a),y=norm(b);if(!x||!y)return 0;if(x===y)return 1;const big=(s:string)=>{const z=` ${s} `;const out:string[]=[];for(let i=0;i<z.length-1;i++)out.push(z.slice(i,i+2));return out};const A=big(x),B=big(y);const used=new Set<number>();let hit=0;for(const g of A){const j=B.findIndex((h,k)=>h===g&&!used.has(k));if(j>=0){used.add(j);hit++}}return (2*hit)/(A.length+B.length)}

Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
 if(req.method!=='POST')return json({error:'POST required'},405);
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
 const auth=req.headers.get('Authorization')??'';const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});const admin=createClient(url,service);
 const {data:{user}}=await userClient.auth.getUser();if(!user)return json({error:'unauthorized'},401);
 let body:any;try{body=await req.json()}catch{return json({error:'invalid_json'},400)}
 const action=String(body.action??'status'),connectionId=String(body.connection_id??'');if(!connectionId)return json({error:'connection_id_required'},400);
 const {data:conn}=await admin.from('platform_connector_connections').select('id,organization_id,store_id,connector_id,variant_id,status,auth_status,settings,last_sync_at,last_success_at,last_error').eq('id',connectionId).maybeSingle();if(!conn)return json({error:'connection_not_found'},404);
 const {data:member}=await admin.from('organization_members').select('role,status').eq('organization_id',conn.organization_id).eq('user_id',user.id).eq('status','active').maybeSingle();if(!member)return json({error:'organization_access_denied'},403);if(!['owner','admin'].includes(String(member.role??'')))return json({error:'admin_required'},403);
 const {data:connector}=await admin.from('platform_connectors').select('key,name').eq('id',conn.connector_id).single();const {data:variant}=conn.variant_id?await admin.from('platform_connector_variants').select('key,name').eq('id',conn.variant_id).single():{data:null};
 let pq=admin.from('platform_connector_onboarding_profiles').select('*').eq('connector_id',conn.connector_id).eq('is_active',true);pq=conn.variant_id?pq.eq('variant_id',conn.variant_id):pq.is('variant_id',null);const {data:profile}=await pq.maybeSingle();if(!profile)return json({error:'onboarding_profile_not_configured',connector:connector?.key,variant:variant?.key??null},409);

 if(action==='auto_match')await buildQueue(admin,conn,profile,user.id);
 if(action==='resolve_employee'){
   const externalId=String(body.external_id??''),candidateId=String(body.user_id??'');if(!externalId||!candidateId)return json({error:'external_id_and_user_id_required'},400);
   const {data:q}=await admin.from('platform_connector_match_queue').select('*').eq('connection_id',connectionId).eq('external_entity_type','employee').eq('external_id',externalId).maybeSingle();if(!q)return json({error:'match_row_not_found'},404);
   const {data:om}=await admin.from('organization_members').select('user_id').eq('organization_id',conn.organization_id).eq('user_id',candidateId).eq('status','active').maybeSingle();if(!om)return json({error:'user_not_active_org_member'},400);
   const map={organization_id:conn.organization_id,store_id:body.store_id??conn.store_id??null,salesperson_user_id:candidateId,pos_employee_id:q.external_code||q.external_id,pos_system:profile.pos_system_key,display_name:q.external_name,is_active:true,created_by:user.id,updated_at:new Date().toISOString()};
   const {error:me}=await admin.from('iq_pos_employee_map').upsert(map,{onConflict:'organization_id,pos_system,pos_employee_id'});if(me)return json({error:'employee_map_failed',detail:me.message},500);
   await admin.from('platform_connector_match_queue').update({candidate_type:'user',candidate_id:candidateId,confidence:1,match_method:'manual',status:'confirmed',reviewed_by:user.id,reviewed_at:new Date().toISOString(),metadata:{...(q.metadata??{}),decision_locked:true},updated_at:new Date().toISOString()}).eq('id',q.id);
 }
 if(action==='resolve_location'){
   const externalId=String(body.external_id??'');if(!externalId)return json({error:'external_id_required'},400);
   const {data:q}=await admin.from('platform_connector_match_queue').select('*').eq('connection_id',connectionId).eq('external_entity_type','location').eq('external_id',externalId).maybeSingle();if(!q)return json({error:'match_row_not_found'},404);
   let locationId=body.location_id?String(body.location_id):'';
   if(!locationId&&body.create===true){const p=q.metadata?.payload??{};const address=String(first(p,profile.location_address_fields)||'')||null;const city=String(first(p,profile.location_city_fields)||'')||null;const {data:newLoc,error:le}=await admin.from('org_locations').insert({organization_id:conn.organization_id,location_type:'store',name:q.external_name||q.external_code||`${profile.source_label} Location`,code:q.external_code||null,address,city,province_state:p.state||p.province||p.provinceState||null,country:p.country||p.countryCode||'CA',metadata:{source:profile.pos_system_key,source_connection_id:connectionId,external_location_id:q.external_id}}).select('id').single();if(le)return json({error:'location_create_failed',detail:le.message},500);locationId=newLoc.id;}
   if(!locationId)return json({error:'location_id_or_create_required'},400);const {data:loc}=await admin.from('org_locations').select('id').eq('id',locationId).eq('organization_id',conn.organization_id).maybeSingle();if(!loc)return json({error:'location_not_in_org'},400);
   const {data:entityMap}=await admin.from('platform_connector_entity_map').select('id').eq('connection_id',connectionId).eq('external_entity_type',q.metadata?.source_entity_type||'location').eq('external_id',externalId).maybeSingle();const em={connection_id:connectionId,external_entity_type:q.metadata?.source_entity_type||'location',external_id:externalId,local_entity_type:'org_location',local_id:locationId,metadata:{confirmed_by:user.id,method:'manual_or_auto'},last_synced_at:new Date().toISOString()};if(entityMap?.id)await admin.from('platform_connector_entity_map').update(em).eq('id',entityMap.id);else await admin.from('platform_connector_entity_map').insert(em);
   await admin.from('platform_connector_match_queue').update({candidate_type:'location',candidate_id:locationId,confidence:1,match_method:'manual',status:'confirmed',reviewed_by:user.id,reviewed_at:new Date().toISOString(),metadata:{...(q.metadata??{}),decision_locked:true},updated_at:new Date().toISOString()}).eq('id',q.id);
   const {data:allLoc}=await admin.from('platform_connector_match_queue').select('candidate_id,status').eq('connection_id',connectionId).eq('external_entity_type','location');const confirmed=(allLoc??[]).filter((x:any)=>x.status==='confirmed'&&x.candidate_id);if(confirmed.length===1)await admin.from('platform_connector_connections').update({store_id:confirmed[0].candidate_id,updated_at:new Date().toISOString()}).eq('id',connectionId);
 }
 if(action==='reject'){const rowId=String(body.match_id??'');if(!rowId)return json({error:'match_id_required'},400);const {data:q}=await admin.from('platform_connector_match_queue').select('metadata').eq('id',rowId).eq('connection_id',connectionId).maybeSingle();await admin.from('platform_connector_match_queue').update({status:'rejected',reviewed_by:user.id,reviewed_at:new Date().toISOString(),metadata:{...(q?.metadata??{}),decision_locked:true},updated_at:new Date().toISOString()}).eq('id',rowId).eq('connection_id',connectionId);}
 if(action==='activate'){const {data:summary}=await admin.rpc('platform_connector_onboarding_summary',{p_connection_id:connectionId});if(!summary?.ready)return json({error:'onboarding_review_incomplete',summary},409);await admin.from('platform_connector_connections').update({status:'active',settings:{...(conn.settings??{}),onboarding_completed_at:new Date().toISOString(),onboarding_profile:profile.pos_system_key},updated_at:new Date().toISOString()}).eq('id',connectionId);}
 const {data:summary}=await admin.rpc('platform_connector_onboarding_summary',{p_connection_id:connectionId});const {data:queue}=await admin.from('platform_connector_match_queue').select('id,external_entity_type,external_id,external_code,external_name,external_email,candidate_type,candidate_id,confidence,match_method,status,metadata,reviewed_at').eq('connection_id',connectionId).order('external_entity_type').order('external_name');
 const {data:members}=await admin.from('organization_members').select('user_id,role,status').eq('organization_id',conn.organization_id).eq('status','active');const userIds=(members??[]).map((m:any)=>m.user_id);let profiles:any[]=[];if(userIds.length){const {data:p}=await admin.from('profiles').select('user_id,full_name,email').in('user_id',userIds);profiles=p??[];}const {data:locations}=await admin.from('org_locations').select('id,name,code,address,city,province_state,country,is_active').eq('organization_id',conn.organization_id).eq('is_active',true).order('name');
 return json({ok:true,connector:{key:connector?.key,name:connector?.name,variant_key:variant?.key??null,variant_name:variant?.name??null,source_label:profile.source_label,pos_system_key:profile.pos_system_key},connection:{id:conn.id,status:action==='activate'?'active':conn.status,auth_status:conn.auth_status,last_sync_at:conn.last_sync_at,last_success_at:conn.last_success_at,last_error:conn.last_error},summary,queue:queue??[],candidates:{users:profiles,locations:locations??[]}});
});

async function buildQueue(admin:any,conn:any,profile:any,userId:string){
 const sourceTypes=[...(profile.employee_entity_types||[]),...(profile.location_entity_types||[])];const {data:keyRows}=await admin.from('platform_connector_ingestion_keys').select('external_id,external_entity_type,intelligence_event_id').eq('connection_id',conn.id).in('external_entity_type',sourceTypes).not('intelligence_event_id','is',null);const keys=keyRows??[];
 const eventIds=keys.map((x:any)=>x.intelligence_event_id);const eventsById=new Map<string,any>();for(let i=0;i<eventIds.length;i+=150){const {data}=await admin.from('intelligence_events').select('id,payload').in('id',eventIds.slice(i,i+150));for(const e of data??[])eventsById.set(e.id,e.payload??{})}
 const {data:members}=await admin.from('organization_members').select('user_id').eq('organization_id',conn.organization_id).eq('status','active');const ids=(members??[]).map((x:any)=>x.user_id);let profiles:any[]=[];if(ids.length){const {data}=await admin.from('profiles').select('user_id,full_name,email').in('user_id',ids);profiles=data??[]}const {data:locations}=await admin.from('org_locations').select('id,name,code,address,city,province_state,country').eq('organization_id',conn.organization_id).eq('is_active',true);
 for(const k of keys){const p=eventsById.get(k.intelligence_event_id)??{};const isEmployee=(profile.employee_entity_types||[]).includes(k.external_entity_type);const normalizedType=isEmployee?'employee':'location';const externalId=String(first(p,['id','uuid','recordId'])??k.external_id);const {data:existingDecision}=await admin.from('platform_connector_match_queue').select('id,status,metadata').eq('connection_id',conn.id).eq('external_entity_type',normalizedType).eq('external_id',externalId).maybeSingle();if(existingDecision?.metadata?.decision_locked)continue;
  if(isEmployee){const code=String(first(p,profile.employee_code_fields)??k.external_id),name=String(first(p,profile.employee_name_fields)??code),em=email(first(p,profile.employee_email_fields));let best:any=null;const exactEmail=em?profiles.filter(x=>email(x.email)===em):[];if(exactEmail.length===1)best={id:exactEmail[0].user_id,confidence:1,method:'email_exact',status:'confirmed'};if(!best&&name){const exact=profiles.filter(x=>norm(x.full_name)===norm(name));if(exact.length===1)best={id:exact[0].user_id,confidence:.98,method:'name_exact',status:'confirmed'}}if(!best&&name){const ranked=profiles.map(x=>({id:x.user_id,s:similarity(name,x.full_name)})).sort((a,b)=>b.s-a.s);if(ranked[0]&&ranked[0].s>=.80)best={id:ranked[0].id,confidence:ranked[0].s,method:'name_similarity',status:ranked[0].s>=.93?'suggested':'needs_review'}}const row={connection_id:conn.id,organization_id:conn.organization_id,external_entity_type:'employee',external_id:externalId,external_code:code,external_name:name,external_email:em||null,candidate_type:best?'user':null,candidate_id:best?.id??null,confidence:best?.confidence??null,match_method:best?.method??null,status:best?.status??'unmatched',metadata:{payload:p,source_entity_type:k.external_entity_type,source_label:profile.source_label},updated_at:new Date().toISOString()};await admin.from('platform_connector_match_queue').upsert(row,{onConflict:'connection_id,external_entity_type,external_id'});if(best?.status==='confirmed')await admin.from('iq_pos_employee_map').upsert({organization_id:conn.organization_id,store_id:conn.store_id??null,salesperson_user_id:best.id,pos_employee_id:code,pos_system:profile.pos_system_key,display_name:name,is_active:true,created_by:userId,updated_at:new Date().toISOString()},{onConflict:'organization_id,pos_system,pos_employee_id'});
  } else {const code=String(first(p,profile.location_code_fields)??''),name=String(first(p,profile.location_name_fields)??code??externalId),city=String(first(p,profile.location_city_fields)??''),address=String(first(p,profile.location_address_fields)??'');let best:any=null;const exactCode=code?(locations??[]).filter((x:any)=>norm(x.code)===norm(code)):[];if(exactCode.length===1)best={id:exactCode[0].id,confidence:1,method:'code_exact',status:'confirmed'};if(!best&&name){const exact=(locations??[]).filter((x:any)=>norm(x.name)===norm(name)&&(!city||norm(x.city)===norm(city)));if(exact.length===1)best={id:exact[0].id,confidence:.98,method:'name_city_exact',status:'confirmed'}}if(!best&&name){const ranked=(locations??[]).map((x:any)=>({id:x.id,s:.65*similarity(name,x.name)+.20*(city?similarity(city,x.city):0)+.15*(address?similarity(address,x.address):0)})).sort((a:any,b:any)=>b.s-a.s);if(ranked[0]&&ranked[0].s>=.68)best={id:ranked[0].id,confidence:ranked[0].s,method:'location_similarity',status:ranked[0].s>=.92?'suggested':'needs_review'}}const row={connection_id:conn.id,organization_id:conn.organization_id,external_entity_type:'location',external_id:externalId,external_code:code||null,external_name:name||externalId,external_email:first(p,['email','emailAddress'])??null,candidate_type:best?'location':null,candidate_id:best?.id??null,confidence:best?.confidence??null,match_method:best?.method??null,status:best?.status??'unmatched',metadata:{payload:p,source_entity_type:k.external_entity_type,source_label:profile.source_label},updated_at:new Date().toISOString()};await admin.from('platform_connector_match_queue').upsert(row,{onConflict:'connection_id,external_entity_type,external_id'});if(best?.status==='confirmed'){const {data:existing}=await admin.from('platform_connector_entity_map').select('id').eq('connection_id',conn.id).eq('external_entity_type',k.external_entity_type).eq('external_id',externalId).maybeSingle();const em={connection_id:conn.id,external_entity_type:k.external_entity_type,external_id:externalId,local_entity_type:'org_location',local_id:best.id,metadata:{auto_matched:true,method:best.method},last_synced_at:new Date().toISOString()};if(existing?.id)await admin.from('platform_connector_entity_map').update(em).eq('id',existing.id);else await admin.from('platform_connector_entity_map').insert(em)}}
 }
}
