import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
async function sha256(input:string){const data=new TextEncoder().encode(input);const hash=await crypto.subtle.digest("SHA-256",data);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("")}
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors}); if(req.method!=="POST")return json({error:"POST required"},405);
 const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,auth=req.headers.get("Authorization")??"";
 const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}}),admin=createClient(url,service); const {data:{user}}=await userClient.auth.getUser(); if(!user)return json({error:"unauthorized"},401);
 let body:any;try{body=await req.json()}catch{return json({error:"invalid_json"},400)}
 const connectionId=String(body.connection_id??""),externalEntityType=String(body.external_entity_type??""),externalId=String(body.external_id??""); if(!connectionId||!externalEntityType||!externalId)return json({error:"connection_id, external_entity_type, external_id required"},400);
 const syncJobId=body.sync_job_id?String(body.sync_job_id):null;
 const {data:conn}=await admin.from("platform_connector_connections").select("id,organization_id,connector_id,variant_id,platform_connectors(key,name),platform_connector_variants(key,name)").eq("id",connectionId).maybeSingle(); if(!conn)return json({error:"connection_not_found"},404);
 const {data:membership}=await admin.from("organization_members").select("role,status").eq("organization_id",conn.organization_id).eq("user_id",user.id).eq("status","active").maybeSingle(); if(!membership)return json({error:"organization_access_denied"},403);
 const connectorKey=(conn as any).platform_connectors?.key??"connector",variantKey=(conn as any).platform_connector_variants?.key??null,sourceSystem=variantKey?`${connectorKey}:${variantKey}`:connectorKey;
 const normalized=body.payload&&typeof body.payload==="object"?body.payload:{};
 const validation=await admin.rpc("platform_validate_connector_record",{p_connector_key:connectorKey,p_external_entity_type:externalEntityType,p_payload:normalized});
 if(validation.error)return json({error:"validation_engine_failed",detail:validation.error.message},500);
 if(validation.data?.valid===false){
   const q=await admin.rpc("platform_enqueue_connector_quarantine",{p_connection_id:connectionId,p_sync_job_id:syncJobId,p_external_entity_type:externalEntityType,p_external_id:externalId,p_stage:"validation",p_error_code:"record_validation_failed",p_error_message:JSON.stringify(validation.data.problems??[]),p_payload:normalized,p_retryable:false});
   return json({error:"record_validation_failed",problems:validation.data.problems??[],quarantine_id:q.data??null},422);
 }
 let q=admin.from("platform_connector_canonical_rules").select("id,variant_id,canonical_entity_type,canonical_event_type,direction,mapping,priority").eq("connector_id",conn.connector_id).eq("external_entity_type",externalEntityType).eq("active",true); if(conn.variant_id)q=q.or(`variant_id.eq.${conn.variant_id},variant_id.is.null`);else q=q.is("variant_id",null);
 const {data:rules,error:rerr}=await q.order("priority",{ascending:true}).limit(10); if(rerr)return json({error:rerr.message},500); const rule=(rules??[]).sort((a:any,b:any)=>Number(a.variant_id===null)-Number(b.variant_id===null)||a.priority-b.priority)[0];
 if(!rule){const qr=await admin.rpc("platform_enqueue_connector_quarantine",{p_connection_id:connectionId,p_sync_job_id:syncJobId,p_external_entity_type:externalEntityType,p_external_id:externalId,p_stage:"mapping",p_error_code:"canonical_mapping_not_found",p_error_message:`No active canonical mapping for ${externalEntityType}`,p_payload:normalized,p_retryable:false});return json({error:"canonical_mapping_not_found",external_entity_type:externalEntityType,quarantine_id:qr.data??null},422)}
 const canonicalEntityType=String(body.canonical_entity_type??rule.canonical_entity_type??"other"),canonicalEventType=String(body.canonical_event_type??rule.canonical_event_type??`${canonicalEntityType}.updated`),canonicalName=String(body.canonical_name??normalized.canonical_name??normalized.name??normalized.displayName??normalized.number??externalId),occurredAt=String(body.occurred_at??new Date().toISOString()),payloadHash=await sha256(JSON.stringify(normalized));
 const {data:seen}=await admin.from("platform_connector_ingestion_keys").select("id,intelligence_entity_id,intelligence_event_id,payload_hash").eq("connection_id",connectionId).eq("external_entity_type",externalEntityType).eq("external_id",externalId).eq("canonical_event_type",canonicalEventType).eq("payload_hash",payloadHash).maybeSingle(); if(seen){await admin.from("platform_connector_ingestion_keys").update({last_seen_at:new Date().toISOString()}).eq("id",seen.id);return json({ok:true,deduped:true,intelligence_entity_id:seen.intelligence_entity_id,intelligence_event_id:seen.intelligence_event_id})}
 try{
   const sourceRecordId=`${externalEntityType}:${externalId}`; let {data:entity}=await admin.from("intelligence_entities").select("id").eq("organization_id",conn.organization_id).eq("source_system",sourceSystem).eq("source_record_id",sourceRecordId).maybeSingle();
   if(entity){const u=await admin.from("intelligence_entities").update({entity_type:canonicalEntityType,canonical_name:canonicalName,status:"active",metadata:{...normalized,connector_connection_id:connectionId,external_entity_type:externalEntityType,external_id:externalId},updated_by:user.id}).eq("id",entity.id);if(u.error)throw u.error}else{const ins=await admin.from("intelligence_entities").insert({organization_id:conn.organization_id,entity_type:canonicalEntityType,canonical_name:canonicalName,source_system:sourceSystem,source_record_id:sourceRecordId,status:"active",metadata:{...normalized,connector_connection_id:connectionId,external_entity_type:externalEntityType,external_id:externalId},created_by:user.id,updated_by:user.id}).select("id").single();if(ins.error)throw ins.error;entity=ins.data}
   const em=await admin.from("platform_connector_entity_map").upsert({connection_id:connectionId,external_entity_type:externalEntityType,external_id:externalId,local_entity_type:"intelligence_entity",local_id:entity.id,payload_hash:payloadHash,metadata:{canonical_entity_type:canonicalEntityType,canonical_event_type:canonicalEventType,source_system:sourceSystem},last_synced_at:new Date().toISOString()},{onConflict:"connection_id,external_entity_type,external_id"});if(em.error)throw em.error;
   const eventSourceRecordId=`${sourceRecordId}:${payloadHash.slice(0,16)}`;const ev=await admin.from("intelligence_events").insert({organization_id:conn.organization_id,entity_id:entity.id,event_type:canonicalEventType,source_system:sourceSystem,source_record_id:eventSourceRecordId,actor_id:user.id,payload:{...normalized,title:body.title??`${canonicalName} ${canonicalEventType}`,summary:body.summary??null,connector_connection_id:connectionId,external_entity_type:externalEntityType,external_id:externalId},occurred_at:occurredAt}).select("id").single();if(ev.error)throw ev.error;
   const ingest=await admin.from("platform_connector_ingestion_keys").insert({connection_id:connectionId,external_entity_type:externalEntityType,external_id:externalId,canonical_event_type:canonicalEventType,payload_hash:payloadHash,intelligence_entity_id:entity.id,intelligence_event_id:ev.data.id,metadata:{source_system:sourceSystem,canonical_entity_type:canonicalEntityType}}).select("id").single();if(ingest.error)throw ingest.error;
   const {data:openQs}=await admin.from("platform_connector_quarantine").select("id").eq("connection_id",connectionId).eq("external_entity_type",externalEntityType).eq("external_id",externalId).in("status",["quarantined","retrying"]);
   for(const oq of openQs??[])await admin.rpc("platform_mark_connector_retry_result",{p_quarantine_id:oq.id,p_success:true,p_error:null});
   return json({ok:true,deduped:false,canonical_entity_type:canonicalEntityType,canonical_event_type:canonicalEventType,intelligence_entity_id:entity.id,intelligence_event_id:ev.data.id,ingestion_id:ingest.data.id},201)
 }catch(e:any){
   const msg=String(e?.message??e);const retryable=/timeout|temporar|rate|429|5\d\d|connection|network|deadlock|lock timeout/i.test(msg);
   const qr=await admin.rpc("platform_enqueue_connector_quarantine",{p_connection_id:connectionId,p_sync_job_id:syncJobId,p_external_entity_type:externalEntityType,p_external_id:externalId,p_stage:"ingestion",p_error_code:retryable?"transient_ingestion_error":"ingestion_error",p_error_message:msg,p_payload:normalized,p_retryable:retryable});
   return json({error:"ingestion_failed",detail:msg,retryable,quarantine_id:qr.data??null},retryable?503:500)
 }
});
