import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}})}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,authHeader=req.headers.get('Authorization')??'';const userClient=createClient(url,anon,{global:{headers:{Authorization:authHeader}}}),admin=createClient(url,service);const {data:{user},error:userError}=await userClient.auth.getUser();if(userError||!user)return json({error:'unauthorized'},401);let body:Record<string,unknown>={};if(req.method==='POST'){try{body=await req.json()}catch{return json({error:'invalid_json'},400)}}const action=String(body.action??'catalog');
if(action==='catalog'){const {data:connectors,error}=await admin.from('platform_connectors').select('id,key,name,vendor_name,category,description,auth_type,status,supports_webhooks,supports_incremental_sync,partner_required,capabilities,documentation_url,metadata').order('name');if(error)return json({error:error.message},500);const {data:variants,error:vError}=await admin.from('platform_connector_variants').select('id,connector_id,key,name,description,api_family,auth_type,status,base_url_template,capabilities,metadata').order('name');if(vError)return json({error:vError.message},500);const {data:profiles}=await admin.from('platform_connector_onboarding_profiles').select('connector_id,variant_id,pos_system_key,source_label,is_active,metadata').eq('is_active',true);return json({connectors:(connectors??[]).map(c=>({...c,onboarding_supported:(profiles??[]).some(p=>p.connector_id===c.id&&p.variant_id===null),variants:(variants??[]).filter(v=>v.connector_id===c.id).map(v=>({...v,onboarding_supported:(profiles??[]).some(p=>p.connector_id===c.id&&p.variant_id===v.id)}))}))})}
const organizationId=String(body.organization_id??'');if(!organizationId)return json({error:'organization_id_required'},400);const {data:membership}=await admin.from('organization_members').select('role,status').eq('organization_id',organizationId).eq('user_id',user.id).eq('status','active').maybeSingle();if(!membership)return json({error:'organization_access_denied'},403);
if(action==='connections'){const {data,error}=await admin.from('platform_connector_connections').select('id,organization_id,store_id,connector_id,variant_id,external_account_id,display_name,status,auth_status,settings,sync_cursor,last_sync_at,last_success_at,last_error,created_at,updated_at').eq('organization_id',organizationId).order('created_at',{ascending:false});if(error)return json({error:error.message},500);return json({connections:data??[]})}
const isAdmin=['owner','admin','super_admin'].includes(String(membership.role??''));
if(action==='prepare_connection'){if(!isAdmin)return json({error:'admin_required'},403);const connectorKey=String(body.connector_key??''),variantKey=body.variant_key?String(body.variant_key):null;if(!connectorKey)return json({error:'connector_key_required'},400);const {data:connector}=await admin.from('platform_connectors').select('id,key,name,auth_type,status').eq('key',connectorKey).maybeSingle();if(!connector)return json({error:'connector_not_found'},404);let variant:Record<string,unknown>|null=null;if(variantKey){const {data}=await admin.from('platform_connector_variants').select('id,key,name,api_family,auth_type,status,base_url_template,capabilities,metadata').eq('connector_id',connector.id).eq('key',variantKey).maybeSingle();if(!data)return json({error:'connector_variant_not_found'},404);variant=data}const settings=body.settings&&typeof body.settings==='object'?body.settings:{};const {data:connection,error}=await admin.from('platform_connector_connections').insert({organization_id:organizationId,store_id:body.store_id||null,connector_id:connector.id,variant_id:variant?.id??null,display_name:String(body.display_name??variant?.name??connector.name),status:'pending',auth_status:'not_configured',settings,created_by:user.id}).select('id,organization_id,store_id,connector_id,variant_id,display_name,status,auth_status,settings,created_at').single();if(error)return json({error:error.message},500);let pq=admin.from('platform_connector_onboarding_profiles').select('id').eq('connector_id',connector.id).eq('is_active',true);pq=variant?.id?pq.eq('variant_id',variant.id):pq.is('variant_id',null);const {data:onboarding}=await pq.maybeSingle();return json({connection,connector,variant,onboarding_supported:!!onboarding,next_step:connector.auth_type==='oauth2'?'oauth_authorization':'credentials_configuration'},201)}
if(action==='queue_sync'){if(!isAdmin)return json({error:'admin_required'},403);const connectionId=String(body.connection_id??''),syncType=String(body.sync_type??'incremental'),direction=String(body.direction??'inbound');if(!connectionId)return json({error:'connection_id_required'},400);const {data:conn}=await admin.from('platform_connector_connections').select('id').eq('id',connectionId).eq('organization_id',organizationId).maybeSingle();if(!conn)return json({error:'connection_not_found'},404);const {data:job,error}=await admin.from('platform_sync_jobs').insert({connection_id:connectionId,job_type:syncType,direction,status:'queued',requested_by:user.id}).select('*').single();if(error)return json({error:error.message},500);return json({job},201)}return json({error:'unknown_action'},400)});
