BEGIN;
SET LOCAL statement_timeout='25s';
DO $$
DECLARE editor_actor uuid;editor_native uuid;reviewer_actor uuid;reviewer_native uuid;trade_actor uuid;trade_native uuid;
 org uuid;foreign_org uuid;vendor uuid;foreign_vendor uuid;link_id uuid;foreign_id uuid;upload_id uuid;upload_path text;result jsonb;draft_id uuid;
BEGIN
 SELECT im.source_user_id,im.target_user_id INTO editor_actor,editor_native FROM tj.source_user_identity_map im JOIN auth.users u ON u.id=im.target_user_id WHERE tj_private.microsoft_actor(u.id)=im.source_user_id AND u.email_confirmed_at IS NOT NULL LIMIT 1;
 SELECT im.source_user_id,im.target_user_id INTO reviewer_actor,reviewer_native FROM tj.source_user_identity_map im JOIN auth.users u ON u.id=im.target_user_id WHERE tj_private.microsoft_actor(u.id)=im.source_user_id AND u.email_confirmed_at IS NOT NULL AND im.source_user_id<>editor_actor LIMIT 1;
 SELECT im.source_user_id,im.target_user_id INTO trade_actor,trade_native FROM tj.source_user_identity_map im JOIN auth.users u ON u.id=im.target_user_id WHERE tj_private.microsoft_actor(u.id)=im.source_user_id AND u.email_confirmed_at IS NOT NULL AND im.source_user_id NOT IN(editor_actor,reviewer_actor) LIMIT 1;
 IF trade_native IS NULL THEN RAISE EXCEPTION 'missing confirmed mapped fixtures';END IF;
 UPDATE tj.product_iq_platform_roles SET status='revoked' WHERE user_id IN(editor_actor,reviewer_actor,trade_actor) AND organization_id IS NULL AND role IN('super_admin','product_iq_super_admin');
 INSERT INTO tj.organizations(name,slug) VALUES('Native asset rollback fixture','native-asset-rollback-'||gen_random_uuid()::text) RETURNING id INTO org;
 INSERT INTO tj.organizations(name,slug) VALUES('Foreign asset rollback fixture','native-asset-rollback-'||gen_random_uuid()::text) RETURNING id INTO foreign_org;
 INSERT INTO tj.organization_members(organization_id,user_id,role,status) VALUES(org,editor_actor,'member','active'),(org,reviewer_actor,'admin','active'),(org,trade_actor,'member','active'),(foreign_org,reviewer_actor,'admin','active');
 INSERT INTO tj.mfr_vendors(slug,name,status) VALUES('native-asset-rollback-'||gen_random_uuid()::text,'Native asset rollback brand','active') RETURNING id INTO vendor;
 INSERT INTO tj.mfr_vendors(slug,name,status) VALUES('native-asset-rollback-'||gen_random_uuid()::text,'Foreign asset rollback brand','active') RETURNING id INTO foreign_vendor;
 INSERT INTO tj.mfr_members(user_id,vendor_id,role,member_role,status,approved_by,approved_at,activated_at)
 VALUES(editor_actor,vendor,'asset_editor','editor','active',reviewer_actor,now(),now()),(reviewer_actor,vendor,'vendor_owner','owner','active',reviewer_actor,now(),now());
 INSERT INTO tj.mfr_user_roles(user_id,is_builder,is_designer,is_retailer) VALUES(trade_actor,true,false,false) ON CONFLICT(user_id) DO UPDATE SET is_builder=true,is_designer=false,is_retailer=false;
 PERFORM set_config('request.jwt.claim.sub',editor_native::text,true);
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','list','vendor_id',vendor,'organization_id',org));
 IF result->>'ok'<>'true' OR result->>'can_write'<>'true' OR result->>'can_review'<>'false' THEN RAISE EXCEPTION 'editor scope wrong: %',result;END IF;
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','create_link','vendor_id',vendor,'organization_id',org,'category','spec_sheet','title','Fixture spec','audiences',jsonb_build_array('builder'),'external_url','https://example.test/spec'));
 IF result->>'ok'<>'true' THEN RAISE EXCEPTION 'link create failed: %',result;END IF;link_id:=(result->>'asset_id')::uuid;
 IF NOT EXISTS(SELECT 1 FROM tj.mfr_assets WHERE id=link_id AND organization_id=org AND uploaded_by=editor_actor AND uploaded_native=editor_native AND NOT is_published AND upload_state='ready') THEN RAISE EXCEPTION 'source actor or draft contract wrong';END IF;
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','publish','asset_id',link_id));IF result->>'error'<>'forbidden' THEN RAISE EXCEPTION 'editor self-published';END IF;
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','list','vendor_id',vendor,'organization_id',foreign_org));IF result->>'error'<>'forbidden' THEN RAISE EXCEPTION 'foreign organization opened';END IF;
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','list','vendor_id',foreign_vendor,'organization_id',org));IF result->>'error'<>'organization_access_required' THEN RAISE EXCEPTION 'foreign vendor opened';END IF;
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','create_link','vendor_id',vendor,'organization_id',org,'category','spec_sheet','title','Invalid','audiences',jsonb_build_array('builder'),'external_url','javascript:alert(1)'));IF result->>'error'<>'invalid_request' THEN RAISE EXCEPTION 'unsafe URL accepted';END IF;
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','reserve_upload','vendor_id',vendor,'organization_id',org,'category','spec_sheet','title','File fixture','audiences',jsonb_build_array('builder'),'file_name','fixture.pdf','mime_type','application/pdf','file_size_bytes',12));
 IF result->>'ok'<>'true' THEN RAISE EXCEPTION 'upload reserve failed: %',result;END IF;upload_id:=(result->>'asset_id')::uuid;upload_path:=result->>'storage_path';
 IF upload_path NOT LIKE org::text||'/'||vendor::text||'/'||upload_id::text||'/%' OR NOT tj_private.mfr_asset_storage_upload(upload_path) OR tj_private.mfr_asset_storage_read(upload_path) THEN RAISE EXCEPTION 'upload path or pending state wrong';END IF;
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','finalize','asset_id',upload_id));IF result->>'error'<>'upload_incomplete' THEN RAISE EXCEPTION 'missing object finalized';END IF;
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','reserve_upload','vendor_id',vendor,'organization_id',org,'category','spec_sheet','title','Oversized','audiences',jsonb_build_array('builder'),'file_name','fixture.pdf','mime_type','application/pdf','file_size_bytes',20971521));IF result->>'error'<>'invalid_request' THEN RAISE EXCEPTION 'oversize accepted';END IF;
 INSERT INTO storage.objects(bucket_id,name,owner_id,metadata) VALUES('tj-mfr-assets',upload_path,editor_native::text,'{"size":12,"mimetype":"application/pdf"}');
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','finalize','asset_id',upload_id));IF result->>'ok'<>'true' OR NOT tj_private.mfr_asset_storage_read(upload_path) OR tj_private.mfr_asset_storage_upload(upload_path) THEN RAISE EXCEPTION 'finalization state wrong';END IF;
 PERFORM set_config('request.jwt.claim.sub',reviewer_native::text,true);
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','finalize','asset_id',upload_id));IF result->>'error'<>'forbidden' THEN RAISE EXCEPTION 'wrong native owner finalized';END IF;
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','publish','asset_id',link_id));IF result->>'ok'<>'true' THEN RAISE EXCEPTION 'review publish failed';END IF;
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','publish','asset_id',upload_id));IF result->>'ok'<>'true' THEN RAISE EXCEPTION 'file publish failed';END IF;
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','create_link','vendor_id',vendor,'organization_id',foreign_org,'category','spec_sheet','title','Foreign fixture','audiences',jsonb_build_array('builder'),'external_url','https://example.test/foreign'));foreign_id:=(result->>'asset_id')::uuid;
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','publish','asset_id',foreign_id));IF result->>'ok'<>'true' THEN RAISE EXCEPTION 'foreign fixture failed';END IF;
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','create_link','vendor_id',vendor,'organization_id',org,'category','spec_sheet','title','Unpublished fixture','audiences',jsonb_build_array('builder'),'external_url','https://example.test/draft'));draft_id:=(result->>'asset_id')::uuid;
 PERFORM set_config('request.jwt.claim.sub',trade_native::text,true);
 result:=public.tj_runtime_manufacturer_assets('{"action":"trade"}');IF result->>'ok'<>'true' OR result->>'audience'<>'builder' THEN RAISE EXCEPTION 'mapped trade role failed';END IF;
 IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(result->'assets') a WHERE a->>'id'=link_id::text) OR EXISTS(SELECT 1 FROM jsonb_array_elements(result->'assets') a WHERE a->>'id' IN(foreign_id::text,draft_id::text)) THEN RAISE EXCEPTION 'trade draft/foreign scope failed';END IF;
 IF NOT tj_private.mfr_asset_storage_read(upload_path) OR tj_private.mfr_asset_storage_upload(upload_path) THEN RAISE EXCEPTION 'trade storage scope failed';END IF;
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','archive','asset_id',link_id));IF result->>'error'<>'forbidden' THEN RAISE EXCEPTION 'trade archived asset';END IF;
 result:=public.tj_runtime_manufacturer_assets('{"action":"trade","audience":"designer"}');IF result->>'error'<>'trade_access_required' THEN RAISE EXCEPTION 'unapproved designer role accepted';END IF;
 PERFORM set_config('request.jwt.claim.sub',editor_native::text,true);
 UPDATE tj.mfr_members SET status='suspended' WHERE user_id=editor_actor AND vendor_id=vendor;
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','archive','asset_id',link_id));IF result->>'error'<>'forbidden' THEN RAISE EXCEPTION 'suspended vendor edited';END IF;
 UPDATE tj.mfr_members SET status='active' WHERE user_id=editor_actor AND vendor_id=vendor;
 UPDATE tj.organizations SET deleted_at=now() WHERE id=org;
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','archive','asset_id',link_id));IF result->>'error'<>'forbidden' THEN RAISE EXCEPTION 'deleted organization edited';END IF;
 UPDATE tj.organizations SET deleted_at=NULL WHERE id=org;
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','archive','asset_id',upload_id));IF result->>'ok'<>'true' OR tj_private.mfr_asset_storage_read(upload_path) THEN RAISE EXCEPTION 'archive did not close access';END IF;
 IF NOT EXISTS(SELECT 1 FROM storage.objects WHERE bucket_id='tj-mfr-assets' AND name=upload_path) OR NOT EXISTS(SELECT 1 FROM tj.mfr_assets WHERE id=upload_id AND archived_at IS NOT NULL AND NOT is_published) THEN RAISE EXCEPTION 'archive removed file or row';END IF;
 IF EXISTS(SELECT 1 FROM storage.buckets WHERE id='tj-mfr-assets' AND public) OR has_table_privilege('authenticated','tj.mfr_assets','INSERT') OR has_table_privilege('authenticated','tj.mfr_assets','UPDATE') OR has_table_privilege('authenticated','tj.mfr_assets','DELETE') OR has_function_privilege('anon','public.tj_runtime_manufacturer_assets(jsonb)','EXECUTE') THEN RAISE EXCEPTION 'private grants wrong';END IF;
 PERFORM set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
 result:=public.tj_runtime_manufacturer_assets('{"action":"trade"}');IF result->>'error'<>'identity_review_required' THEN RAISE EXCEPTION 'unmapped user allowed';END IF;
 PERFORM set_config('test.assets.org',org::text,true);PERFORM set_config('test.assets.vendor',vendor::text,true);PERFORM set_config('test.assets.reviewer_native',reviewer_native::text,true);PERFORM set_config('test.assets.upload_path',upload_path,true);PERFORM set_config('test.assets.editor_native',editor_native::text,true);PERFORM set_config('test.assets.native',trade_native::text,true);PERFORM set_config('test.assets.link',link_id::text,true);PERFORM set_config('test.assets.foreign',foreign_id::text,true);PERFORM set_config('test.assets.draft',draft_id::text,true);
END $$;
SET LOCAL ROLE authenticated;
DO $$DECLARE result jsonb;blocked boolean:=false;reserved_path text;reserved_id uuid;BEGIN
 PERFORM set_config('request.jwt.claim.sub',current_setting('test.assets.native'),true);
 IF EXISTS(SELECT 1 FROM storage.objects WHERE bucket_id='tj-mfr-assets' AND name=current_setting('test.assets.upload_path')) THEN RAISE EXCEPTION 'archived storage object visible';END IF;
 BEGIN
  INSERT INTO storage.objects(bucket_id,name,owner_id,metadata) VALUES('tj-mfr-assets','unreserved/'||gen_random_uuid()::text,auth.uid()::text,'{"size":12,"mimetype":"application/pdf"}');
 EXCEPTION WHEN insufficient_privilege THEN blocked:=true;END;
 IF NOT blocked THEN RAISE EXCEPTION 'unreserved upload allowed by real Storage RLS';END IF;
 PERFORM set_config('request.jwt.claim.sub',current_setting('test.assets.editor_native'),true);
 blocked:=false;
 BEGIN
  INSERT INTO storage.objects(bucket_id,name,owner_id,metadata) VALUES('tj-mfr-assets','unreserved/'||gen_random_uuid()::text,auth.uid()::text,'{"size":12,"mimetype":"application/pdf"}');
 EXCEPTION WHEN insufficient_privilege THEN blocked:=true;END;
 IF NOT blocked THEN RAISE EXCEPTION 'editor unreserved upload allowed';END IF;
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','reserve_upload','organization_id',current_setting('test.assets.org'),'vendor_id',current_setting('test.assets.vendor'),'category','spec_sheet','title','Authenticated Storage fixture','audiences',jsonb_build_array('builder'),'file_name','authenticated.pdf','mime_type','application/pdf','file_size_bytes',13));
 IF result->>'ok'<>'true' THEN RAISE EXCEPTION 'authenticated reservation failed: %',result;END IF;
 reserved_path:=result->>'storage_path';reserved_id:=(result->>'asset_id')::uuid;
 INSERT INTO storage.objects(bucket_id,name,owner_id,metadata) VALUES('tj-mfr-assets',reserved_path,auth.uid()::text,'{"size":13,"mimetype":"application/pdf"}');
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','finalize','asset_id',reserved_id));
 IF result->>'ok'<>'true' OR NOT EXISTS(SELECT 1 FROM storage.objects WHERE bucket_id='tj-mfr-assets' AND name=reserved_path) THEN RAISE EXCEPTION 'authorized Storage upload/read failed';END IF;
 PERFORM set_config('request.jwt.claim.sub',current_setting('test.assets.native'),true);
 IF EXISTS(SELECT 1 FROM storage.objects WHERE bucket_id='tj-mfr-assets' AND name=reserved_path) THEN RAISE EXCEPTION 'trade saw unpublished file';END IF;
 PERFORM set_config('request.jwt.claim.sub',current_setting('test.assets.reviewer_native'),true);
 result:=public.tj_runtime_manufacturer_assets(jsonb_build_object('action','publish','asset_id',reserved_id));IF result->>'ok'<>'true' THEN RAISE EXCEPTION 'authenticated publication failed';END IF;
 PERFORM set_config('request.jwt.claim.sub',current_setting('test.assets.native'),true);
 IF NOT EXISTS(SELECT 1 FROM storage.objects WHERE bucket_id='tj-mfr-assets' AND name=reserved_path) THEN RAISE EXCEPTION 'trade cannot read reviewed file';END IF;
 IF NOT EXISTS(SELECT 1 FROM tj.mfr_assets WHERE id=current_setting('test.assets.link')::uuid) OR EXISTS(SELECT 1 FROM tj.mfr_assets WHERE id IN(current_setting('test.assets.foreign')::uuid,current_setting('test.assets.draft')::uuid)) THEN RAISE EXCEPTION 'direct table RLS failed';END IF;
 result:=public.tj_runtime_manufacturer_assets('{"action":"trade"}');IF result->>'ok'<>'true' THEN RAISE EXCEPTION 'authenticated invoker wrapper failed';END IF;
END $$;
ROLLBACK;
SELECT 'PASS: native editor/reviewer/trade lifecycle, organization/vendor isolation, draft and file privacy, reserved owner/path/size/finalize, forbidden self-publish, revoked/deleted/unmapped denial, retained archived objects, RLS and private grants; metadata fixtures rolled back; actual file bytes/browser not exercised' result;
