BEGIN;
SET LOCAL statement_timeout='25s';
DO $$
DECLARE actor uuid; native uuid; other_actor uuid; other_native uuid; org uuid; foreign_org uuid; warranty uuid;
 body jsonb; result jsonb; pkg uuid; new_pkg uuid; before_count bigint; request jsonb; decision_request jsonb; manager_actor uuid; manager_native uuid; loop_decision text; v integer; stamp timestamptz;
BEGIN
 SELECT im.source_user_id,im.target_user_id INTO actor,native FROM tj.source_user_identity_map im JOIN auth.users u ON u.id=im.target_user_id WHERE tj_private.microsoft_actor(u.id)=im.source_user_id AND u.email_confirmed_at IS NOT NULL LIMIT 1;
 SELECT im.source_user_id,im.target_user_id INTO other_actor,other_native FROM tj.source_user_identity_map im JOIN auth.users u ON u.id=im.target_user_id WHERE tj_private.microsoft_actor(u.id)=im.source_user_id AND u.email_confirmed_at IS NOT NULL AND im.source_user_id<>actor LIMIT 1;
 IF native IS NULL OR other_native IS NULL THEN RAISE EXCEPTION 'missing mapped fixture identities'; END IF;
 INSERT INTO tj.organizations(name,slug) VALUES('Spec draft rollback fixture','spec-draft-rollback-'||gen_random_uuid()) RETURNING id INTO org;
 INSERT INTO tj.organizations(name,slug) VALUES('Spec foreign rollback fixture','spec-draft-rollback-'||gen_random_uuid()) RETURNING id INTO foreign_org;
 INSERT INTO tj.organization_members(organization_id,user_id,role,status) VALUES(org,actor,'member','active'),(org,other_actor,'viewer','active');
 INSERT INTO tj.speciq_warranty_catalog(organization_id,warranty_name,warranty_type,selling_price,active,is_included,applies_to_categories) VALUES(org,'Fixture coverage','extended',12.34,true,false,ARRAY['refrigerator']) RETURNING id INTO warranty;
 PERFORM set_config('request.jwt.claim.sub',native::text,true);
 result:=public.tj_runtime_speciq_drafts('{"action":"context"}');
 IF result->>'ok' IS DISTINCT FROM 'true' OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements(result->'organizations') o WHERE o->>'id'=org::text AND o->>'role'='member') OR EXISTS(SELECT 1 FROM jsonb_array_elements(result->'organizations') o WHERE o->>'id'=foreign_org::text) THEN RAISE EXCEPTION 'context isolation failed: %',result; END IF;
 body:=jsonb_build_object('action','save','organization_id',org,'request_id',gen_random_uuid(),'customer',jsonb_build_object('name','Fixture customer','project_name','Fixture project'),'package_name','Fixture draft','include_pricing',true,'products',jsonb_build_array(jsonb_build_object('product_name','Fixture refrigerator','brand','Fixture brand','category','refrigerator','msrp','10.01','quantity',2,'warranty_id',warranty)),'services',jsonb_build_array(jsonb_build_object('service_type','delivery','description','Fixture delivery','amount','5.10','taxable',true)));

 result:=public.tj_runtime_speciq_drafts(body);IF result->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'fixture draft failed: %',result;END IF;pkg:=(result->>'package_id')::uuid;
 UPDATE tj.organization_members SET role='manager' WHERE organization_id=org AND user_id=other_actor;
 manager_actor:=other_actor;manager_native:=other_native;
 SELECT jsonb_build_object('action','submit','organization_id',org,'package_id',id,'expected_version',version,'expected_updated_at',updated_at,'request_id',gen_random_uuid()) INTO request FROM tj.speciq_packages WHERE id=pkg;
 result:=public.tj_runtime_speciq_workflow(request);IF result->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'submission failed: %',result;END IF;
 result:=public.tj_runtime_speciq_workflow(request);IF result->>'replayed' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'submit retry duplicated';END IF;
 IF (SELECT count(*) FROM tj.speciq_approval_history WHERE package_id=pkg)<>1 OR NOT EXISTS(SELECT 1 FROM tj.speciq_packages WHERE id=pkg AND status='ready_for_review' AND approval_status='pending' AND submitted_by=actor AND total_tax IS NULL AND total_final IS NULL) THEN RAISE EXCEPTION 'submission contract wrong';END IF;
 SELECT jsonb_build_object('action','decide','organization_id',org,'package_id',id,'expected_version',version,'expected_updated_at',updated_at,'request_id',gen_random_uuid(),'decision','approved') INTO decision_request FROM tj.speciq_packages WHERE id=pkg;
 result:=public.tj_runtime_speciq_workflow(decision_request);IF result->>'error' IS DISTINCT FROM 'independent_manager_required' THEN RAISE EXCEPTION 'self approval allowed';END IF;
 PERFORM set_config('request.jwt.claim.sub',manager_native::text,true);
 result:=public.tj_runtime_speciq_workflow(decision_request||jsonb_build_object('request_id',gen_random_uuid(),'decision','approved_with_conditions'));IF result->>'error' IS DISTINCT FROM 'invalid_request' THEN RAISE EXCEPTION 'empty conditions approved';END IF;
 result:=public.tj_runtime_speciq_workflow(decision_request||jsonb_build_object('request_id',gen_random_uuid(),'decision','returned','comments','Correct draft details'));IF result->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'return failed: %',result;END IF;
 IF NOT EXISTS(SELECT 1 FROM tj.speciq_packages WHERE id=pkg AND status='draft' AND approval_status='returned' AND NOT locked AND reviewed_by=manager_actor AND returned_to_rep_at IS NOT NULL) THEN RAISE EXCEPTION 'returned state wrong';END IF;
 result:=public.tj_runtime_speciq_workflow(decision_request);IF result->>'error' IS DISTINCT FROM 'revision_conflict' THEN RAISE EXCEPTION 'stale manager decision accepted';END IF;
 PERFORM set_config('request.jwt.claim.sub',native::text,true);
 SELECT version,updated_at INTO v,stamp FROM tj.speciq_packages WHERE id=pkg;
 result:=public.tj_runtime_speciq_drafts(body||jsonb_build_object('request_id',gen_random_uuid(),'previous_package_id',pkg,'expected_version',v,'expected_updated_at',stamp));IF result->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'returned revision failed: %',result;END IF;new_pkg:=(result->>'package_id')::uuid;
 SELECT jsonb_build_object('action','submit','organization_id',org,'package_id',id,'expected_version',version,'expected_updated_at',updated_at,'request_id',gen_random_uuid()) INTO request FROM tj.speciq_packages WHERE id=new_pkg;
 result:=public.tj_runtime_speciq_workflow(request);IF result->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'new revision submission failed';END IF;
 PERFORM set_config('request.jwt.claim.sub',manager_native::text,true);
 SELECT jsonb_build_object('action','decide','organization_id',org,'package_id',id,'expected_version',version,'expected_updated_at',updated_at,'request_id',gen_random_uuid(),'decision','approved_with_conditions','conditions','Confirm installation details','comments','Draft reviewed') INTO decision_request FROM tj.speciq_packages WHERE id=new_pkg;
 result:=public.tj_runtime_speciq_workflow(decision_request);IF result->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'approval failed: %',result;END IF;
 result:=public.tj_runtime_speciq_workflow(decision_request);IF result->>'replayed' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'decision retry duplicated';END IF;
 result:=public.tj_runtime_speciq_workflow(decision_request||'{"comments":"Changed retry"}');IF result->>'error' IS DISTINCT FROM 'request_conflict' THEN RAISE EXCEPTION 'changed decision retry accepted';END IF;
 IF NOT EXISTS(SELECT 1 FROM tj.speciq_packages WHERE id=new_pkg AND status='in_progress' AND approval_status='approved_with_conditions' AND locked AND approved_by=manager_actor AND total_tax IS NULL AND total_final IS NULL AND sent_at IS NULL AND share_token IS NULL) OR NOT EXISTS(SELECT 1 FROM tj.speciq_approval_history WHERE package_id=new_pkg AND manager_decision='approved_with_conditions' AND assigned_manager=manager_actor AND conditions='Confirm installation details') THEN RAISE EXCEPTION 'approval atomic/source identity contract wrong';END IF;
 PERFORM set_config('request.jwt.claim.sub',native::text,true);
 SELECT jsonb_build_object('action','archive','organization_id',org,'package_id',id,'expected_version',version,'expected_updated_at',updated_at,'request_id',gen_random_uuid()) INTO request FROM tj.speciq_packages WHERE id=new_pkg;
 result:=public.tj_runtime_speciq_workflow(request);IF result->>'error' IS DISTINCT FROM 'forbidden' THEN RAISE EXCEPTION 'rep archived locked approval';END IF;
 PERFORM set_config('request.jwt.claim.sub',manager_native::text,true);
 result:=public.tj_runtime_speciq_workflow(request);IF result->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'archive failed: %',result;END IF;
 result:=public.tj_runtime_speciq_workflow(request);IF result->>'replayed' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'archive retry failed';END IF;
 IF NOT EXISTS(SELECT 1 FROM tj.speciq_packages WHERE id=new_pkg AND status='archived') OR (SELECT count(*) FROM tj.speciq_package_products WHERE package_id IN(pkg,new_pkg))<>2 OR (SELECT count(*) FROM tj.speciq_product_warranties WHERE package_id IN(pkg,new_pkg))<>2 OR (SELECT count(*) FROM tj.speciq_package_versions WHERE package_id IN(pkg,new_pkg))<>2 OR (SELECT count(*) FROM tj.speciq_projects WHERE organization_id=org)<>2 THEN RAISE EXCEPTION 'archive removed history';END IF;
 result:=public.tj_runtime_speciq_workflow(jsonb_build_object('action','list','organization_id',org));IF jsonb_array_length(result->'packages')<>0 THEN RAISE EXCEPTION 'archived revisions in active list';END IF;
 result:=public.tj_runtime_speciq_workflow(jsonb_build_object('action','get','organization_id',foreign_org,'package_id',new_pkg));IF result->>'error' IS DISTINCT FROM 'organization_access_required' THEN RAISE EXCEPTION 'foreign package access';END IF;
 UPDATE tj.organization_members SET status='suspended' WHERE organization_id=org AND user_id=manager_actor;
 result:=public.tj_runtime_speciq_workflow(request);IF result->>'error' IS DISTINCT FROM 'organization_access_required' THEN RAISE EXCEPTION 'suspended manager retry allowed';END IF;
 UPDATE tj.organization_members SET status='active' WHERE organization_id=org AND user_id=manager_actor;

 FOR loop_decision IN SELECT unnest(ARRAY['approved','rejected','withdrawn']) LOOP
 PERFORM set_config('request.jwt.claim.sub',native::text,true);
 result:=public.tj_runtime_speciq_drafts(body||jsonb_build_object('request_id',gen_random_uuid()));IF result->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'additional draft fixture failed';END IF;pkg:=(result->>'package_id')::uuid;
 SELECT jsonb_build_object('action','submit','organization_id',org,'package_id',id,'expected_version',version,'expected_updated_at',updated_at,'request_id',gen_random_uuid()) INTO request FROM tj.speciq_packages WHERE id=pkg;
 UPDATE tj.organization_members SET role='viewer' WHERE organization_id=org AND user_id=actor;
 result:=public.tj_runtime_speciq_workflow(request);IF result->>'error' IS DISTINCT FROM 'forbidden' THEN RAISE EXCEPTION 'viewer submitted';END IF;
 UPDATE tj.organization_members SET role='member' WHERE organization_id=org AND user_id=actor;
 result:=public.tj_runtime_speciq_workflow(request);IF result->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'additional submit failed';END IF;
 IF loop_decision<>'withdrawn' THEN
 PERFORM set_config('request.jwt.claim.sub',manager_native::text,true);
 SELECT jsonb_build_object('action','decide','organization_id',org,'package_id',id,'expected_version',version,'expected_updated_at',updated_at,'request_id',gen_random_uuid(),'decision',loop_decision,'comments','Fixture reason') INTO request FROM tj.speciq_packages WHERE id=pkg;
 result:=public.tj_runtime_speciq_workflow(request);IF result->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'additional decision failed: %',result;END IF;
 END IF;
 SELECT jsonb_build_object('action','archive','organization_id',org,'package_id',id,'expected_version',version,'expected_updated_at',updated_at,'request_id',gen_random_uuid()) INTO request FROM tj.speciq_packages WHERE id=pkg;
 result:=public.tj_runtime_speciq_workflow(request);IF result->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'additional archive failed: %',result;END IF;
 IF NOT EXISTS(SELECT 1 FROM tj.speciq_approval_history WHERE package_id=pkg AND manager_decision=loop_decision) OR NOT EXISTS(SELECT 1 FROM tj.speciq_package_products WHERE package_id=pkg) THEN RAISE EXCEPTION 'approve/reject/withdraw history or retained content wrong';END IF;
 END LOOP;
 PERFORM set_config('test.review.native',manager_native::text,true);PERFORM set_config('test.review.org',org::text,true);PERFORM set_config('test.review.pkg',new_pkg::text,true);
 IF has_function_privilege('anon','public.tj_runtime_speciq_workflow(jsonb)','EXECUTE') OR has_table_privilege('authenticated','tj.speciq_packages','UPDATE') OR has_table_privilege('authenticated','tj.speciq_packages','DELETE') THEN RAISE EXCEPTION 'direct grants opened';END IF;
END $$;
SET LOCAL ROLE authenticated;
DO $$DECLARE result jsonb;BEGIN
 PERFORM set_config('request.jwt.claim.sub',current_setting('test.review.native'),true);
 result:=public.tj_runtime_speciq_workflow(jsonb_build_object('action','get','organization_id',current_setting('test.review.org'),'package_id',current_setting('test.review.pkg')));IF result->>'ok' IS DISTINCT FROM 'true' OR jsonb_array_length(result->'history')<>1 THEN RAISE EXCEPTION 'actual authenticated wrapper/history failed: %',result;END IF;
 PERFORM set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);result:=public.tj_runtime_speciq_workflow(jsonb_build_object('action','list','organization_id',current_setting('test.review.org')));IF result->>'error' IS DISTINCT FROM 'identity_review_required' THEN RAISE EXCEPTION 'unmapped user allowed';END IF;
END $$;
ROLLBACK;
SELECT 'PASS: independent manager submit/return/revise/resubmit/approve/conditional approve/reject/withdraw/archive with exact source identities; snapshots/products/warranties/projects retained; retry/conflict/stale/self/foreign/suspended/unmapped denial; actual authenticated wrapper; no final tax/send/share or direct writes; fixtures rolled back' result;
