begin;
set local statement_timeout='30s';
do $$ declare native uuid; actor uuid; org uuid; foreign_org uuid; account uuid; contact uuid; campaign uuid; enroll uuid; begin
 select im.target_user_id,im.source_user_id,m.organization_id into native,actor,org
 from tj.source_user_identity_map im join tj.organization_members m on m.user_id=im.source_user_id join tj.organizations o on o.id=m.organization_id
 where im.activation_status='activated' and m.status='active' and m.role in ('owner','admin') and o.status='active' and o.deleted_at is null limit 1;
 if native is null then raise exception 'missing_native_fixture'; end if;
 perform set_config('request.jwt.claim.sub',native::text,true);
 if tj_private.current_source_user_id() is distinct from actor then raise exception 'fixture_mapping_not_verified'; end if;
 insert into tj.organizations(name,slug) values('Rollback primary fixture','rollback-primary-'||gen_random_uuid()) returning id into org;
 insert into tj.organization_members(organization_id,user_id,role,status) values(org,actor,'admin','active');
 perform set_config('test.batch.native',native::text,true); perform set_config('test.batch.actor',actor::text,true); perform set_config('test.batch.org',org::text,true);
 delete from tj.product_iq_platform_roles where user_id=actor;
 insert into tj.product_iq_platform_roles(user_id,role,status) values(actor,'data_publisher','active');
 insert into tj.organizations(name,slug) values('Rollback sequence fixture','rollback-sequence-'||gen_random_uuid()) returning id into foreign_org;
 perform set_config('test.batch.foreign',foreign_org::text,true);
 insert into tj.aicrm_accounts(organization_id,company_name) values(org,'Rollback fixture') returning id into account;
 insert into tj.aicrm_contacts(organization_id,account_id,full_name,email) values(org,account,'Rollback fixture','synthetic@example.invalid') returning id into contact;
 insert into tj.aicrm_outreach_campaigns(organization_id,name,campaign_type,status) values(org,'Rollback fixture','Appliance Dealer','active') returning id into campaign;
 insert into tj.aicrm_sequence_steps(organization_id,campaign_id,step_number,delay_days,channel,subject_template,body_template) values(org,campaign,1,0,'email','PRIVATE SUBJECT','PRIVATE BODY');
 insert into tj.aicrm_sequence_enrollments(organization_id,account_id,contact_id,campaign_id,next_action_at) values(org,account,contact,campaign,now()-interval '1 hour') returning id into enroll;
 perform set_config('test.batch.enrollment',enroll::text,true);perform set_config('test.batch.campaign',campaign::text,true);perform set_config('test.batch.contact',contact::text,true);perform set_config('test.batch.account',account::text,true);
end $$;
set local role authenticated;
do $$ declare r jsonb; rawid uuid; prefix text:='rollback-'||gen_random_uuid();bad jsonb;begin
 r:=public.tj_scraper_write(jsonb_build_object('table','retailer_discovered_products','operation','insert','data',jsonb_build_object('retailer_name',prefix,'brand_name','fixture','model','one')));
 if r->>'count'<>'1' or r#>>'{data,0,country}'<>'CA' or r#>>'{data,0,condition}'<>'new' or r->>'verified_catalog_updated'<>'false' then raise exception 'insert_defaults_failed';end if;
 rawid:=(r#>>'{data,0,id}')::uuid;perform set_config('test.batch.raw',rawid::text,true);perform set_config('test.batch.prefix',prefix,true);
 r:=public.tj_scraper_write(jsonb_build_object('table','retailer_discovered_products','operation','upsert','conflict_columns','retailer_name,brand_name,model,condition,country','data',jsonb_build_object('retailer_name',prefix,'brand_name','fixture','model','one','condition','new','country','CA','price',123)));
 if r#>>'{data,0,id}'<>rawid::text or r#>>'{data,0,price}'<>'123' then raise exception 'upsert_failed';end if;
 r:=public.tj_scraper_write(jsonb_build_object('table','retailer_discovered_products','operation','update','match',jsonb_build_object('id',jsonb_build_array(rawid),'product_url',null),'data',jsonb_build_object('price',321)));
 if r->>'count'<>'1' or r#>>'{data,0,price}'<>'321' then raise exception 'match_array_null_failed'; end if;
 for bad in select value from jsonb_array_elements('[{"table":"retailer_discovered_products","operation":"update","data":{"price":1}},{"table":"retailer_discovered_products","operation":"update","match":{"id":"ignored"},"data":{"id":"11111111-1111-4111-8111-111111111111"}},{"table":"retailer_discovered_products","operation":"insert","data":{"aiq_product_id":null}},{"table":"retailer_discovered_products","operation":"insert","data":{"organization_id":null}},{"table":"retailer_discovered_products","operation":"upsert","conflict_columns":"price);drop table public.products;--","data":{"price":1}},{"table":"pim_brand_content","operation":"delete","match":{"id":"ignored"}},{"table":"scraper_retailer_sources","operation":"insert","data":{"retailer_name":"no"}}]') loop
  begin perform public.tj_scraper_write(bad);raise exception 'invalid_request_accepted';exception when invalid_parameter_value then null;end;
 end loop;
 r:=public.tj_scraper_write('{"table":"aiq_products","operation":"insert","data":{"model":"no"}}');if r->>'error'<>'governed_catalog_write_required' then raise exception 'curated_write_accepted';end if;
 begin perform public.tj_scraper_write(jsonb_build_object('table','retailer_discovered_products','operation','insert','data',jsonb_build_array(jsonb_build_object('retailer_name',prefix,'brand_name','fixture','model','atomic'),jsonb_build_object('retailer_name',prefix))));raise exception 'invalid_batch_accepted';exception when not_null_violation then null;end;
 r:=public.tj_scraper_write(jsonb_build_object('table','retailer_discovered_products','operation','delete','match',jsonb_build_object('id',rawid)));
 if r->>'count'<>'1' then raise exception 'delete_failed';end if;
 perform public.tj_scraper_write('{"table":"retailer_crawl_runs","operation":"insert","data":{"retailer_name":"rollback-fixture","crawl_url":"https://example.invalid/fixture"}}');
 perform public.tj_scraper_write('{"table":"retailer_brand_pages","operation":"insert","data":{"retailer_name":"rollback-fixture","brand_name":"rollback-fixture","brand_page_url":"https://example.invalid"}}');
 perform public.tj_scraper_write('{"table":"brand_category_pages","operation":"insert","data":{"brand_name":"rollback-fixture","category":"rollback-fixture","page_url":"https://example.invalid"}}');
 perform public.tj_scraper_write('{"table":"pim_scrape_runs","operation":"insert","data":{"retailer_name":"rollback-fixture"}}');
 perform public.tj_scraper_write('{"table":"pim_brand_content","operation":"insert","data":{"brand_name":"rollback-fixture","url":"https://example.invalid/rollback"}}');
 perform public.tj_scraper_write(jsonb_build_object('table','scraper_retailer_sources','operation','update','data',jsonb_build_object('total_products_found',0),'match',jsonb_build_object('id',gen_random_uuid())));
 r:=public.tj_sequence_preview(jsonb_build_object('organization_id',current_setting('test.batch.org'),'limit',100));
 if r->>'send_enabled'<>'false' or r->>'sent'<>'0' or r->>'executed'<>'false' or not exists(select 1 from jsonb_array_elements(r->'data') d where d->>'enrollment_id'=current_setting('test.batch.enrollment')) or r::text like '%PRIVATE%' or r::text like '%example.invalid%' then raise exception 'preview_failed_or_leaked';end if;
 r:=public.tj_sequence_preview(jsonb_build_object('action','execute','organization_id',current_setting('test.batch.org')));if r->>'error'<>'sequence_sending_verification_required' or r->>'sent'<>'0' then raise exception 'send_accepted';end if;
 begin perform public.tj_sequence_preview(jsonb_build_object('organization_id',current_setting('test.batch.foreign')));raise exception 'foreign_org_accepted';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
 begin perform public.tj_scraper_write('{"table":"pim_scrape_runs","operation":"insert","data":{"status":"running"}}');raise exception 'unmapped_scraper_accepted';exception when insufficient_privilege then null;end;
 begin perform public.tj_sequence_preview(jsonb_build_object('organization_id',current_setting('test.batch.org')));raise exception 'unmapped_preview_accepted';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',current_setting('test.batch.native'),true);
end $$;
reset role;
do $$begin
 if exists(select 1 from tj.retailer_discovered_products where retailer_name=current_setting('test.batch.prefix') and model='atomic') then raise exception 'partial_batch_persisted';end if;
 if not exists(select 1 from tj_private.scraper_write_audit where source_user_id=current_setting('test.batch.actor')::uuid) then raise exception 'missing_audit';end if;
 if exists(select 1 from tj.aicrm_sequence_enrollments where id=current_setting('test.batch.enrollment')::uuid and (last_contacted_at is not null or current_step<>1)) then raise exception 'preview_mutated_enrollment';end if;
 update tj.product_iq_platform_roles set role='data_reviewer' where user_id=current_setting('test.batch.actor')::uuid;
 insert into tj.retailer_discovered_products(retailer_name,brand_name,model) select current_setting('test.batch.prefix'),'fixture','many-'||i from generate_series(1,101) i;
end $$;
set local role authenticated;
do $$begin begin perform public.tj_scraper_write('{"table":"pim_scrape_runs","operation":"insert","data":{"status":"running"}}');raise exception 'reviewer_write_accepted';exception when insufficient_privilege then null;end;end $$;
reset role;
update tj.product_iq_platform_roles set role='data_publisher',organization_id=current_setting('test.batch.org')::uuid where user_id=current_setting('test.batch.actor')::uuid;
set local role authenticated;
do $$begin begin perform public.tj_scraper_write('{"table":"pim_scrape_runs","operation":"insert","data":{"status":"running"}}');raise exception 'org_scoped_shared_write_accepted';exception when insufficient_privilege then null;end;end $$;
reset role;
update tj.product_iq_platform_roles set organization_id=null where user_id=current_setting('test.batch.actor')::uuid;
set local role authenticated;
do $$begin begin perform public.tj_scraper_write(jsonb_build_object('table','retailer_discovered_products','operation','delete','match',jsonb_build_object('retailer_name',current_setting('test.batch.prefix'))));raise exception 'broad_match_accepted';exception when program_limit_exceeded then null;end;end $$;
reset role;
insert into tj.aicrm_sequence_enrollments(organization_id,account_id,contact_id,campaign_id,next_action_at) values(current_setting('test.batch.org')::uuid,current_setting('test.batch.account')::uuid,current_setting('test.batch.contact')::uuid,current_setting('test.batch.campaign')::uuid,now()-interval '1 hour');
set local role authenticated;
do $$declare r jsonb;p jsonb;begin
 r:=public.tj_sequence_preview(jsonb_build_object('organization_id',current_setting('test.batch.org'),'limit',1));
 if r->>'count'<>'1' or r->>'next_cursor' is null then raise exception 'missing_page_cursor';end if;
 p:=public.tj_sequence_preview(jsonb_build_object('organization_id',current_setting('test.batch.org'),'limit',1,'cursor',r->>'next_cursor'));
 if p->>'count'<>'1' or p->>'next_cursor' is not null or p#>>'{data,0,enrollment_id}'=r#>>'{data,0,enrollment_id}' then raise exception 'paging_failed';end if;
end $$;
reset role;
update tj.aicrm_sequence_enrollments set last_contacted_at=now() where campaign_id=current_setting('test.batch.campaign')::uuid;
update tj.aicrm_sequence_steps set delay_days=1 where campaign_id=current_setting('test.batch.campaign')::uuid;
set local role authenticated;
do $$declare r jsonb;begin r:=public.tj_sequence_preview(jsonb_build_object('organization_id',current_setting('test.batch.org')));if r->>'count'<>'0' then raise exception 'delay_ignored';end if;end $$;
reset role;
update tj.aicrm_sequence_steps set delay_days=0 where campaign_id=current_setting('test.batch.campaign')::uuid;
update tj.aicrm_sequence_enrollments set next_action_at=now()+interval '1 day' where campaign_id=current_setting('test.batch.campaign')::uuid;
set local role authenticated;
do $$declare r jsonb;begin r:=public.tj_sequence_preview(jsonb_build_object('organization_id',current_setting('test.batch.org')));if r->>'count'<>'0' then raise exception 'future_action_included';end if;end $$;
reset role;
update tj.aicrm_sequence_enrollments set next_action_at=now()-interval '1 hour' where campaign_id=current_setting('test.batch.campaign')::uuid;
update tj.aicrm_sequence_steps set organization_id=current_setting('test.batch.foreign')::uuid where campaign_id=current_setting('test.batch.campaign')::uuid;
set local role authenticated;
do $$declare r jsonb;begin r:=public.tj_sequence_preview(jsonb_build_object('organization_id',current_setting('test.batch.org')));if r->>'count'<>'0' then raise exception 'cross_org_step_included';end if;end $$;
reset role;
update tj.aicrm_sequence_steps set organization_id=current_setting('test.batch.org')::uuid where campaign_id=current_setting('test.batch.campaign')::uuid;
update tj.aicrm_contacts set organization_id=current_setting('test.batch.foreign')::uuid where id=current_setting('test.batch.contact')::uuid;
set local role authenticated;
do $$declare r jsonb;begin r:=public.tj_sequence_preview(jsonb_build_object('organization_id',current_setting('test.batch.org'),'limit',100));if exists(select 1 from jsonb_array_elements(r->'data')d where d->>'enrollment_id'=current_setting('test.batch.enrollment')) then raise exception 'cross_org_contact_leaked';end if;end $$;
reset role;
update tj.aicrm_contacts set organization_id=current_setting('test.batch.org')::uuid where id=current_setting('test.batch.contact')::uuid;
update tj.aicrm_accounts set do_not_contact=true where id=current_setting('test.batch.account')::uuid;
set local role authenticated;
do $$declare r jsonb;begin r:=public.tj_sequence_preview(jsonb_build_object('organization_id',current_setting('test.batch.org'),'limit',100));if exists(select 1 from jsonb_array_elements(r->'data')d where d->>'enrollment_id'=current_setting('test.batch.enrollment')) then raise exception 'do_not_contact_included';end if;end $$;
reset role;
update tj.organization_members set role='member' where user_id=current_setting('test.batch.actor')::uuid and organization_id=current_setting('test.batch.org')::uuid;
set local role authenticated;
do $$begin begin perform public.tj_sequence_preview(jsonb_build_object('organization_id',current_setting('test.batch.org')));raise exception 'nonadmin_preview_accepted';exception when insufficient_privilege then null;end;end $$;
reset role;
do $$declare f text;r text;begin
 foreach f in array array['public.tj_scraper_write(jsonb)','public.tj_sequence_preview(jsonb)','tj_private.scraper_write(jsonb)','tj_private.sequence_preview(jsonb)'] loop
  foreach r in array array['anon','service_role'] loop if has_function_privilege(r,f,'EXECUTE') then raise exception 'unsafe_function_grant';end if;end loop;
 end loop;
 if has_table_privilege('authenticated','tj_private.scraper_write_audit','SELECT,INSERT,UPDATE,DELETE') or has_table_privilege('service_role','tj_private.scraper_write_audit','SELECT,INSERT,UPDATE,DELETE') then raise exception 'audit_direct_access';end if;
end $$;
rollback;
select jsonb_build_object('passed',true,'fixture','scraper imports and sequence preview','persisted_fixture_rows',0) as verification;
