begin;set local statement_timeout='30s';
do $$declare native uuid;actor uuid;org uuid;other uuid;r uuid;r2 uuid;t uuid;begin
 select im.target_user_id,im.source_user_id into native,actor from tj.source_user_identity_map im join tj.organization_members m on m.user_id=im.source_user_id join tj.organizations o on o.id=m.organization_id where im.activation_status='activated' and m.status='active' and m.role in ('owner','admin') and o.status='active' and o.deleted_at is null limit 1;
 if native is null then raise exception 'missing_fixture';end if;
 perform set_config('test.review.original',(select jsonb_build_array((select md5(coalesce(jsonb_agg(x order by id)::text,'')) from tj.sales_recordings x),(select md5(coalesce(jsonb_agg(x order by id)::text,'')) from tj.recording_transcripts x),(select md5(coalesce(jsonb_agg(x order by id)::text,'')) from tj.ai_coaching_reviews x))::text),true);
 insert into tj.organizations(name,slug) values('Rollback review','rollback-review-'||gen_random_uuid()) returning id into org;
 insert into tj.organizations(name,slug) values('Rollback foreign review','rollback-review-foreign-'||gen_random_uuid()) returning id into other;
 insert into tj.organization_members(organization_id,user_id,role,status) values(org,actor,'admin','active');
 insert into tj.sales_recordings(organization_id,user_id,file_path,consent_confirmed) values(org,actor,'PRIVATE PATH',false) returning id into r;
 insert into tj.sales_recordings(organization_id,user_id,file_path,consent_confirmed) values(org,null,'PRIVATE PATH OTHER',true) returning id into r2;
 insert into tj.recording_transcripts(organization_id,recording_id,content,status) values(org,r,'PRIVATE TRANSCRIPT','completed') returning id into t;
 update tj.sales_recordings set transcript_id=t where id=r;
 perform set_config('request.jwt.claim.sub',native::text,true);
 perform set_config('test.review.native',native::text,true);perform set_config('test.review.actor',actor::text,true);perform set_config('test.review.org',org::text,true);perform set_config('test.review.other',other::text,true);perform set_config('test.review.r',r::text,true);perform set_config('test.review.r2',r2::text,true);perform set_config('test.review.t',t::text,true);
end $$;
set local role authenticated;
do $$declare x jsonb;begin
 x:=public.tj_recording_review_preflight(jsonb_build_object('recording_id',current_setting('test.review.r'),'action','status'));
 if x->>'ok'<>'true' or x->>'transcript_metadata_checked'<>'false' then raise exception 'unconsented_transcript_checked';end if;
 x:=public.tj_recording_review_preflight(jsonb_build_object('recording_id',current_setting('test.review.r')));
 if x->>'error'<>'consent_required' or x->>'executed'<>'false' then raise exception 'consent_bypassed';end if;
 begin perform public.tj_recording_review_preflight(jsonb_build_object('recording_id',current_setting('test.review.r'),'organization_id',current_setting('test.review.other')));raise exception 'org_mismatch_accepted';exception when insufficient_privilege then null;end;
 begin perform public.tj_recording_review_preflight(jsonb_build_object('recording_id',current_setting('test.review.r'),'transcript','PRIVATE'));raise exception 'transcript_payload_accepted';exception when invalid_parameter_value then null;end;
 perform set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
 begin perform public.tj_recording_review_preflight(jsonb_build_object('recording_id',current_setting('test.review.r')));raise exception 'unmapped_accepted';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',current_setting('test.review.native'),true);
end $$;
reset role;
update tj.sales_recordings set consent_confirmed=true where id=current_setting('test.review.r')::uuid;
set local role authenticated;
do $$declare x jsonb;begin
 x:=public.tj_recording_review_preflight(jsonb_build_object('recording_id',current_setting('test.review.r'),'action','status'));
 if x->>'completed_transcript_linked'<>'true' or x::text like '%PRIVATE%' or x ? 'transcript_id' then raise exception 'unsafe_metadata';end if;
 x:=public.tj_recording_review_preflight(jsonb_build_object('recording_id',current_setting('test.review.r')));
 if x->>'error'<>'recording_review_verification_required' or x->>'provider_called'<>'false' or x->>'reviews_created'<>'0' then raise exception 'review_executed';end if;
end $$;
reset role;
update tj.recording_transcripts set organization_id=current_setting('test.review.other')::uuid where id=current_setting('test.review.t')::uuid;
set local role authenticated;
do $$declare x jsonb;begin x:=public.tj_recording_review_preflight(jsonb_build_object('recording_id',current_setting('test.review.r')));if x->>'error'<>'completed_transcript_required' then raise exception 'foreign_transcript_accepted';end if;end $$;
reset role;
update tj.recording_transcripts set organization_id=current_setting('test.review.org')::uuid,recording_id=current_setting('test.review.r2')::uuid where id=current_setting('test.review.t')::uuid;
set local role authenticated;
do $$declare x jsonb;begin x:=public.tj_recording_review_preflight(jsonb_build_object('recording_id',current_setting('test.review.r')));if x->>'error'<>'completed_transcript_required' then raise exception 'wrong_recording_transcript_accepted';end if;end $$;
reset role;
update tj.recording_transcripts set recording_id=current_setting('test.review.r')::uuid,status='failed' where id=current_setting('test.review.t')::uuid;
set local role authenticated;
do $$declare x jsonb;begin x:=public.tj_recording_review_preflight(jsonb_build_object('recording_id',current_setting('test.review.r')));if x->>'error'<>'completed_transcript_required' then raise exception 'failed_transcript_accepted';end if;end $$;
reset role;
update tj.recording_transcripts set status='completed' where id=current_setting('test.review.t')::uuid;
update tj.sales_recordings set transcript_id=null where id=current_setting('test.review.r')::uuid;
update tj.organization_members set role='member' where organization_id=current_setting('test.review.org')::uuid and user_id=current_setting('test.review.actor')::uuid;
set local role authenticated;
do $$declare x jsonb;begin
 x:=public.tj_recording_review_preflight(jsonb_build_object('recording_id',current_setting('test.review.r'),'action','status'));if x->>'completed_transcript_linked'<>'true' then raise exception 'owner_scoped_fallback_failed';end if;
 begin perform public.tj_recording_review_preflight(jsonb_build_object('recording_id',current_setting('test.review.r2')));raise exception 'unowned_recording_accepted';exception when insufficient_privilege then null;end;
end $$;
reset role;
update tj.organization_members set status='suspended' where organization_id=current_setting('test.review.org')::uuid and user_id=current_setting('test.review.actor')::uuid;
set local role authenticated;
do $$begin begin perform public.tj_recording_review_preflight(jsonb_build_object('recording_id',current_setting('test.review.r')));raise exception 'suspended_owner_accepted';exception when insufficient_privilege then null;end;end $$;
reset role;
do $$declare f text;r text;begin
 foreach f in array array['public.tj_recording_review_preflight(jsonb)','tj_private.recording_review_preflight(jsonb)'] loop foreach r in array array['anon','service_role'] loop if has_function_privilege(r,f,'EXECUTE') then raise exception 'unsafe_grants';end if;end loop;end loop;
 if exists(select 1 from tj.sales_recordings where id in (current_setting('test.review.r')::uuid,current_setting('test.review.r2')::uuid) and (status<>'uploaded' or coaching_review_id is not null)) then raise exception 'review_marker_mutated';end if;
 if (select jsonb_build_array((select md5(coalesce(jsonb_agg(x order by id)::text,'')) from tj.sales_recordings x where organization_id not in (current_setting('test.review.org')::uuid,current_setting('test.review.other')::uuid)),(select md5(coalesce(jsonb_agg(x order by id)::text,'')) from tj.recording_transcripts x where organization_id not in (current_setting('test.review.org')::uuid,current_setting('test.review.other')::uuid)),(select md5(coalesce(jsonb_agg(x order by id)::text,'')) from tj.ai_coaching_reviews x))::text)<>current_setting('test.review.original') then raise exception 'existing_data_mutated';end if;
end $$;
rollback;
select jsonb_build_object('passed',true,'fixture','recording review preflight','persisted_rows',0) verification;
