begin;set local statement_timeout='30s';
do $$declare native uuid;actor uuid;org uuid;other uuid;retailer uuid;client uuid;location uuid;store uuid;visit uuid;second_visit uuid;foreign_client uuid;foreign_visit uuid;media uuid;second_media uuid;begin
 select im.target_user_id,im.source_user_id,m.organization_id into native,actor,org from tj.source_user_identity_map im join tj.organization_members m on m.user_id=im.source_user_id join tj.organizations o on o.id=m.organization_id where im.activation_status='activated' and m.status='active' and m.role in ('owner','admin') and o.status='active' and o.deleted_at is null and not exists(select 1 from tj.platform_admins a where a.user_id=im.source_user_id) limit 1;
 select id into other from tj.organizations o where not exists(select 1 from tj.organization_members m where m.organization_id=o.id and m.user_id=actor and m.status='active') limit 1;
 select id into retailer from tj.field_retailers limit 1;if native is null or retailer is null or other is null then raise exception 'missing_fixture';end if;
 insert into tj.field_clients(organization_id,client_name,status) values(org,'Rollback photo client','active') returning id into client;
 insert into tj.org_locations(organization_id,location_type,name,is_active) values(org,'store','Rollback photo store',true) returning id into location;
 insert into tj.field_stores(retailer_id,org_location_id,store_name,status) values(retailer,location,'Rollback photo store','active') returning id into store;
 insert into tj.field_visits(client_id,store_id,rep_user_id,status) values(client,store,actor,'scheduled') returning id into visit;
 insert into tj.field_visits(client_id,store_id,rep_user_id,status) values(client,store,actor,'scheduled') returning id into second_visit;
 insert into tj.field_media(visit_id,media_type,storage_path,file_size,mime_type,caption,metadata) values(visit,'photo','PRIVATE/PATH',1234,'image/jpeg','PRIVATE CAPTION','{"private":"PRIVATE METADATA"}') returning id into media;
 insert into tj.field_media(visit_id,media_type,storage_path,file_size,mime_type) values(second_visit,'photo','PRIVATE SECOND',1234,'image/png') returning id into second_media;
 insert into tj.field_clients(organization_id,client_name,status) values(other,'Rollback foreign photo client','active') returning id into foreign_client;
 insert into tj.field_visits(client_id,store_id,rep_user_id,status) values(foreign_client,store,actor,'scheduled') returning id into foreign_visit;
 perform set_config('request.jwt.claim.sub',native::text,true);perform set_config('test.photo.native',native::text,true);perform set_config('test.photo.actor',actor::text,true);perform set_config('test.photo.org',org::text,true);perform set_config('test.photo.other',other::text,true);perform set_config('test.photo.visit',visit::text,true);perform set_config('test.photo.foreign',foreign_visit::text,true);perform set_config('test.photo.media',media::text,true);perform set_config('test.photo.second_media',second_media::text,true);perform set_config('test.photo.client',client::text,true);
end $$;
set local role authenticated;
do $$declare r jsonb;k text;begin
 r:=public.tj_field_photo_preflight(jsonb_build_object('visit_id',current_setting('test.photo.visit'),'media_id',current_setting('test.photo.media'),'mode','status'));
 if r->>'ok'<>'true' or r->>'metadata_eligible'<>'true' or r->>'analysis_enabled'<>'false' or r->>'storage_verified'<>'false' or r::text like '%PRIVATE%' then raise exception 'unsafe_photo_status';end if;
 r:=public.tj_field_photo_preflight(jsonb_build_object('visit_id',current_setting('test.photo.visit'),'media_id',current_setting('test.photo.media')));if r->>'error'<>'field_photo_verification_required' or r->>'detections_created'<>'0' then raise exception 'analysis_enabled';end if;
 begin perform public.tj_field_photo_preflight(jsonb_build_object('visit_id',current_setting('test.photo.visit'),'media_id',current_setting('test.photo.second_media')));raise exception 'mismatched_media_accepted';exception when insufficient_privilege then null;end;
 begin perform public.tj_field_photo_preflight(jsonb_build_object('visit_id',current_setting('test.photo.foreign'),'media_id',current_setting('test.photo.media')));raise exception 'foreign_client_accepted';exception when insufficient_privilege then null;end;
 begin perform public.tj_field_photo_preflight(jsonb_build_object('visit_id',current_setting('test.photo.visit'),'media_id',current_setting('test.photo.media'),'organization_id',current_setting('test.photo.other')));raise exception 'foreign_org_accepted';exception when insufficient_privilege then null;end;
 foreach k in array array['image_base64','image_url'] loop begin perform public.tj_field_photo_preflight(jsonb_build_object('visit_id',current_setting('test.photo.visit'),'media_id',current_setting('test.photo.media'),k,'PRIVATE UNSCOPED INPUT'));raise exception 'unscoped_image_accepted';exception when invalid_parameter_value then null;end;end loop;
 perform set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
 begin perform public.tj_field_photo_preflight(jsonb_build_object('visit_id',current_setting('test.photo.visit'),'media_id',current_setting('test.photo.media')));raise exception 'unmapped_accepted';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',current_setting('test.photo.native'),true);
end $$;
reset role;
update tj.field_media set file_size=10485761 where id=current_setting('test.photo.media')::uuid;
set local role authenticated;
do $$declare r jsonb;begin r:=public.tj_field_photo_preflight(jsonb_build_object('visit_id',current_setting('test.photo.visit'),'media_id',current_setting('test.photo.media')));if r->>'error'<>'photo_metadata_not_eligible' then raise exception 'oversize_accepted';end if;end $$;
reset role;
update tj.field_clients set status='paused' where id=current_setting('test.photo.client')::uuid;
set local role authenticated;
do $$begin begin perform public.tj_field_photo_preflight(jsonb_build_object('visit_id',current_setting('test.photo.visit'),'media_id',current_setting('test.photo.media')));raise exception 'inactive_client_accepted';exception when insufficient_privilege then null;end;end $$;
reset role;
update tj.field_clients set status='active' where id=current_setting('test.photo.client')::uuid;
update tj.organization_members set role='member' where organization_id=current_setting('test.photo.org')::uuid and user_id=current_setting('test.photo.actor')::uuid;
update tj.field_visits set rep_user_id=(select id from tj.profiles where id<>current_setting('test.photo.actor')::uuid limit 1) where id=current_setting('test.photo.visit')::uuid;
set local role authenticated;
do $$begin begin perform public.tj_field_photo_preflight(jsonb_build_object('visit_id',current_setting('test.photo.visit'),'media_id',current_setting('test.photo.media')));raise exception 'nonowner_nonadmin_accepted';exception when insufficient_privilege then null;end;end $$;
reset role;
do $$declare f text;r text;begin
 foreach f in array array['public.tj_field_photo_preflight(jsonb)','tj_private.field_photo_preflight(jsonb)'] loop foreach r in array array['anon','service_role'] loop if has_function_privilege(r,f,'EXECUTE') then raise exception 'unsafe_grants';end if;end loop;end loop;
 if exists(select 1 from tj.field_ai_detections where visit_id=current_setting('test.photo.visit')::uuid) or exists(select 1 from tj.field_media where id=current_setting('test.photo.media')::uuid and ai_processed) then raise exception 'photo_results_written';end if;
end $$;
rollback;
select jsonb_build_object('passed',true,'fixture','field photo ownership and metadata readiness','persisted_rows',0) verification;
