BEGIN;
SET LOCAL statement_timeout='25s';
DO $$
DECLARE actor uuid;native uuid;other_actor uuid;other_native uuid;org uuid;foreign_org uuid;body jsonb;r jsonb;v_project_id uuid;stamp timestamptz;pkg uuid;historical uuid;
BEGIN
 SELECT im.source_user_id,im.target_user_id INTO actor,native FROM tj.source_user_identity_map im JOIN auth.users u ON u.id=im.target_user_id WHERE tj_private.microsoft_actor(u.id)=im.source_user_id AND u.email_confirmed_at IS NOT NULL AND NOT EXISTS(SELECT 1 FROM tj.platform_admins p WHERE p.user_id=im.source_user_id) LIMIT 1;
 SELECT im.source_user_id,im.target_user_id INTO other_actor,other_native FROM tj.source_user_identity_map im JOIN auth.users u ON u.id=im.target_user_id WHERE tj_private.microsoft_actor(u.id)=im.source_user_id AND u.email_confirmed_at IS NOT NULL AND im.source_user_id<>actor LIMIT 1;
 IF native IS NULL OR other_native IS NULL THEN RAISE EXCEPTION 'mapped fixture identity missing';END IF;
 INSERT INTO tj.organizations(name,slug) VALUES('Spec projects rollback fixture','spec-projects-rollback-'||gen_random_uuid()) RETURNING organizations.id INTO org;
 INSERT INTO tj.organizations(name,slug) VALUES('Spec projects rollback fixture','spec-projects-rollback-'||gen_random_uuid()) RETURNING organizations.id INTO foreign_org;
 INSERT INTO tj.organization_members(organization_id,user_id,role,status) VALUES(org,actor,'member','active'),(org,other_actor,'viewer','active');
 PERFORM set_config('request.jwt.claim.sub',native::text,true);
 body:=jsonb_build_object('action','create','organization_id',org,'request_id',gen_random_uuid(),'project',jsonb_build_object('project_name','<script>','customer_name','Fixture','customer_email','fixture@example.invalid','customer_phone','123','builder_name','Builder','designer_name','Designer','expected_purchase_date','2026-12-01','delivery_date','2026-12-02','notes','Keep these details'));
 r:=public.tj_runtime_speciq_projects(body);IF r->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'create failed %',r;END IF;v_project_id:=(r->>'project_id')::uuid;
 IF NOT EXISTS(SELECT 1 FROM tj.speciq_projects WHERE speciq_projects.id=v_project_id AND created_by=actor AND builder_name='Builder' AND designer_name='Designer' AND notes='Keep these details' AND delivery_date='2026-12-02') THEN RAISE EXCEPTION 'project facts/source actor lost';END IF;
 r:=public.tj_runtime_speciq_projects(body);IF r->>'replayed' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'create replay failed %',r;END IF;
 r:=public.tj_runtime_speciq_projects(body||jsonb_build_object('project','{}'::jsonb));IF r->>'error' IS DISTINCT FROM 'request_conflict' THEN RAISE EXCEPTION 'request conflict allowed';END IF;
 r:=public.tj_runtime_speciq_projects(body||jsonb_build_object('request_id',gen_random_uuid(),'project',body->'project'||jsonb_build_object('delivery_date','2026-02-30')));IF r->>'error' IS DISTINCT FROM 'invalid_request' THEN RAISE EXCEPTION 'invalid date allowed %',r;END IF;
 r:=public.tj_runtime_speciq_projects(jsonb_build_object('action','list','organization_id',org));IF jsonb_array_length(r->'projects')<>1 OR r#>>'{projects,0,can_edit}'<>'true' THEN RAISE EXCEPTION 'list permissions failed %',r;END IF;
 SELECT updated_at INTO stamp FROM tj.speciq_projects WHERE speciq_projects.id=v_project_id;
 body:=body||jsonb_build_object('action','update','project_id',v_project_id,'request_id',gen_random_uuid(),'expected_updated_at',stamp,'project',body->'project'||jsonb_build_object('notes','Changed'));
 r:=public.tj_runtime_speciq_projects(body);IF r->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'update failed %',r;END IF;
 r:=public.tj_runtime_speciq_projects(body||jsonb_build_object('request_id',gen_random_uuid()));IF r->>'error' IS DISTINCT FROM 'revision_conflict' THEN RAISE EXCEPTION 'stale update allowed %',r;END IF;
 r:=public.tj_runtime_speciq_projects(body||jsonb_build_object('request_id',gen_random_uuid(),'organization_id',foreign_org));IF r->>'error' IS DISTINCT FROM 'organization_access_required' THEN RAISE EXCEPTION 'foreign org allowed';END IF;
 PERFORM set_config('request.jwt.claim.sub',other_native::text,true);
 r:=public.tj_runtime_speciq_projects(body);IF r->>'error' IS DISTINCT FROM 'organization_write_required' THEN RAISE EXCEPTION 'viewer update allowed';END IF;
 UPDATE tj.organization_members SET role='member' WHERE organization_id=org AND user_id=other_actor;
 r:=public.tj_runtime_speciq_projects(body);IF r->>'error' IS DISTINCT FROM 'project_unavailable' THEN RAISE EXCEPTION 'other member update allowed';END IF;
 PERFORM set_config('request.jwt.claim.sub',native::text,true);
 INSERT INTO tj.speciq_projects(organization_id,created_by,project_name,customer_name) VALUES(org,actor,'Copied history','Fixture') RETURNING speciq_projects.id INTO historical;
 SELECT updated_at INTO stamp FROM tj.speciq_projects WHERE speciq_projects.id=historical;
 r:=public.tj_runtime_speciq_projects(jsonb_build_object('action','archive','organization_id',org,'request_id',gen_random_uuid(),'project_id',historical,'expected_updated_at',stamp));IF r->>'error' IS DISTINCT FROM 'historical_project_read_only' THEN RAISE EXCEPTION 'imported history changed';END IF;
 INSERT INTO tj.speciq_packages(organization_id,project_id,package_name,created_by,status) VALUES(org,v_project_id,'Retain fixture package',actor,'draft') RETURNING speciq_packages.id INTO pkg;
 SELECT updated_at INTO stamp FROM tj.speciq_projects WHERE speciq_projects.id=v_project_id;
 body:=body||jsonb_build_object('request_id',gen_random_uuid(),'expected_updated_at',stamp);
 r:=public.tj_runtime_speciq_projects(body);IF r->>'error' IS DISTINCT FROM 'package_revision_required' THEN RAISE EXCEPTION 'package live project edited %',r;END IF;
 body:=jsonb_build_object('action','archive','organization_id',org,'request_id',gen_random_uuid(),'project_id',v_project_id,'expected_updated_at',stamp);
 r:=public.tj_runtime_speciq_projects(body);IF r->>'error' IS DISTINCT FROM 'archive_packages_first' THEN RAISE EXCEPTION 'active package archive allowed %',r;END IF;
 UPDATE tj.speciq_packages SET status='archived' WHERE speciq_packages.id=pkg;
 r:=public.tj_runtime_speciq_projects(body);IF r->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'archive failed %',r;END IF;
 r:=public.tj_runtime_speciq_projects(body);IF r->>'replayed' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'archive replay failed';END IF;
 IF NOT EXISTS(SELECT 1 FROM tj.speciq_projects WHERE speciq_projects.id=v_project_id AND status='archived' AND deleted_at IS NULL AND notes='Changed') OR NOT EXISTS(SELECT 1 FROM tj.speciq_packages WHERE speciq_packages.id=pkg) OR (SELECT count(*) FROM tj_private.speciq_project_requests WHERE project_id=v_project_id)<>3 THEN RAISE EXCEPTION 'archive lost rows/audit history';END IF;
 UPDATE tj.organization_members SET status='suspended' WHERE organization_id=org AND user_id=actor;
 r:=public.tj_runtime_speciq_projects(body);IF r->>'error' IS DISTINCT FROM 'organization_access_required' THEN RAISE EXCEPTION 'suspended replay allowed';END IF;
 UPDATE tj.organization_members SET status='active' WHERE organization_id=org AND user_id=actor;
 IF has_function_privilege('anon','public.tj_runtime_speciq_projects(jsonb)','EXECUTE') OR has_table_privilege('authenticated','tj_private.speciq_project_requests','SELECT') THEN RAISE EXCEPTION 'private journal/anonymous exposure';END IF;
 PERFORM set_config('test.projects.native',native::text,true);PERFORM set_config('test.projects.org',org::text,true);
END $$;
SET LOCAL ROLE authenticated;
DO $$DECLARE r jsonb;BEGIN
 PERFORM set_config('request.jwt.claim.sub',current_setting('test.projects.native'),true);
 r:=public.tj_runtime_speciq_projects(jsonb_build_object('action','list','organization_id',current_setting('test.projects.org')));IF r->>'ok' IS DISTINCT FROM 'true' OR jsonb_array_length(r->'projects')<>2 THEN RAISE EXCEPTION 'authenticated wrapper failed %',r;END IF;
END $$;
ROLLBACK;
SELECT 'PASS: project create/edit/archive/replay, source actors and metadata, exact dates, stale/foreign/viewer/other owner/suspended denial, imported history read only, attached package freeze, archive retains package/project/audit, authenticated wrapper; fixtures rolled back' result;
