-- Bulk table read/access/write checks. All fixtures roll back.
BEGIN; SET LOCAL statement_timeout='45s';
DO $$ DECLARE u uuid; src uuid; org uuid; other uuid; chapter integer:=-(1000000000+floor(random()*1000000000))::integer; notification uuid:=gen_random_uuid(); hidden uuid:=gen_random_uuid(); BEGIN
 SELECT im.target_user_id,im.source_user_id,m.organization_id INTO u,src,org FROM tj.source_user_identity_map im JOIN tj.organization_members m ON m.user_id=im.source_user_id JOIN tj.organizations o ON o.id=m.organization_id AND o.deleted_at IS NULL AND o.status='active' WHERE im.activation_status='activated' AND m.status='active' AND m.role IN('owner','admin') AND NOT EXISTS(SELECT 1 FROM tj.platform_admins x WHERE x.user_id=im.source_user_id) LIMIT 1;
 SELECT o.id INTO other FROM tj.organizations o WHERE o.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM tj.organization_members m WHERE m.user_id=src AND m.organization_id=o.id AND m.status='active') LIMIT 1;
 IF u IS NULL OR other IS NULL THEN RAISE EXCEPTION 'Access fixtures unavailable'; END IF;
 PERFORM set_config('request.jwt.claim.sub',u::text,true); PERFORM set_config('test.user',u::text,true); PERFORM set_config('test.source',src::text,true); PERFORM set_config('test.org',org::text,true); PERFORM set_config('test.foreign',other::text,true); PERFORM set_config('test.chapter',chapter::text,true); PERFORM set_config('test.notification',notification::text,true); PERFORM set_config('test.hidden',hidden::text,true);
 INSERT INTO tj.academy_chapters(id,chapter_number,title,slug) VALUES(chapter,chapter,'Rollback fixture',chapter::text);
 INSERT INTO tj.academy_notifications(id,user_id,organization_id,type,title,read) VALUES(notification,src,org,'recommended','Rollback fixture',false),(hidden,src,other,'recommended','Hidden fixture',false);
END $$;
SET LOCAL ROLE authenticated;
DO $$ DECLARE t text; has_rows boolean; orgcol text; src uuid:=current_setting('test.source')::uuid; BEGIN
 IF NOT tj_private.has_active_mapped_org() OR NOT tj_private.is_source_self(src) THEN RAISE EXCEPTION 'Mapped identity not recognized'; END IF;
 IF NOT EXISTS(SELECT 1 FROM tj.academy_chapters WHERE id=current_setting('test.chapter')::int) THEN RAISE EXCEPTION 'Reference content missing'; END IF;
 IF NOT EXISTS(SELECT 1 FROM tj.academy_notifications WHERE id=current_setting('test.notification')::uuid) OR EXISTS(SELECT 1 FROM tj.academy_notifications WHERE id=current_setting('test.hidden')::uuid) THEN RAISE EXCEPTION 'Notification org scope'; END IF;
 INSERT INTO tj.academy_progress(user_id,chapter_id,completed_at) VALUES(src,current_setting('test.chapter')::int,now());
 INSERT INTO tj.academy_progress(user_id,chapter_id,completed_at) VALUES(src,current_setting('test.chapter')::int,now()) ON CONFLICT(user_id,chapter_id) DO UPDATE SET user_id=excluded.user_id,chapter_id=excluded.chapter_id,completed_at=excluded.completed_at;
 UPDATE tj.academy_notifications SET read=true WHERE id=current_setting('test.notification')::uuid;
 IF NOT EXISTS(SELECT 1 FROM tj.academy_notifications WHERE id=current_setting('test.notification')::uuid AND read) THEN RAISE EXCEPTION 'Read receipt failed'; END IF;
 BEGIN INSERT INTO tj.academy_progress(user_id,chapter_id,completed_at) VALUES(gen_random_uuid(),current_setting('test.chapter')::int,now()); RAISE EXCEPTION 'Foreign progress allowed'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 BEGIN UPDATE tj.academy_progress SET user_id=gen_random_uuid() WHERE user_id=src AND chapter_id=current_setting('test.chapter')::int; RAISE EXCEPTION 'Progress ownership change'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 BEGIN UPDATE tj.academy_notifications SET title='Forbidden edit' WHERE id=current_setting('test.notification')::uuid; RAISE EXCEPTION 'Notification content editable'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 BEGIN INSERT INTO tj.academy_brand_certifications(user_id,brand_id,tier) VALUES(src,gen_random_uuid(),'fake'); RAISE EXCEPTION 'Certification forgery'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 FOREACH t IN ARRAY ARRAY['academy_brand_certifications','academy_brand_progress','academy_chapters','academy_daily_metrics','academy_learning_events','academy_notifications','academy_progress','academy_quiz_scores','academy_quizzes','academy_volumes','ai_conversation_turns','aicrm_outreach_campaigns','aicrm_sequence_enrollments','aicrm_sequence_steps','aiq_recalls','aiq_service_providers','aiq_vendor_contacts','aiq_warranty_policies','brand_map_policies','buying_groups','communication_templates','competitive_cross_reference','crm_activity_goals','crm_analytics_events','crm_archive_log','crm_buying_group_members','crm_buying_groups','crm_coaching_queue','crm_commissions','crm_custom_fields','crm_daily_five','crm_deal_participants','crm_deals','crm_delivery_workflows','crm_emails','crm_replacement_cycles','crm_sla_events','crm_sla_rules','crm_stage_history','crm_tasks','crm_temperature_history','field_checklist_categories','field_checklist_items','intel_news','iq_badges','iq_cards','iq_courses','iq_decks','iq_lanes','iq_product_cards','iq_zones','mfr_members','mfr_user_roles','organization_brands','performance_competencies','performance_observations','performance_skill_state','pim_category_map','piq_retailer_brands','piq_retailer_profiles','platform_ai_credit_packs','platform_ai_credits','platform_plan_modules','platform_plans','platform_seat_tiers','platform_subscriptions','product_iq_brand_scopes','product_iq_governance_audit_log','product_iq_platform_roles','profiles','scraper_brand_sources','scraper_retailer_sources','service_iq_templates','speciq_package_events','speciq_package_versions','speciq_retailer_settings'] LOOP
  EXECUTE format('SELECT EXISTS(SELECT 1 FROM tj.%I)',t) INTO has_rows;
  SELECT CASE WHEN EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='tj' AND table_name=t AND column_name='organization_id') THEN 'organization_id' WHEN EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='tj' AND table_name=t AND column_name='org_id') THEN 'org_id' ELSE NULL END INTO orgcol;
  IF orgcol IS NOT NULL THEN EXECUTE format('SELECT EXISTS(SELECT 1 FROM tj.%I WHERE %I=$1)',t,orgcol) INTO has_rows USING current_setting('test.foreign')::uuid;
   IF has_rows THEN RAISE EXCEPTION 'Cross-org read: %',t; END IF;
  END IF;
 END LOOP;
 PERFORM set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
 FOREACH t IN ARRAY ARRAY['academy_brand_certifications','academy_brand_progress','academy_chapters','academy_daily_metrics','academy_learning_events','academy_notifications','academy_progress','academy_quiz_scores','academy_quizzes','academy_volumes','ai_conversation_turns','aicrm_outreach_campaigns','aicrm_sequence_enrollments','aicrm_sequence_steps','aiq_recalls','aiq_service_providers','aiq_vendor_contacts','aiq_warranty_policies','brand_map_policies','buying_groups','communication_templates','competitive_cross_reference','crm_activity_goals','crm_analytics_events','crm_archive_log','crm_buying_group_members','crm_buying_groups','crm_coaching_queue','crm_commissions','crm_custom_fields','crm_daily_five','crm_deal_participants','crm_deals','crm_delivery_workflows','crm_emails','crm_replacement_cycles','crm_sla_events','crm_sla_rules','crm_stage_history','crm_tasks','crm_temperature_history','field_checklist_categories','field_checklist_items','intel_news','iq_badges','iq_cards','iq_courses','iq_decks','iq_lanes','iq_product_cards','iq_zones','mfr_members','mfr_user_roles','organization_brands','performance_competencies','performance_observations','performance_skill_state','pim_category_map','piq_retailer_brands','piq_retailer_profiles','platform_ai_credit_packs','platform_ai_credits','platform_plan_modules','platform_plans','platform_seat_tiers','platform_subscriptions','product_iq_brand_scopes','product_iq_governance_audit_log','product_iq_platform_roles','profiles','scraper_brand_sources','scraper_retailer_sources','service_iq_templates','speciq_package_events','speciq_package_versions','speciq_retailer_settings'] LOOP
  EXECUTE format('SELECT EXISTS(SELECT 1 FROM tj.%I)',t) INTO has_rows;
  IF has_rows THEN RAISE EXCEPTION 'Unmapped read: %',t; END IF;
 END LOOP;
END $$;
RESET ROLE;
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['academy_brand_certifications','academy_brand_progress','academy_chapters','academy_daily_metrics','academy_learning_events','academy_notifications','academy_progress','academy_quiz_scores','academy_quizzes','academy_volumes','ai_conversation_turns','aicrm_outreach_campaigns','aicrm_sequence_enrollments','aicrm_sequence_steps','aiq_recalls','aiq_service_providers','aiq_vendor_contacts','aiq_warranty_policies','brand_map_policies','buying_groups','communication_templates','competitive_cross_reference','crm_activity_goals','crm_analytics_events','crm_archive_log','crm_buying_group_members','crm_buying_groups','crm_coaching_queue','crm_commissions','crm_custom_fields','crm_daily_five','crm_deal_participants','crm_deals','crm_delivery_workflows','crm_emails','crm_replacement_cycles','crm_sla_events','crm_sla_rules','crm_stage_history','crm_tasks','crm_temperature_history','field_checklist_categories','field_checklist_items','intel_news','iq_badges','iq_cards','iq_courses','iq_decks','iq_lanes','iq_product_cards','iq_zones','mfr_members','mfr_user_roles','organization_brands','performance_competencies','performance_observations','performance_skill_state','pim_category_map','piq_retailer_brands','piq_retailer_profiles','platform_ai_credit_packs','platform_ai_credits','platform_plan_modules','platform_plans','platform_seat_tiers','platform_subscriptions','product_iq_brand_scopes','product_iq_governance_audit_log','product_iq_platform_roles','profiles','scraper_brand_sources','scraper_retailer_sources','service_iq_templates','speciq_package_events','speciq_package_versions','speciq_retailer_settings'] LOOP
  IF has_table_privilege('anon',format('tj.%I',t),'SELECT') OR (t<>'crm_buying_group_members' AND has_table_privilege('authenticated',format('tj.%I',t),'DELETE')) THEN RAISE EXCEPTION 'Unexpected privilege: %',t; END IF;
 END LOOP;
 IF (SELECT count(*) FROM tj.academy_progress WHERE user_id=current_setting('test.source')::uuid AND chapter_id=current_setting('test.chapter')::int)<>1 THEN RAISE EXCEPTION 'Progress upsert duplicate'; END IF;
 IF (SELECT read FROM tj.academy_notifications WHERE id=current_setting('test.hidden')::uuid) THEN RAISE EXCEPTION 'Hidden receipt changed'; END IF;
 RAISE NOTICE '76 table reads and two limited write workflows passed; fixtures roll back';
END $$;
ROLLBACK;
