BEGIN;
SET LOCAL statement_timeout='25s';
DO $$
DECLARE actor uuid; native uuid; other_actor uuid; other_native uuid; org uuid; foreign_org uuid; warranty uuid;
 body jsonb; result jsonb; pkg uuid; new_pkg uuid; before_count bigint; contact uuid; second_contact uuid; foreign_contact uuid; deal uuid; other_deal uuid; foreign_deal uuid; mismatch_deal uuid; request jsonb; v integer; stamp timestamptz;
BEGIN
 SELECT im.source_user_id,im.target_user_id INTO actor,native FROM tj.source_user_identity_map im JOIN auth.users u ON u.id=im.target_user_id WHERE tj_private.microsoft_actor(u.id)=im.source_user_id AND u.email_confirmed_at IS NOT NULL AND NOT EXISTS(SELECT 1 FROM tj.platform_admins p WHERE p.user_id=im.source_user_id) LIMIT 1;
 SELECT im.source_user_id,im.target_user_id INTO other_actor,other_native FROM tj.source_user_identity_map im JOIN auth.users u ON u.id=im.target_user_id WHERE tj_private.microsoft_actor(u.id)=im.source_user_id AND u.email_confirmed_at IS NOT NULL AND im.source_user_id<>actor LIMIT 1;
 IF native IS NULL OR other_native IS NULL THEN RAISE EXCEPTION 'missing mapped fixture identities'; END IF;
 INSERT INTO tj.organizations(name,slug) VALUES('Spec draft rollback fixture','spec-draft-rollback-'||gen_random_uuid()) RETURNING id INTO org;
 INSERT INTO tj.organizations(name,slug) VALUES('Spec foreign rollback fixture','spec-draft-rollback-'||gen_random_uuid()) RETURNING id INTO foreign_org;
 INSERT INTO tj.organization_members(organization_id,user_id,role,status) VALUES(org,actor,'member','active'),(org,other_actor,'viewer','active');
 INSERT INTO tj.speciq_warranty_catalog(organization_id,warranty_name,warranty_type,selling_price,active,is_included,applies_to_categories) VALUES(org,'Fixture coverage','extended',12.34,true,false,ARRAY['refrigerator']) RETURNING id INTO warranty;
 PERFORM set_config('request.jwt.claim.sub',native::text,true);
 result:=public.tj_runtime_speciq_drafts('{"action":"context"}');
 IF result->>'ok' IS DISTINCT FROM 'true' OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements(result->'organizations') o WHERE o->>'id'=org::text AND o->>'role'='member') OR EXISTS(SELECT 1 FROM jsonb_array_elements(result->'organizations') o WHERE o->>'id'=foreign_org::text) THEN RAISE EXCEPTION 'context isolation failed: %',result; END IF;
 body:=jsonb_build_object('action','save','organization_id',org,'request_id',gen_random_uuid(),'customer',jsonb_build_object('name','Fixture customer','project_name','Fixture project'),'package_name','Fixture draft','include_pricing',true,'products',jsonb_build_array(jsonb_build_object('product_name','Fixture refrigerator','brand','Fixture brand','category','refrigerator','msrp','10.01','quantity',2,'warranty_id',warranty)),'services',jsonb_build_array(jsonb_build_object('service_type','delivery','description','Fixture delivery','amount','5.10','taxable',true)));

 UPDATE tj.organization_members SET visibility_scope='own' WHERE organization_id=org AND user_id=actor;
 INSERT INTO tj.contacts(organization_id,first_name,last_name,email,phone) VALUES(org,'Canonical','Customer','canonical@example.test','5550100') RETURNING id INTO contact;
 INSERT INTO tj.contacts(organization_id,first_name) VALUES(org,'Second') RETURNING id INTO second_contact;
 INSERT INTO tj.contacts(organization_id,first_name) VALUES(foreign_org,'Foreign') RETURNING id INTO foreign_contact;
 INSERT INTO tj.crm_deals(organization_id,contact_id,owner_user_id,title,value_amount) VALUES(org,contact,actor,'Own deal',123.45) RETURNING id INTO deal;
 INSERT INTO tj.crm_deals(organization_id,contact_id,owner_user_id,title) VALUES(org,contact,other_actor,'Other owner deal') RETURNING id INTO other_deal;
 INSERT INTO tj.crm_deals(organization_id,contact_id,owner_user_id,title) VALUES(org,second_contact,actor,'Wrong contact deal') RETURNING id INTO mismatch_deal;
 INSERT INTO tj.crm_deals(organization_id,contact_id,owner_user_id,title) VALUES(foreign_org,foreign_contact,other_actor,'Foreign deal') RETURNING id INTO foreign_deal;
 result:=public.tj_runtime_speciq_crm_links(jsonb_build_object('action','search','organization_id',org,'query','Canonical'));
 IF result->>'ok' IS DISTINCT FROM 'true' OR jsonb_array_length(result->'contacts')<>1 OR result#>>'{contacts,0,id}'<>contact::text THEN RAISE EXCEPTION 'contact search failed: %',result;END IF;
 result:=public.tj_runtime_speciq_crm_links(jsonb_build_object('action','search','organization_id',org,'query','%,()'));
 IF result->>'ok' IS DISTINCT FROM 'true' OR jsonb_array_length(result->'contacts')<>0 THEN RAISE EXCEPTION 'query punctuation altered filters';END IF;
 result:=public.tj_runtime_speciq_crm_links(jsonb_build_object('action','select','organization_id',org,'contact_id',contact));
 IF result->>'ok' IS DISTINCT FROM 'true' OR jsonb_array_length(result->'deals')<>1 OR result#>>'{deals,0,id}'<>deal::text THEN RAISE EXCEPTION 'scoped deal picker failed: %',result;END IF;
 request:=body||jsonb_build_object('contact_id',contact,'deal_id',deal,'salesperson_name','Draft salesperson');
 result:=public.tj_runtime_speciq_drafts(request);IF result->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'linked save failed: %',result;END IF;pkg:=(result->>'package_id')::uuid;
 IF NOT EXISTS(SELECT 1 FROM tj.speciq_packages k JOIN tj.speciq_projects p ON p.id=k.project_id WHERE k.id=pkg AND k.contact_id=contact AND k.deal_id=deal AND k.salesperson_name='Draft salesperson' AND p.contact_id=contact AND p.deal_id=deal AND p.customer_name='Canonical Customer' AND p.customer_email='canonical@example.test' AND p.customer_phone='5550100' AND k.created_by=actor) THEN RAISE EXCEPTION 'canonical link/project/salesperson/source actor mismatch';END IF;
 IF NOT EXISTS(SELECT 1 FROM tj.speciq_package_versions WHERE package_id=pkg AND snapshot#>>'{package,contact_id}'=contact::text AND snapshot#>>'{project,deal_id}'=deal::text) THEN RAISE EXCEPTION 'link snapshot incomplete';END IF;
 IF NOT EXISTS(SELECT 1 FROM tj.crm_deals WHERE id=deal AND value_amount=123.45 AND stage='Lead' AND quote_sent_at IS NULL) THEN RAISE EXCEPTION 'CRM financial stage changed';END IF;
 result:=public.tj_runtime_speciq_drafts(request);IF result->>'replayed' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'linked retry duplicated';END IF;
 SELECT count(*) INTO before_count FROM tj.speciq_packages WHERE organization_id=org;
 result:=public.tj_runtime_speciq_drafts(request||jsonb_build_object('request_id',gen_random_uuid(),'deal_id',other_deal));IF result->>'error' IS DISTINCT FROM 'crm_link_unavailable' THEN RAISE EXCEPTION 'out of salesperson scope deal accepted';END IF;
 result:=public.tj_runtime_speciq_drafts(request||jsonb_build_object('request_id',gen_random_uuid(),'deal_id',mismatch_deal));IF result->>'error' IS DISTINCT FROM 'crm_link_unavailable' THEN RAISE EXCEPTION 'mismatched contact/deal accepted';END IF;
 result:=public.tj_runtime_speciq_drafts(request||jsonb_build_object('request_id',gen_random_uuid(),'contact_id',foreign_contact,'deal_id',foreign_deal));IF result->>'error' IS DISTINCT FROM 'crm_link_unavailable' THEN RAISE EXCEPTION 'foreign CRM link accepted';END IF;
 result:=public.tj_runtime_speciq_drafts(request||jsonb_build_object('request_id',gen_random_uuid(),'contact_id',NULL));IF result->>'error' IS DISTINCT FROM 'crm_link_unavailable' THEN RAISE EXCEPTION 'deal without contact accepted';END IF;
 UPDATE tj.crm_deals SET closed_at=now() WHERE id=deal;
 result:=public.tj_runtime_speciq_drafts(request);IF result->>'error' IS DISTINCT FROM 'crm_link_unavailable' THEN RAISE EXCEPTION 'closed deal retry allowed';END IF;
 UPDATE tj.crm_deals SET closed_at=NULL,is_archived=true WHERE id=deal;
 result:=public.tj_runtime_speciq_drafts(request||jsonb_build_object('request_id',gen_random_uuid()));IF result->>'error' IS DISTINCT FROM 'crm_link_unavailable' THEN RAISE EXCEPTION 'archived deal accepted';END IF;
 UPDATE tj.crm_deals SET is_archived=false WHERE id=deal;
 UPDATE tj.contacts SET deleted_at=now() WHERE id=contact;
 result:=public.tj_runtime_speciq_drafts(request);IF result->>'error' IS DISTINCT FROM 'crm_link_unavailable' THEN RAISE EXCEPTION 'deleted contact retry allowed';END IF;
 UPDATE tj.contacts SET deleted_at=NULL WHERE id=contact;
 IF (SELECT count(*) FROM tj.speciq_packages WHERE organization_id=org)<>before_count THEN RAISE EXCEPTION 'invalid link left package rows';END IF;
 SELECT version,updated_at INTO v,stamp FROM tj.speciq_packages WHERE id=pkg;
 result:=public.tj_runtime_speciq_drafts(body||jsonb_build_object('request_id',gen_random_uuid(),'previous_package_id',pkg,'expected_version',v,'expected_updated_at',stamp));IF result->>'error' IS DISTINCT FROM 'crm_link_unavailable' THEN RAISE EXCEPTION 'old client silently dropped link';END IF;
 result:=public.tj_runtime_speciq_drafts(request||jsonb_build_object('request_id',gen_random_uuid(),'previous_package_id',pkg,'expected_version',v,'expected_updated_at',stamp));IF result->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'linked revision failed: %',result;END IF;new_pkg:=(result->>'package_id')::uuid;
 IF NOT EXISTS(SELECT 1 FROM tj.speciq_packages WHERE id=pkg AND contact_id=contact AND deal_id=deal AND superseded_by=new_pkg) OR NOT EXISTS(SELECT 1 FROM tj.speciq_packages WHERE id=new_pkg AND contact_id=contact AND deal_id=deal) THEN RAISE EXCEPTION 'revised links/history lost';END IF;
 SELECT version,updated_at INTO v,stamp FROM tj.speciq_packages WHERE id=new_pkg;
 result:=public.tj_runtime_speciq_drafts(request||jsonb_build_object('request_id',gen_random_uuid(),'previous_package_id',new_pkg,'expected_version',v,'expected_updated_at',stamp,'contact_id',NULL,'deal_id',NULL));IF result->>'ok' IS DISTINCT FROM 'true' OR NOT EXISTS(SELECT 1 FROM tj.speciq_packages WHERE id=(result->>'package_id')::uuid AND contact_id IS NULL AND deal_id IS NULL) THEN RAISE EXCEPTION 'explicit clearing failed';END IF;
 UPDATE tj.organization_members SET status='suspended' WHERE organization_id=org AND user_id=actor;
 result:=public.tj_runtime_speciq_crm_links(jsonb_build_object('action','search','organization_id',org,'query','Canonical'));IF result->>'error' IS DISTINCT FROM 'organization_write_required' THEN RAISE EXCEPTION 'suspended contact search allowed';END IF;
 UPDATE tj.organization_members SET status='active' WHERE organization_id=org AND user_id=actor;
 PERFORM set_config('test.links.native',native::text,true);PERFORM set_config('test.links.org',org::text,true);PERFORM set_config('test.links.contact',contact::text,true);
 IF has_function_privilege('anon','public.tj_runtime_speciq_crm_links(jsonb)','EXECUTE') THEN RAISE EXCEPTION 'anonymous contact access';END IF;
END $$;
SET LOCAL ROLE authenticated;
DO $$DECLARE result jsonb;BEGIN
 PERFORM set_config('request.jwt.claim.sub',current_setting('test.links.native'),true);
 result:=public.tj_runtime_speciq_crm_links(jsonb_build_object('action','select','organization_id',current_setting('test.links.org'),'contact_id',current_setting('test.links.contact')));IF result->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'authenticated picker wrapper failed';END IF;
END $$;
ROLLBACK;
SELECT 'PASS: native CRM contact/deal picker and canonical linked atomic draft/revise/clear; source identity/salesperson/customer/contact/deal snapshots preserved; own scope and mismatch/foreign/closed/archive/deleted/suspended/replay denial; actual authenticated wrapper; CRM stage/value/send unchanged; fixtures rolled back' result;
