BEGIN;
SET LOCAL statement_timeout='25s';
DO $$
DECLARE actor uuid; native uuid; other_actor uuid; other_native uuid; org uuid; foreign_org uuid; warranty uuid;
 body jsonb; result jsonb; pkg uuid; new_pkg uuid; before_count bigint; v integer; stamp timestamptz;
BEGIN
 SELECT im.source_user_id,im.target_user_id INTO actor,native FROM tj.source_user_identity_map im JOIN auth.users u ON u.id=im.target_user_id WHERE tj_private.microsoft_actor(u.id)=im.source_user_id AND u.email_confirmed_at IS NOT NULL LIMIT 1;
 SELECT im.source_user_id,im.target_user_id INTO other_actor,other_native FROM tj.source_user_identity_map im JOIN auth.users u ON u.id=im.target_user_id WHERE tj_private.microsoft_actor(u.id)=im.source_user_id AND u.email_confirmed_at IS NOT NULL AND im.source_user_id<>actor LIMIT 1;
 IF native IS NULL OR other_native IS NULL THEN RAISE EXCEPTION 'missing mapped fixture identities'; END IF;
 INSERT INTO tj.organizations(name,slug) VALUES('Spec draft rollback fixture','spec-draft-rollback-'||gen_random_uuid()) RETURNING id INTO org;
 INSERT INTO tj.organizations(name,slug) VALUES('Spec foreign rollback fixture','spec-draft-rollback-'||gen_random_uuid()) RETURNING id INTO foreign_org;
 INSERT INTO tj.organization_members(organization_id,user_id,role,status) VALUES(org,actor,'member','active'),(org,other_actor,'viewer','active');
 INSERT INTO tj.speciq_warranty_catalog(organization_id,warranty_name,warranty_type,selling_price,active,is_included,applies_to_categories) VALUES(org,'Fixture coverage','extended',12.34,true,false,ARRAY['refrigerator']) RETURNING id INTO warranty;
 PERFORM set_config('request.jwt.claim.sub',native::text,true);
 result:=public.tj_runtime_speciq_drafts('{"action":"context"}');
 IF result->>'ok' IS DISTINCT FROM 'true' OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements(result->'organizations') o WHERE o->>'id'=org::text AND o->>'role'='member') OR EXISTS(SELECT 1 FROM jsonb_array_elements(result->'organizations') o WHERE o->>'id'=foreign_org::text) THEN RAISE EXCEPTION 'context isolation failed: %',result; END IF;
 body:=jsonb_build_object('action','save','organization_id',org,'request_id',gen_random_uuid(),'customer',jsonb_build_object('name','Fixture customer','project_name','Fixture project'),'package_name','Fixture draft','include_pricing',true,'products',jsonb_build_array(jsonb_build_object('product_name','Fixture refrigerator','brand','Fixture brand','category','refrigerator','msrp','10.01','quantity',2,'warranty_id',warranty)),'services',jsonb_build_array(jsonb_build_object('service_type','delivery','description','Fixture delivery','amount','5.10','taxable',true)));
 result:=public.tj_runtime_speciq_drafts(body);
 IF result->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'save failed: %',result; END IF; pkg:=(result->>'package_id')::uuid;
 IF NOT EXISTS(SELECT 1 FROM tj.speciq_packages WHERE id=pkg AND created_by=actor AND updated_by=actor AND organization_id=org AND status='draft' AND total_msrp=20.02 AND total_services=5.10 AND warranty_total=24.68 AND total_tax IS NULL AND total_final IS NULL AND share_token IS NULL AND sent_at IS NULL) THEN RAISE EXCEPTION 'draft provenance/totals failed'; END IF;
 IF NOT EXISTS(SELECT 1 FROM tj.speciq_package_versions WHERE package_id=pkg AND jsonb_array_length(snapshot->'products')=1 AND jsonb_array_length(snapshot->'warranties')=1 AND jsonb_array_length(snapshot->'services')=1 AND created_by=actor) THEN RAISE EXCEPTION 'complete snapshot failed'; END IF;
 result:=public.tj_runtime_speciq_drafts(body);IF result->>'ok' IS DISTINCT FROM 'true' OR result->>'package_id'<>pkg::text OR result->>'replayed'<>'true' THEN RAISE EXCEPTION 'retry created a duplicate'; END IF;
 result:=public.tj_runtime_speciq_drafts(body||'{"package_name":"Changed retry"}');IF result->>'error' IS DISTINCT FROM 'request_conflict' THEN RAISE EXCEPTION 'changed retry accepted'; END IF;
 SELECT count(*) INTO before_count FROM tj.speciq_packages WHERE organization_id=org;
 result:=public.tj_runtime_speciq_drafts(body||jsonb_build_object('request_id',gen_random_uuid(),'services',jsonb_build_array(jsonb_build_object('service_type','other','amount','-1','taxable',true))));
 IF result->>'error' IS DISTINCT FROM 'invalid_request' OR (SELECT count(*) FROM tj.speciq_packages WHERE organization_id=org)<>before_count OR (SELECT count(*) FROM tj.speciq_projects WHERE organization_id=org)<>1 THEN RAISE EXCEPTION 'failed child write was not rolled back'; END IF;
 result:=public.tj_runtime_speciq_drafts(body||jsonb_build_object('request_id',gen_random_uuid(),'organization_id',foreign_org));IF result->>'error' IS DISTINCT FROM 'organization_write_required' THEN RAISE EXCEPTION 'foreign organization write'; END IF;
 result:=public.tj_runtime_speciq_drafts(body||jsonb_build_object('request_id',gen_random_uuid(),'created_by',other_actor));IF result->>'error' IS DISTINCT FROM 'invalid_request' THEN RAISE EXCEPTION 'spoofed actor accepted'; END IF;
 result:=public.tj_runtime_speciq_drafts(body||jsonb_build_object('request_id',gen_random_uuid(),'products',jsonb_build_array(jsonb_build_object('product_name','Spoof','aiq_product_id',gen_random_uuid(),'msrp','10','quantity',1))));IF result->>'error' IS DISTINCT FROM 'invalid_request' THEN RAISE EXCEPTION 'foreign catalog product accepted'; END IF;
 PERFORM set_config('request.jwt.claim.sub',other_native::text,true);
 result:=public.tj_runtime_speciq_drafts(body||jsonb_build_object('request_id',gen_random_uuid()));IF result->>'error' IS DISTINCT FROM 'organization_write_required' THEN RAISE EXCEPTION 'viewer wrote'; END IF;
 UPDATE tj.organization_members SET role='member' WHERE organization_id=org AND user_id=other_actor;
 SELECT version,updated_at INTO v,stamp FROM tj.speciq_packages WHERE id=pkg;
 result:=public.tj_runtime_speciq_drafts(body||jsonb_build_object('request_id',gen_random_uuid(),'previous_package_id',pkg,'expected_version',v,'expected_updated_at',stamp));IF result->>'error' IS DISTINCT FROM 'package_unavailable' THEN RAISE EXCEPTION 'member edited another owner'; END IF;
 PERFORM set_config('request.jwt.claim.sub',native::text,true);
 result:=public.tj_runtime_speciq_drafts(body||jsonb_build_object('request_id',gen_random_uuid(),'previous_package_id',pkg,'expected_version',v+1,'expected_updated_at',stamp));IF result->>'error' IS DISTINCT FROM 'revision_conflict' THEN RAISE EXCEPTION 'stale revision accepted'; END IF;
 result:=public.tj_runtime_speciq_drafts(body||jsonb_build_object('request_id',gen_random_uuid(),'previous_package_id',pkg,'expected_version',v,'expected_updated_at',stamp));IF result->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'revision failed: %',result; END IF;new_pkg:=(result->>'package_id')::uuid;
 IF NOT EXISTS(SELECT 1 FROM tj.speciq_packages WHERE id=pkg AND status='archived' AND superseded_by=new_pkg) OR NOT EXISTS(SELECT 1 FROM tj.speciq_packages WHERE id=new_pkg AND supersedes=pkg AND version=2 AND status='draft') OR NOT EXISTS(SELECT 1 FROM tj.speciq_package_products WHERE package_id=pkg) OR NOT EXISTS(SELECT 1 FROM tj.speciq_product_warranties WHERE package_id=pkg) THEN RAISE EXCEPTION 'prior revision removed'; END IF;
 UPDATE tj.organization_members SET status='suspended' WHERE organization_id=org AND user_id=actor;
 result:=public.tj_runtime_speciq_drafts(body);IF result->>'error' IS DISTINCT FROM 'organization_write_required' THEN RAISE EXCEPTION 'suspended retry allowed'; END IF;
 UPDATE tj.organization_members SET status='active' WHERE organization_id=org AND user_id=actor;
 PERFORM set_config('test.spec.native',native::text,true);PERFORM set_config('test.spec.body',(body||jsonb_build_object('request_id',gen_random_uuid()))::text,true);
 IF has_function_privilege('anon','public.tj_runtime_speciq_drafts(jsonb)','EXECUTE') OR has_table_privilege('authenticated','tj.speciq_packages','INSERT') OR has_table_privilege('authenticated','tj_private.speciq_draft_requests','SELECT') THEN RAISE EXCEPTION 'private grants wrong'; END IF;
END $$;
SET LOCAL ROLE authenticated;
DO $$DECLARE result jsonb;BEGIN
 PERFORM set_config('request.jwt.claim.sub',current_setting('test.spec.native'),true);
 result:=public.tj_runtime_speciq_drafts(current_setting('test.spec.body')::jsonb);IF result->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'authenticated wrapper failed: %',result; END IF;
 PERFORM set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
 result:=public.tj_runtime_speciq_drafts('{"action":"context"}');IF result->>'error' IS DISTINCT FROM 'identity_review_required' THEN RAISE EXCEPTION 'unmapped user accepted'; END IF;
END $$;
ROLLBACK;
SELECT 'PASS: atomic native draft writes, exact quantity/warranty subtotals, source actor, complete version snapshot, retry/conflict, child failure rollback, foreign catalog/org/viewer/other-owner/stale/suspended/unmapped denial, preserved prior revisions, actual authenticated wrapper and closed direct writes; fixtures rolled back' AS result;
