BEGIN;SET LOCAL ROLE authenticated;
SELECT "brand_name" FROM tj."brand_catalog" WHERE false;
SELECT "category","full_coverage_years","full_coverage_notes","component_warranties","certified_install_bonus_notes","key_exclusions","last_verified_date" FROM tj."aiq_warranty_policies" WHERE false;
SELECT "chapter_number","title","intro" FROM tj."academy_chapters" WHERE false;
SELECT "chunk_key","title","content","organization_id" FROM tj."ai_knowledge_chunks" WHERE false;
SELECT "code","name" FROM tj."performance_competencies" WHERE false;
SELECT "country","customer_service_phone","customer_service_phone_label","customer_service_hours","service_repair_phone","warranty_phone","trade_distributor_phone","support_email","service_portal_url","owner_account_portal_url","confidence_level","notes" FROM tj."aiq_vendor_contacts" WHERE false;
SELECT "id" FROM tj."organization_members" WHERE false;
SELECT "id","code","name" FROM tj."performance_competencies" WHERE false;
SELECT "id","code","title","difficulty","competency_weights" FROM tj."performance_scenarios" WHERE false;
SELECT "id","code","title","difficulty","persona","context","objectives","competency_weights","customer_profile","hidden_facts","objections","success_criteria","opening_line" FROM tj."performance_scenarios" WHERE false;
SELECT "id","kpi_scores","organization_id","transcript","scenario_type","status","feedback","session_score" FROM tj."ai_roleplay_sessions" WHERE false;
SELECT "id","organization_id","user_id","scenario_type","status","mode","difficulty_level","transcript","scoring_breakdown" FROM tj."ai_roleplay_sessions" WHERE false;
SELECT "kpi_name" FROM tj."org_kpis" WHERE false;
SELECT "persona_name","handoff_triggers","handoff_style","handoff_template","debate_approach","defer_pattern","max_response_length" FROM tj."persona_communication_protocol" WHERE false;
SELECT "persona_name","persona_role","avatar_emoji","tone","specialization","prompt_prefix" FROM tj."ai_personas" WHERE false;
SELECT "rolling_score","confidence","last_observed_at","competency_id" FROM tj."performance_skill_state" WHERE false;
SELECT "rolling_score","confidence","sample_size","trend","competency_id" FROM tj."performance_skill_state" WHERE false;
SELECT "scenario_id" FROM tj."performance_roleplay_links" WHERE false;
SELECT "session_score","scoring_breakdown","feedback","coach_summary" FROM tj."ai_roleplay_sessions" WHERE false;
SELECT "title","hazard","recall_date","units_affected","injury_count","remedy","url","model_numbers" FROM tj."aiq_recalls" WHERE false;
SELECT * FROM tj."ai_roleplay_sessions" WHERE false;
ROLLBACK;
