BEGIN;SET LOCAL statement_timeout='45s';
DO $$ DECLARE u uuid;src uuid;org uuid;other uuid;foreign_org uuid;fd uuid:=gen_random_uuid(); BEGIN
 SELECT im.target_user_id,im.source_user_id,m.organization_id INTO u,src,org FROM tj.source_user_identity_map im JOIN tj.organization_members m ON m.user_id=im.source_user_id JOIN tj.profiles p ON p.user_id=im.source_user_id JOIN tj.organizations o ON o.id=m.organization_id WHERE im.activation_status='activated' AND m.status='active' AND m.role IN('owner','admin') AND o.status='active' AND o.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM tj.platform_admins x WHERE x.user_id=im.source_user_id) LIMIT 1;
 SELECT id INTO other FROM tj.source_auth_users WHERE id<>src LIMIT 1;
 SELECT id INTO foreign_org FROM tj.organizations o WHERE o.status='active' AND o.deleted_at IS NULL AND NOT EXISTS(SELECT 1 FROM tj.organization_members m WHERE m.organization_id=o.id AND m.user_id=src AND m.status='active') LIMIT 1;
 IF u IS NULL OR other IS NULL OR foreign_org IS NULL THEN RAISE EXCEPTION 'Write fixture unavailable'; END IF;
 PERFORM set_config('request.jwt.claim.sub',u::text,true);PERFORM set_config('test.source',src::text,true);PERFORM set_config('test.org',org::text,true);PERFORM set_config('test.other',other::text,true);PERFORM set_config('test.foreign',foreign_org::text,true);PERFORM set_config('test.foreign_deal',fd::text,true);
 INSERT INTO tj.organization_members(organization_id,user_id,role,status,visibility_scope) VALUES(org,other,'member','active','own') ON CONFLICT(organization_id,user_id) DO NOTHING;
 UPDATE tj.organization_members SET role='member',visibility_scope='own' WHERE organization_id=org AND user_id=src;
 INSERT INTO tj.crm_deals(id,organization_id,owner_user_id,title) VALUES(fd,foreign_org,other,'Foreign rollback fixture');
END $$;
SET LOCAL ROLE authenticated;
DO $$ DECLARE d uuid;t uuid;r uuid;count_rows int;src uuid:=current_setting('test.source')::uuid;org uuid:=current_setting('test.org')::uuid;BEGIN
 INSERT INTO tj.crm_deals(organization_id,owner_user_id,title,value_amount,margin_pct,margin_amount) VALUES(org,src,'Rollback fixture',1000,20,999) RETURNING id INTO d;
 PERFORM set_config('test.deal',d::text,true);
 UPDATE tj.crm_deals SET organization_id=org,stage='Proposal',temperature='hot',temperature_reason='Rollback fixture' WHERE id=d;
 IF NOT EXISTS(SELECT 1 FROM tj.crm_deals WHERE id=d AND margin_amount=200 AND stage='Proposal') THEN RAISE EXCEPTION 'Deal save or computed margin failed'; END IF;
 INSERT INTO tj.crm_tasks(organization_id,deal_id,assignee_user_id,title) VALUES(org,d,src,'Rollback task') RETURNING id INTO t;
 UPDATE tj.crm_tasks SET completed_at=now(),resolution_note='Completed fixture' WHERE id=t;
 IF NOT EXISTS(SELECT 1 FROM tj.crm_tasks WHERE id=t AND completed_at IS NOT NULL) THEN RAISE EXCEPTION 'Task completion failed';END IF;
 INSERT INTO tj.crm_activity_goals(organization_id,user_id,period,calls_target) VALUES(org,src,'weekly',3) ON CONFLICT(organization_id,user_id,period) DO UPDATE SET calls_target=excluded.calls_target;
 INSERT INTO tj.crm_activity_goals(organization_id,user_id,period,calls_target) VALUES(org,src,'weekly',4) ON CONFLICT(organization_id,user_id,period) DO UPDATE SET calls_target=excluded.calls_target;
 IF NOT EXISTS(SELECT 1 FROM tj.crm_activity_goals WHERE organization_id=org AND user_id=src AND period='weekly' AND calls_target=4) THEN RAISE EXCEPTION 'Goal upsert failed';END IF;
 INSERT INTO tj.crm_postmortems(organization_id,deal_id,salesperson_id,review_type,salesperson_reflection,is_private) VALUES(org,d,src,'won','Rollback reflection',true) RETURNING id INTO r;
 UPDATE tj.crm_postmortems SET what_went_well='Rollback fixture' WHERE id=r;
 IF NOT EXISTS(SELECT 1 FROM tj.crm_postmortems WHERE id=r AND what_went_well='Rollback fixture') THEN RAISE EXCEPTION 'Reflection save failed';END IF;
 UPDATE tj.crm_deals SET is_archived=true,archived_at=now(),archive_reason='Rollback fixture' WHERE id=d;
 UPDATE tj.crm_deals SET is_archived=false,archived_at=NULL WHERE id=d;
 BEGIN UPDATE tj.crm_deals SET organization_id=current_setting('test.foreign')::uuid WHERE id=d;RAISE EXCEPTION 'Tenant move permitted';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 BEGIN UPDATE tj.crm_deals SET owner_user_id=current_setting('test.other')::uuid WHERE id=d;RAISE EXCEPTION 'Rep reassignment permitted';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 BEGIN INSERT INTO tj.crm_tasks(organization_id,assignee_user_id,title,deal_id) VALUES(org,src,'Forbidden parent',current_setting('test.foreign_deal')::uuid);RAISE EXCEPTION 'Cross-org task parent permitted';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 BEGIN INSERT INTO tj.crm_deals(organization_id,owner_user_id,title) VALUES(current_setting('test.foreign')::uuid,src,'Forbidden organization');RAISE EXCEPTION 'Cross-org deal permitted';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 BEGIN UPDATE tj.crm_tasks SET ai_priority_score=100 WHERE id=t;RAISE EXCEPTION 'AI score forged';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 BEGIN UPDATE tj.crm_postmortems SET ai_summary='Forged score' WHERE id=r;RAISE EXCEPTION 'AI reflection forged';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 BEGIN UPDATE tj.crm_deals SET value_amount='NaN'::numeric WHERE id=d;RAISE EXCEPTION 'NaN permitted';EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'Invalid deal amount or margin' THEN RAISE;END IF;END;
 BEGIN DELETE FROM tj.crm_deals WHERE id=d;RAISE EXCEPTION 'Hard delete permitted';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 UPDATE tj.crm_deals SET title='Forbidden' WHERE id=current_setting('test.foreign_deal')::uuid;GET DIAGNOSTICS count_rows=ROW_COUNT;IF count_rows<>0 THEN RAISE EXCEPTION 'Foreign update permitted';END IF;
 PERFORM set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
 BEGIN INSERT INTO tj.crm_tasks(organization_id,title,assignee_user_id) VALUES(org,'Unmapped',src);RAISE EXCEPTION 'Unmapped write permitted';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
END $$;
RESET ROLE;
DO $$ DECLARE d uuid:=current_setting('test.deal')::uuid;src uuid:=current_setting('test.source')::uuid;BEGIN
 IF (SELECT count(*) FROM tj.crm_stage_history WHERE deal_id=d)<>1 OR NOT EXISTS(SELECT 1 FROM tj.crm_stage_history h JOIN tj.profiles p ON p.id=h.changed_by WHERE h.deal_id=d AND p.user_id=src) THEN RAISE EXCEPTION 'Stage audit identity/count';END IF;
 IF (SELECT count(*) FROM tj.crm_temperature_history WHERE entity_id=d)<>1 OR (SELECT count(*) FROM tj.crm_archive_log WHERE record_id=d)<>2 THEN RAISE EXCEPTION 'Temperature/archive audit';END IF;
 IF NOT EXISTS(SELECT 1 FROM tj.crm_postmortems r JOIN tj.profiles p ON p.id=r.salesperson_id WHERE r.deal_id=d AND p.user_id=src) THEN RAISE EXCEPTION 'Reflection profile mapping';END IF;
END $$;
UPDATE tj.organization_members SET role='owner',visibility_scope='all' WHERE organization_id=current_setting('test.org')::uuid AND user_id=current_setting('test.source')::uuid;
UPDATE tj.organization_members SET status='active' WHERE organization_id=current_setting('test.org')::uuid AND user_id=current_setting('test.other')::uuid;
DO $$ BEGIN PERFORM set_config('request.jwt.claim.sub',(SELECT target_user_id::text FROM tj.source_user_identity_map WHERE source_user_id=current_setting('test.source')::uuid AND activation_status='activated'),true);END $$;
SET LOCAL ROLE authenticated;
UPDATE tj.crm_deals SET owner_user_id=current_setting('test.other')::uuid WHERE id=current_setting('test.deal')::uuid;
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM tj.crm_deals WHERE id=current_setting('test.deal')::uuid AND owner_user_id=current_setting('test.other')::uuid) THEN RAISE EXCEPTION 'Administrator reassignment failed';END IF;END $$;
RESET ROLE;
UPDATE tj.organization_members SET role='viewer',visibility_scope='own' WHERE organization_id=current_setting('test.org')::uuid AND user_id=current_setting('test.source')::uuid;
SET LOCAL ROLE authenticated;
DO $$ BEGIN BEGIN INSERT INTO tj.crm_deals(organization_id,owner_user_id,title) VALUES(current_setting('test.org')::uuid,current_setting('test.source')::uuid,'Forbidden viewer');RAISE EXCEPTION 'Viewer write permitted';EXCEPTION WHEN insufficient_privilege THEN NULL;END;END $$;
RESET ROLE;
ROLLBACK;
