// ai-intelligence-router v6.1 — Luna as default fast tier
// Change: gpt-4.1-mini → gpt-5.6-luna ($0.20/$1.20 per 1M vs $0.40/$1.60)
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
type Json = Record<string, any>;
type Persona = "TJ"|"Natalie"|"Leah"|"Caden"|"Asher"|"Katrina";
type ModelTier = "fast"|"standard"|"strong";
const TEAM: Persona[] = ["TJ","Natalie","Leah","Caden","Asher","Katrina"];
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
function cacheKey(msg: string): string { return msg.toLowerCase().replace(/[^a-z0-9 ]/g, '').replace(/\s+/g, ' ').trim(); }
async function cacheGet(admin: any, key: string): Promise<{hit:boolean; text?:string; persona?:string; type?:string}> { try { const { data } = await admin.from("ai_response_cache").select("response_text,persona_name,deterministic_type,hit_count").eq("cache_key", key).gt("expires_at", new Date().toISOString()).maybeSingle(); if (!data) return { hit: false }; admin.from("ai_response_cache").update({ hit_count: (data.hit_count ?? 0) + 1 }).eq("cache_key", key).then(() => {}); return { hit: true, text: data.response_text, persona: data.persona_name, type: data.deterministic_type }; } catch { return { hit: false }; } }
async function cacheSet(admin: any, key: string, text: string, persona: string, type: string, source: string, ttlHours = 24) { try { await admin.from("ai_response_cache").upsert({ cache_key: key, response_text: text, persona_name: persona, deterministic_type: type, source_table: source, ttl_hours: ttlHours, hit_count: 0, expires_at: new Date(Date.now() + ttlHours * 3600000).toISOString() }, { onConflict: "cache_key" }); } catch {} }
interface ComplexityResult { tier: ModelTier; reason: string; deterministic: boolean; deterministicType?: string }
function classifyComplexity(message: string, historyLength: number): ComplexityResult {
  const lower = message.toLowerCase(), wordCount = message.split(/\s+/).length;
  if (/\brecall\b/.test(lower) && wordCount < 20) return { tier: "fast", reason: "recall_lookup", deterministic: true, deterministicType: "recall" };
  if (/\bwarranty\b/.test(lower) && !/explain|why|compare|better/i.test(lower) && wordCount < 20) return { tier: "fast", reason: "warranty_lookup", deterministic: true, deterministicType: "warranty" };
  if (/\b(phone|contact|call|number|email|support line)\b/.test(lower) && wordCount < 20) return { tier: "fast", reason: "contact_lookup", deterministic: true, deterministicType: "contact" };
  if (/\b(spec|dimension|width|height|depth|capacity|voltage|amperage)\b/.test(lower) && !/compare|vs|versus|better|recommend/i.test(lower) && wordCount < 25) return { tier: "fast", reason: "spec_lookup", deterministic: true, deterministicType: "spec" };
  if (/\b(install|rough.?in|clearance|cutout|electrical req|plumbing req|venting req)\b/.test(lower) && !/compare|recommend|should/i.test(lower) && wordCount < 25) return { tier: "fast", reason: "installation_lookup", deterministic: true, deterministicType: "installation" };
  if (/\b(map policy|map pricing|minimum advertised|price protection)\b/.test(lower) && wordCount < 20) return { tier: "fast", reason: "map_lookup", deterministic: true, deterministicType: "map_policy" };
  if (/\b(selling angle|selling point|why sell|how to sell|pitch for|position)\b/.test(lower) && wordCount < 25) return { tier: "fast", reason: "selling_angles_lookup", deterministic: true, deterministicType: "selling_angles" };
  if (/\b(cross.?reference|alternative|competitor|switch from|instead of)\b/.test(lower) && !/compare|which is better|recommend/i.test(lower) && wordCount < 25) return { tier: "fast", reason: "cross_ref_lookup", deterministic: true, deterministicType: "cross_reference" };
  if (/\b(lifecycle|end of life|discontinued|replacement model|replaced by)\b/.test(lower) && wordCount < 20) return { tier: "fast", reason: "lifecycle_lookup", deterministic: true, deterministicType: "lifecycle" };
  const strongSignals = ["analyze","analysis","coaching session","score my","evaluate my","role-play","roleplay","role play","transcript","performance review","post-mortem","lost the sale","won the sale","management coaching","training module","training course","compare my performance","what did i do wrong","how could i improve","strategy for","deep dive","walk me through","seven steps","11 steps","steps of selling","difficult customer","angry customer"];
  if (strongSignals.some(s => lower.includes(s))) return { tier: "strong", reason: "coaching_or_analysis", deterministic: false };
  if (wordCount > 80) return { tier: "standard", reason: "long_message", deterministic: false };
  if (historyLength > 8) return { tier: "standard", reason: "deep_conversation", deterministic: false };
  const standardSignals = ["explain why","help me understand","what should i say","objection","how do i handle","how would you","recommend","suggestion","which is better","compare","versus","vs","pros and cons","write me","draft a","create a","what's the difference","should i"];
  if (standardSignals.some(s => lower.includes(s))) return { tier: "standard", reason: "reasoning_needed", deterministic: false };
  return { tier: "fast", reason: "simple_request", deterministic: false };
}
async function executeDeterministicTool(type: string, message: string, admin: any): Promise<{ok:boolean; data:string; source:string}> {
  const lower = message.toLowerCase();
  const { data: brandRows } = await admin.from("brand_catalog").select("brand_name").eq("is_active", true);
  const allBrands: string[] = (brandRows ?? []).map((b: any) => b.brand_name).filter(Boolean);
  const matchedBrands = allBrands.filter(n => lower.includes(n.toLowerCase())).sort((a, b) => b.length - a.length).slice(0, 3);
  const modelNumbers = [...message.matchAll(/\b[A-Z]{2,5}[A-Z0-9-]{4,}\b/g)].map(m => m[0]);
  switch (type) {
    case "recall": { if (!matchedBrands.length && !modelNumbers.length) return { ok: false, data: "I couldn't identify a brand or model number. Which brand or model are you asking about?", source: "deterministic" }; const results: string[] = []; for (const brand of matchedBrands) { const { data: recalls } = await admin.from("aiq_recalls").select("title,hazard,recall_date,units_affected,remedy,url,model_numbers").ilike("brand_name", brand); if (!recalls?.length) { results.push(`No recalls on file for ${brand}.`); } else { results.push(`**${brand} \u2014 ${recalls.length} recall(s) on file:**`); for (const r of recalls.slice(0, 5)) { results.push(`\u2022 "${r.title}" (${r.recall_date ?? "date unknown"}) \u2014 Hazard: ${r.hazard ?? "n/a"}. Models: ${(r.model_numbers ?? []).join(", ") || "see notice"}. Remedy: ${r.remedy ?? "see notice"}.`); } if (recalls.length > 5) results.push(`...and ${recalls.length - 5} more.`); } } return { ok: true, data: results.join("\n"), source: "aiq_recalls" }; }
    case "warranty": { if (!matchedBrands.length) return { ok: false, data: "Which brand's warranty are you asking about?", source: "deterministic" }; const results: string[] = []; for (const brand of matchedBrands) { const { data: warranties } = await admin.from("aiq_warranty_policies").select("category,full_coverage_years,full_coverage_notes,component_warranties,key_exclusions,last_verified_date").ilike("brand_name", brand); if (!warranties?.length) { results.push(`No warranty policies on file for ${brand}.`); } else { results.push(`**${brand} warranty coverage:**`); for (const w of warranties) { let compText = ""; try { const comps = typeof w.component_warranties === "string" ? JSON.parse(w.component_warranties) : (w.component_warranties ?? []); if (Array.isArray(comps) && comps.length) compText = " Extended: " + comps.map((c: any) => `${c.component} ${c.years}yr`).join(", ") + "."; } catch {} results.push(`\u2022 ${w.category}: ${w.full_coverage_years}yr full. ${w.full_coverage_notes ?? ""}${compText} (verified ${w.last_verified_date ?? "unknown"})`); } } } return { ok: true, data: results.join("\n"), source: "aiq_warranty_policies" }; }
    case "contact": { if (!matchedBrands.length) return { ok: false, data: "Which brand's contact information are you looking for?", source: "deterministic" }; const results: string[] = []; for (const brand of matchedBrands) { const { data: contacts } = await admin.from("aiq_vendor_contacts").select("country,customer_service_phone,customer_service_phone_label,customer_service_hours,service_repair_phone,warranty_phone,support_email,service_portal_url,confidence_level").ilike("brand_name", brand); if (!contacts?.length) { results.push(`No contact info on file for ${brand}.`); } else { results.push(`**${brand} contact info:**`); for (const c of contacts) { const bits: string[] = []; if (c.customer_service_phone) bits.push(`${c.customer_service_phone_label ?? "Customer Service"}: ${c.customer_service_phone}${c.customer_service_hours ? " (" + c.customer_service_hours + ")" : ""}`); if (c.service_repair_phone && c.service_repair_phone !== c.customer_service_phone) bits.push(`Service/Repair: ${c.service_repair_phone}`); if (c.warranty_phone && c.warranty_phone !== c.customer_service_phone) bits.push(`Warranty: ${c.warranty_phone}`); if (c.support_email) bits.push(`Email: ${c.support_email}`); if (c.service_portal_url) bits.push(`Book service: ${c.service_portal_url}`); results.push(`${c.country}: ${bits.join(" | ")} (confidence: ${c.confidence_level})`); } } } return { ok: true, data: results.join("\n"), source: "aiq_vendor_contacts" }; }
    case "spec": { const products: any[] = []; if (modelNumbers.length) { for (const model of modelNumbers.slice(0, 3)) { const { data } = await admin.from("aiq_products").select("brand_name,model,category,short_description,width_inches,height_inches,depth_inches,depth_with_handles,capacity_cu_ft,energy_star,installation_type,voltage,amperage,msrp,sale_price,finish").ilike("model", `%${model}%`).limit(3); if (data?.length) products.push(...data); } } if (!products.length && matchedBrands.length) { for (const brand of matchedBrands) { const { data } = await admin.from("aiq_products").select("brand_name,model,category,short_description,width_inches,height_inches,depth_inches,depth_with_handles,capacity_cu_ft,energy_star,installation_type,voltage,amperage,msrp,sale_price,finish").ilike("brand_name", brand).limit(5); if (data?.length) products.push(...data); } } if (!products.length) return { ok: false, data: "I couldn't find that product. Can you give me the exact model number?", source: "deterministic" }; const results: string[] = []; for (const p of products.slice(0, 5)) { const specs: string[] = [`**${p.brand_name} ${p.model}** \u2014 ${p.category ?? ""}`, p.short_description ?? ""]; if (p.width_inches || p.height_inches || p.depth_inches) specs.push(`Dimensions: ${p.width_inches ?? "?"}\" W \u00d7 ${p.height_inches ?? "?"}\" H \u00d7 ${p.depth_inches ?? "?"}\" D${p.depth_with_handles ? ` (${p.depth_with_handles}\" with handles)` : ""}`); if (p.capacity_cu_ft) specs.push(`Capacity: ${p.capacity_cu_ft} cu ft`); if (p.energy_star != null) specs.push(`ENERGY STAR: ${p.energy_star ? "Yes" : "No"}`); if (p.installation_type) specs.push(`Installation: ${p.installation_type}`); if (p.voltage) specs.push(`Electrical: ${p.voltage}V${p.amperage ? ` / ${p.amperage}A` : ""}`); if (p.finish) specs.push(`Finish: ${p.finish}`); if (p.msrp || p.sale_price) specs.push(`Price: ${p.sale_price ? `$${p.sale_price}` : ""}${p.msrp ? ` (MSRP $${p.msrp})` : ""}`); results.push(specs.filter(Boolean).join("\n")); } return { ok: true, data: results.join("\n\n"), source: "aiq_products" }; }
    case "installation": { const { data: installs } = await admin.from("installation_requirements").select("*").limit(14); if (!installs?.length) return { ok: false, data: "No installation requirements data available.", source: "deterministic" }; const cats = ["range","refrigerator","dishwasher","washer","dryer","cooktop","wall oven","hood","microwave","freezer"]; const mentionedCat = cats.find(c => lower.includes(c)); const filtered = mentionedCat ? installs.filter((i: any) => (i.category||i.appliance_type||"").toLowerCase().includes(mentionedCat)) : installs; const target = filtered.length ? filtered : installs.slice(0, 5); const results: string[] = ["**Installation Requirements:**"]; for (const i of target) { results.push(`\n**${i.category || i.appliance_type || "General"}**`); if (i.electrical) results.push(`Electrical: ${i.electrical}`); if (i.plumbing) results.push(`Plumbing: ${i.plumbing}`); if (i.venting) results.push(`Venting: ${i.venting}`); if (i.clearances) results.push(`Clearances: ${i.clearances}`); if (i.notes) results.push(`Notes: ${i.notes}`); } return { ok: true, data: results.join("\n"), source: "installation_requirements" }; }
    case "map_policy": { if (!matchedBrands.length) return { ok: false, data: "Which brand's MAP policy are you asking about?", source: "deterministic" }; const results: string[] = []; for (const brand of matchedBrands) { const { data: policies } = await admin.from("brand_map_policies").select("*").ilike("brand_name", brand); if (!policies?.length) { results.push(`No MAP policy on file for ${brand}.`); } else { for (const p of policies) { results.push(`**${brand} MAP Policy:**`); if (p.policy_summary) results.push(p.policy_summary); if (p.enforcement_level) results.push(`Enforcement: ${p.enforcement_level}`); if (p.online_policy) results.push(`Online: ${p.online_policy}`); if (p.violation_consequences) results.push(`Violations: ${p.violation_consequences}`); } } } return { ok: true, data: results.join("\n"), source: "brand_map_policies" }; }
    case "selling_angles": { if (!matchedBrands.length) return { ok: false, data: "Which brand are you looking for selling angles on?", source: "deterministic" }; const results: string[] = []; for (const brand of matchedBrands) { const { data: vendors } = await admin.from("mfr_vendors").select("name,rightFor,sellingAngles,specGuides").ilike("name", brand).limit(1); const { data: catalog } = await admin.from("brand_catalog").select("name,tier,brand_story_short,country_of_origin").ilike("name", brand).limit(1); const v = vendors?.[0]; const c = catalog?.[0]; results.push(`**${brand} Selling Guide:**`); if (c?.tier) results.push(`Tier: ${c.tier}`); if (c?.country_of_origin) results.push(`Origin: ${c.country_of_origin}`); if (c?.brand_story_short) results.push(`Story: ${c.brand_story_short}`); if (v?.rightFor) results.push(`\n**Right For:** ${v.rightFor}`); if (v?.sellingAngles) results.push(`\n**Selling Angles:** ${v.sellingAngles}`); if (v?.specGuides) results.push(`\n**Spec Guides:** ${v.specGuides}`); } return { ok: true, data: results.join("\n"), source: "mfr_vendors+brand_catalog" }; }
    case "cross_reference": { const results: string[] = []; if (matchedBrands.length >= 2) { const { data: ccr } = await admin.from("competitive_cross_reference").select("brand_a,model_a,brand_b,model_b,category,comparison_summary").or(`brand_a.ilike.%${matchedBrands[0]}%,brand_b.ilike.%${matchedBrands[0]}%`).limit(10); const filtered = ccr?.filter((c: any) => matchedBrands.some(b => c.brand_a?.toLowerCase().includes(b.toLowerCase()) || c.brand_b?.toLowerCase().includes(b.toLowerCase()))); if (filtered?.length) { results.push(`**Cross-Reference: ${matchedBrands.join(" vs ")}**`); for (const c of filtered.slice(0, 8)) { results.push(`\u2022 ${c.brand_a} ${c.model_a || ""} \u2194 ${c.brand_b} ${c.model_b || ""} (${c.category || ""}): ${c.comparison_summary || ""}`); } } } else if (matchedBrands.length === 1) { const { data: ccr } = await admin.from("competitive_cross_reference").select("brand_a,model_a,brand_b,model_b,category,comparison_summary").or(`brand_a.ilike.%${matchedBrands[0]}%,brand_b.ilike.%${matchedBrands[0]}%`).limit(8); if (ccr?.length) { results.push(`**${matchedBrands[0]} Cross-References (${ccr.length} entries):**`); for (const c of ccr) { results.push(`\u2022 ${c.brand_a} ${c.model_a || ""} \u2194 ${c.brand_b} ${c.model_b || ""}: ${c.comparison_summary || ""}`); } } } if (!results.length) return { ok: false, data: "No cross-reference data found. Try naming specific brands.", source: "deterministic" }; return { ok: true, data: results.join("\n"), source: "competitive_cross_reference" }; }
    case "lifecycle": { const results: string[] = []; for (const brand of matchedBrands) { const { data: lc } = await admin.from("product_lifecycle").select("*").ilike("brand_name", brand).limit(10); if (lc?.length) { results.push(`**${brand} Product Lifecycle:**`); for (const l of lc) { results.push(`\u2022 ${l.model || "?"}: ${l.status || "?"} ${l.replacement_model ? "\u2192 Replaced by " + l.replacement_model : ""} ${l.end_of_life_date ? "(EOL: " + l.end_of_life_date + ")" : ""}`); } } } if (modelNumbers.length && !results.length) { for (const mn of modelNumbers.slice(0, 3)) { const { data: lc } = await admin.from("product_lifecycle").select("*").ilike("model", `%${mn}%`).limit(3); if (lc?.length) { for (const l of lc) { results.push(`**${l.brand_name || ""} ${l.model}**: ${l.status || "?"} ${l.replacement_model ? "\u2192 " + l.replacement_model : ""}`); } } } } if (!results.length) return { ok: false, data: "No lifecycle data found for that brand/model.", source: "deterministic" }; return { ok: true, data: results.join("\n"), source: "product_lifecycle" }; }
    default: return { ok: false, data: "Unknown tool type", source: "deterministic" };
  }
}
async function fetchCrossAppContext(message: string, sourceApp: string, admin: any, userId: string | null): Promise<string> {
  const lower = message.toLowerCase(); const sections: string[] = [];
  if (lower.match(/\b(deal|pipeline|contact|customer|lead|follow.?up|stale|idle|overdue|crm|quote sent|close)\b/)) { try { const { data: deals } = await admin.from("crm_deals").select("title,stage,value_amount,contact_name,updated_at,created_at").order("updated_at", { ascending: false }).limit(15); if (deals?.length) { const now = Date.now(); const enriched = deals.map((d: any) => { const idle = Math.floor((now - new Date(d.updated_at).getTime()) / 86400000); return `\u2022 ${d.title} \u2014 ${d.stage} \u2014 $${d.value_amount || 0} \u2014 ${d.contact_name || "?"} \u2014 ${idle}d idle`; }); sections.push(`LIVE CRM PIPELINE (${deals.length} deals):\n${enriched.join("\n")}`); } } catch {} }
  if (lower.match(/\b(training|progress|certif|badge|quiz|learn|academy|course|module|score)\b/)) { try { const { data: progress } = await admin.from("academy_brand_progress").select("*").limit(20); const { data: certs } = await admin.from("academy_brand_certifications").select("*").order("earned_at", { ascending: false }).limit(10); const { data: scores } = await admin.from("academy_brand_quiz_scores").select("*").order("completed_at", { ascending: false }).limit(10); if (progress?.length) sections.push(`TRAINING PROGRESS (${progress.length} entries):\n${JSON.stringify(progress.slice(0, 10), null, 1)}`); if (certs?.length) sections.push(`CERTIFICATIONS (${certs.length}):\n${JSON.stringify(certs, null, 1)}`); if (scores?.length) sections.push(`RECENT QUIZ SCORES:\n${JSON.stringify(scores.slice(0, 5), null, 1)}`); } catch {} }
  if (lower.match(/\b(spec iq|package|quote|order|invoice|proposal)\b/) && lower.match(/\b(status|my|open|pending|latest|recent)\b/)) { try { const { data: pkgs } = await admin.from("speciq_packages").select("package_name,status,total_price,customer_name,created_at").order("created_at", { ascending: false }).limit(10); if (pkgs?.length) sections.push(`SPEC IQ PACKAGES (${pkgs.length}):\n${pkgs.map((p: any) => `\u2022 ${p.package_name || "?"} \u2014 ${p.status} \u2014 $${p.total_price || 0} \u2014 ${p.customer_name || "?"}`).join("\n")}`); } catch {} }
  if (lower.match(/\b(up system|queue|floor|rotation|shift|missed up|who.?s up|greeter)\b/)) { try { const { data: queue } = await admin.from("iq_up_queue_entries").select("*").order("position", { ascending: true }).limit(10); if (queue?.length) sections.push(`UP SYSTEM QUEUE (${queue.length} entries):\n${JSON.stringify(queue, null, 1)}`); } catch {} }
  if (lower.match(/\b(field|store walk|checklist|action plan|inspection|audit)\b/)) { try { const { data: resp } = await admin.from("field_checklist_responses").select("*").order("created_at", { ascending: false }).limit(8); if (resp?.length) sections.push(`FIELD RESPONSES (${resp.length}):\n${JSON.stringify(resp.slice(0, 5), null, 1)}`); } catch {} }
  return sections.length ? "\n\n=== LIVE ECOSYSTEM DATA ===\n" + sections.join("\n\n") : "";
}
function route(message: string, max: number) { const q = message.toLowerCase(); const s: Record<Persona, number> = { TJ: 0, Natalie: 0, Leah: 0, Caden: 0, Asher: 0, Katrina: 0 }; const add = (p: Persona, words: string[], w: number) => words.forEach(x => { if (q.includes(x)) s[p] += w; }); const product = ["model","spec","feature","compare","price","product","brand","refrigerator","fridge","range","dishwasher","washer","dryer","appliance","oven","cooktop","freezer","microwave","hood"]; add("Natalie", product, 3); add("Asher", ["fit","install","dimension","width","height","depth","opening","clearance","electrical","gas","vent","water line","door swing"], 4); add("Leah", ["design","style","colour","color","finish","kitchen","aesthetic","layout","lifestyle","family"], 3); add("TJ", ["sell","sales","close","objection","customer","pitch","follow-up","quote","commission","deal","pipeline","crm"], 4); add("Caden", ["teach","training","learn","explain","lesson","quiz","module","progress","certif","academy"], 4); add("Katrina", ["service","repair","problem","issue","complaint","warranty","support","troubleshoot","broken","recall"], 4); if (Object.values(s).every(v => v === 0)) s.Natalie = 1; const ranked = (Object.entries(s) as [Persona, number][]).sort((a, b) => b[1] - a[1]); const people = ranked.filter(x => x[1] > 0).slice(0, max).map(x => x[0]); return { primary: people[0] ?? "Natalie", personas: people.length ? people : ["Natalie"], reason: ranked.filter(x => x[1] > 0).map(x => `${x[0]}:${x[1]}`).join(", "), productIntent: product.some(x => q.includes(x)) || s.Natalie > 0 || s.Asher > 0 }; }
function memoryContext(m: Json, s: Json | null) { return ["CUSTOMER MEMORY (authoritative):", JSON.stringify({ conversation_id: m.conversation_id, stage: m.stage, profile: m.profile, contradictions: m.contradictions, completeness_score: m.completeness_score, next_discovery_question: m.next_discovery_question, missing_profile_fields: m.missing_profile_fields }, null, 2), s ? "SCORED RECOMMENDATIONS (authoritative):\n" + JSON.stringify({ recommendations: s.recommendations, labelled_recommendations: s.labelled_recommendations, next_discovery_question: s.next_discovery_question }, null, 2).slice(0, 18000) : "No scored recommendation was run."].join("\n\n"); }
function memorySummary(m: Json) { return { stage: m.stage, profile: m.profile, completeness_score: m.completeness_score, next_discovery_question: m.next_discovery_question, missing_profile_fields: m.missing_profile_fields, recommendation_ready: m.recommendation_ready, contradictions: m.contradictions }; }
async function call(url: string, key: string, auth: string, fn: string, payload: Json) { try { const r = await fetch(`${url}/functions/v1/${fn}`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: auth, apikey: key }, body: JSON.stringify(payload) }); return { ok: r.ok, data: await r.json().catch(() => ({})) }; } catch (e) { return { ok: false, data: { error: String(e) } }; } }
async function persona(url: string, key: string, auth: string, org: string | null, id: string, message: string, history: any[], tier: ModelTier) { try { const r = await fetch(`${url}/functions/v1/ai-team-coach`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: auth, apikey: key }, body: JSON.stringify({ organization_id: org, persona_id: id, message, history, model_tier: tier }) }); const d = await r.json().catch(() => ({})); return { ok: r.ok && d.ok !== false, answer: String(d.answer ?? ""), detail: d.detail ? String(d.detail) : undefined, model_used: d.model_used ?? null, cost_estimate_usd: d.cost_estimate_usd ?? 0 }; } catch (e) { return { ok: false, answer: "", detail: String(e), model_used: null, cost_estimate_usd: 0 }; } }
async function saveAssistantTurn(url: string, key: string, conversationId: string, content: string, personaName: string, ok: boolean, metadata?: Json) { if (!content) return; try { await fetch(`${url}/rest/v1/ai_conversation_turns`, { method: "POST", headers: { apikey: key, Authorization: `Bearer ${key}`, "Content-Type": "application/json", Prefer: "return=minimal" }, body: JSON.stringify({ conversation_id: conversationId, role: "assistant", content, persona_name: personaName, metadata: { ok, ...metadata } }) }); } catch {} }
function out(body: unknown, status = 200) { return new Response(JSON.stringify(body), { status, headers: { ...CORS, "Content-Type": "application/json" } }); }
async function synthesize(message: string, context: string, specialists: Json[], tier: ModelTier): Promise<string> { const prompt = ["You are the Appliance IQ Intelligence Router. Combine the specialist findings into one grounded answer.", "Use stored customer memory and scored recommendations as authoritative. Do not invent missing facts.", `Customer message: ${message}`, context, "SPECIALISTS:", ...specialists.map((r: Json) => `[${r.persona} - ${r.role}]\n${r.answer}`)].join("\n\n"); if (tier === "fast") { const openaiKey = Deno.env.get("OPENAI_API_KEY") ?? ""; if (openaiKey) { try { const r = await fetch("https://api.openai.com/v1/chat/completions", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${openaiKey}` }, body: JSON.stringify({ model: Deno.env.get("AI_MODEL_FAST") ?? "gpt-5.6-luna", max_tokens: 1500, temperature: 0, messages: [{ role: "user", content: prompt }] }) }); if (r.ok) { const d = await r.json(); const text = d.choices?.[0]?.message?.content ?? ""; if (text) return text; } } catch {} } } const anthropicKey = Deno.env.get("ANTHROPIC_API_KEY") ?? "", model = Deno.env.get("AI_MODEL") ?? "claude-sonnet-4-6"; if (anthropicKey) { try { const r = await fetch("https://api.anthropic.com/v1/messages", { method: "POST", headers: { "content-type": "application/json", "x-api-key": anthropicKey, "anthropic-version": "2023-06-01" }, body: JSON.stringify({ model, max_tokens: 1500, temperature: 0, messages: [{ role: "user", content: prompt }] }) }); if (r.ok) { const d = await r.json(); return (d.content ?? []).filter((b: any) => b.type === "text").map((b: any) => b.text).join("\n").trim(); } } catch {} } return ""; }
async function resolveUserId(url: string, anon: string, auth: string): Promise<string | null> { try { const r = await fetch(`${url}/auth/v1/user`, { headers: { Authorization: auth, apikey: anon } }); if (r.ok) { const u = await r.json(); return u.id ?? null; } } catch {} return null; }
Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  if (req.method !== "POST") return out({ ok: false, detail: "method_not_allowed" }, 405);
  const auth = req.headers.get("Authorization") ?? ""; if (!auth.startsWith("Bearer ")) return out({ ok: false, detail: "authentication_required" }, 401);
  let body: Json; try { body = await req.json(); } catch { return out({ ok: false, detail: "invalid_json_body" }, 400); }
  const message = String(body.message ?? "").trim(); if (!message) return out({ ok: false, detail: "message_required" }, 400);
  const url = Deno.env.get("SUPABASE_URL") ?? "", anon = Deno.env.get("SUPABASE_ANON_KEY") ?? "", service = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
  const organizationId = body.organization_id ? String(body.organization_id) : null, country = String(body.country ?? "CA").toUpperCase(), retailer = body.retailer_name ? String(body.retailer_name) : null;
  const history = Array.isArray(body.history) ? body.history : [], max = Math.max(1, Math.min(Number(body.max_specialists ?? 3), 4));
  const sourceApp = body.metadata?.source_app ?? "unknown";
  const admin = createClient(url, service);
  const ck = cacheKey(message); const cached = await cacheGet(admin, ck);
  if (cached.hit && cached.text) { return out({ ok: true, engine: "applianceiq-intelligence-router-v6.1", mode: "cached", conversation_id: body.conversation_id ?? null, answer: cached.text, primary_persona: cached.persona ?? "Natalie", complexity: { tier: "cached", auto_detected: "cached", reason: "cache_hit", deterministic_type: cached.type }, model_used: { provider: "cache", model: "none", tier_requested: "cached" }, cost_estimate_usd: 0, specialists: [] }); }
  const { data: personas, error } = await admin.from("ai_personas").select("id,persona_name,persona_role").eq("active", true).in("persona_name", TEAM);
  if (error || !personas?.length) return out({ ok: false, detail: "active_personas_not_found" }, 500);
  const byName = new Map(personas.map((p: any) => [p.persona_name, p]));
  const memory = await call(url, anon, auth, "conversation-memory-engine", { message, conversation_id: body.conversation_id ?? null, organization_id: organizationId, crm_record_type: body.crm_record_type ?? null, crm_record_id: body.crm_record_id ?? null, title: body.title ?? null });
  if (!memory.ok) return out({ ok: false, detail: "conversation_memory_failed", memory_error: memory.data }, 502);
  const conversationId = memory.data.conversation_id, profile = memory.data.profile ?? {}, recommendationReady = Boolean(memory.data.recommendation_ready);
  const userId = await resolveUserId(url, anon, auth);
  const complexity = classifyComplexity(message, history.length);
  const requestedTier = body.model_tier ? String(body.model_tier) as ModelTier : null;
  let effectiveTier: ModelTier = requestedTier && ["fast", "standard", "strong"].includes(requestedTier) ? requestedTier : complexity.tier;
  if (String(body.mode ?? "auto") === "manual" || body.persona_id) { const selected = body.persona_id ? personas.find((p: any) => p.id === String(body.persona_id)) : byName.get(String(body.persona_name ?? "")); if (!selected) return out({ ok: false, detail: "persona_not_found" }, 404); const crossApp = await fetchCrossAppContext(message, sourceApp, admin, userId); const context = memoryContext(memory.data, null) + crossApp; const r = await persona(url, anon, auth, organizationId, selected.id, `${message}\n\n${context}`, history, effectiveTier); await saveAssistantTurn(url, service, conversationId, r.answer, selected.persona_name, r.ok, { tier: effectiveTier, model_used: r.model_used, source_app: sourceApp }); return out({ ok: r.ok, engine: "applianceiq-intelligence-router-v6.1", mode: "manual", conversation_id: conversationId, memory: memorySummary(memory.data), answer: r.answer, primary_persona: selected.persona_name, complexity: { tier: effectiveTier, auto_detected: complexity.tier, reason: complexity.reason }, model_used: r.model_used, cost_estimate_usd: r.cost_estimate_usd, specialists: [r] }, r.ok ? 200 : 502); }
  if (complexity.deterministic && complexity.deterministicType) { const result = await executeDeterministicTool(complexity.deterministicType, message, admin); const answer = result.data; const personaName = ["contact", "warranty", "recall", "service"].includes(complexity.deterministicType) ? "Katrina" : complexity.deterministicType === "installation" ? "Asher" : complexity.deterministicType === "selling_angles" ? "TJ" : "Natalie"; if (result.ok) await cacheSet(admin, ck, answer, personaName, complexity.deterministicType, result.source, 48); await saveAssistantTurn(url, service, conversationId, answer, personaName, result.ok, { tier: "deterministic", deterministic_type: complexity.deterministicType, source: result.source, source_app: sourceApp }); return out({ ok: result.ok, engine: "applianceiq-intelligence-router-v6.1", mode: "deterministic", conversation_id: conversationId, memory: memorySummary(memory.data), answer, primary_persona: personaName, complexity: { tier: "deterministic", auto_detected: complexity.tier, reason: complexity.reason, deterministic_type: complexity.deterministicType }, model_used: { provider: "none", model: "deterministic", tier_requested: "deterministic" }, cost_estimate_usd: 0, data_source: result.source, recommendation_scoring_used: false, recommendation_scoring: null, specialists: [] }); }
  const crossAppData = await fetchCrossAppContext(message, sourceApp, admin, userId);
  const routing = route(message, max); let scoring: any = null;
  if (routing.productIntent && recommendationReady) { scoring = await call(url, anon, auth, "recommendation-scoring-engine", { query: message, conversation_id: conversationId, profile, country, retailer_name: retailer, limit: 5 }); }
  const context = memoryContext(memory.data, scoring?.ok ? scoring.data : null) + crossAppData;
  const selected = routing.personas.map(n => byName.get(n)).filter(Boolean);
  const results = await Promise.all(selected.map(async (p: any) => { const r = await persona(url, anon, auth, organizationId, p.id, `${message}\n\n${context}`, history, effectiveTier); return { persona: p.persona_name, role: p.persona_role, ...r }; }));
  const good = results.filter((r: any) => r.ok && r.answer);
  if (!good.length) return out({ ok: false, detail: "all_specialists_failed", conversation_id: conversationId, memory: memorySummary(memory.data), complexity: { tier: effectiveTier, auto_detected: complexity.tier, reason: complexity.reason }, specialists: results }, 502);
  let answer = good[0].answer; if (good.length > 1) { const synthesized = await synthesize(message, context, good, effectiveTier); if (synthesized) answer = synthesized; }
  const totalCost = results.reduce((sum: number, r: any) => sum + (r.cost_estimate_usd ?? 0), 0);
  await saveAssistantTurn(url, service, conversationId, answer, routing.primary, true, { tier: effectiveTier, auto_detected_tier: complexity.tier, personas_used: routing.personas, total_cost_usd: totalCost, source_app: sourceApp });
  return out({ ok: true, engine: "applianceiq-intelligence-router-v6.1", mode: "auto", conversation_id: conversationId, answer, primary_persona: routing.primary, routed_personas: routing.personas, routing_reason: routing.reason, memory: memorySummary(memory.data), complexity: { tier: effectiveTier, auto_detected: complexity.tier, reason: complexity.reason, deterministic: false }, model_used: good[0].model_used, cost_estimate_usd: totalCost, recommendation_scoring_used: Boolean(scoring?.ok), recommendation_scoring: scoring?.ok ? { result_count: scoring.data.result_count, labelled_recommendations: scoring.data.labelled_recommendations, next_discovery_question: scoring.data.next_discovery_question } : null, specialists: results });
});
