import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const RES:any={customers:'customer',invoices:'invoice',models:'model',service:'service_ticket',salespeople:'salesperson',locations:'location'};
const IDS:any={customer:['customer_id','customerId','id','number'],invoice:['invoice_id','invoiceId','invoice_number','invoiceNumber','id'],model:['model_id','modelId','model','sku','id'],service_ticket:['ticket_id','ticketId','service_order_number','serviceOrderNumber','id'],salesperson:['salesperson_id','salespersonId','employee_id','employeeId','code','id'],location:['location_id','locationId','store_id','storeId','store_code','storeCode','code','id']};
const NAMES:any={customer:['name','customer_name','customerName','displayName'],invoice:['invoice_number','invoiceNumber','number','id'],model:['model','description','name','sku'],service_ticket:['service_order_number','serviceOrderNumber','number','id'],salesperson:['displayName','name','fullName','salespersonName'],location:['storeName','locationName','displayName','name','store_code','storeCode']};
const first=(o:any,fs:string[])=>{for(const f of fs){const v=o?.[f];if(v!==undefined&&v!==null&&String(v)!=='')return String(v)}return ''};
const rows=(x:any)=>Array.isArray(x)?x:Array.isArray(x?.value)?x.value:Array.isArray(x?.items)?x.items:Array.isArray(x?.data)?x.data:Array.isArray(x?.results)?x.results:[];
const next=(x:any)=>x?.['@odata.nextLink']||x?.nextLink||x?.next||x?.links?.next||null;
const join=(b:string,p:string)=>/^https?:\/\//i.test(p)?p:b.replace(/\/$/,'')+'/'+p.replace(/^\//,'');
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'POST required'},405);
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,auth=req.headers.get('Authorization')??'';const uc=createClient(url,anon,{global:{headers:{Authorization:auth}}}),db=createClient(url,service);const {data:{user}}=await uc.auth.getUser();if(!user)return json({error:'unauthorized'},401);let b:any;try{b=await req.json()}catch{return json({error:'invalid_json'},400)}const action=String(b.action??'status'),cid=String(b.connection_id??'');if(!cid)return json({error:'connection_id_required'},400);
 const {data:c}=await db.from('platform_connector_connections').select('*').eq('id',cid).maybeSingle();if(!c)return json({error:'connection_not_found'},404);const {data:m}=await db.from('organization_members').select('role,status').eq('organization_id',c.organization_id).eq('user_id',user.id).eq('status','active').maybeSingle();if(!m)return json({error:'organization_access_denied'},403);const admin=['owner','admin','super_admin'].includes(String(m.role??''));const {data:co}=await db.from('platform_connectors').select('key').eq('id',c.connector_id).single();if(co?.key!=='epass')return json({error:'not_epass_connection'},400);
 let cfg:any=c.settings?.epass_api??{};if(action==='status')return json({ok:true,connection:{id:c.id,status:c.status,auth_status:c.auth_status,last_sync_at:c.last_sync_at,last_success_at:c.last_success_at,last_error:c.last_error},configuration:{base_url:cfg.base_url??null,endpoints:cfg.endpoints??{},configured:Boolean(cfg.base_url&&Object.keys(cfg.endpoints??{}).length)}});if(!admin)return json({error:'admin_required'},403);
 if(action==='configure'){const base=String(b.base_url??cfg.base_url??'').trim();if(!/^https:\/\//i.test(base))return json({error:'https_base_url_required'},400);const endpoints=b.endpoints&&typeof b.endpoints==='object'?b.endpoints:(cfg.endpoints??{});for(const k of Object.keys(endpoints)){if(!RES[k])return json({error:'unsupported_resource_key',resource:k},400)}let cr=c.credential_ref;const cred=b.credential&&typeof b.credential==='object'?b.credential:null;if(cred){const secret=JSON.stringify(cred);if(cr){const {error}=await db.rpc('platform_update_connector_secret',{p_id:cr,p_secret:secret});if(error)return json({error:error.message},500)}else{const {data,error}=await db.rpc('platform_store_connector_secret',{p_name:`epass_${cid}`,p_secret:secret,p_description:`ePASS API credential for ${cid}`});if(error||!data)return json({error:error?.message||'credential_store_failed'},500);cr=data}}
 const settings={...(c.settings??{}),epass_api:{base_url:base,endpoints,auth_mode:String(b.auth_mode??cfg.auth_mode??'headers'),api_key_header:String(b.api_key_header??cfg.api_key_header??'X-API-Key'),api_secret_header:String(b.api_secret_header??cfg.api_secret_header??'X-API-Secret'),configured_at:new Date().toISOString()}};await db.from('platform_connector_connections').update({settings,credential_ref:cr??null,auth_status:cr?'valid':'not_configured',status:'pending',last_error:null,updated_at:new Date().toISOString()}).eq('id',cid);return json({ok:true,resources:Object.keys(endpoints)})}
 if(!cfg.base_url)return json({error:'epass_not_configured'},409);let cred:any={};if(c.credential_ref){const {data,error}=await db.rpc('platform_get_connector_secret',{p_id:c.credential_ref});if(error)return json({error:error.message},500);cred=typeof data==='string'?JSON.parse(data):data}const headers:any={Accept:'application/json'};if(cred?.api_key)headers[cfg.api_key_header||'X-API-Key']=cred.api_key;if(cred?.api_secret)headers[cfg.api_secret_header||'X-API-Secret']=cred.api_secret;if(cred?.token)headers.Authorization=`Bearer ${cred.token}`;
 if(action==='test'){const p=String(b.path??Object.values(cfg.endpoints??{})[0]??'');if(!p)return json({error:'endpoint_required'},400);const r=await fetch(join(cfg.base_url,p),{headers});if(!r.ok)return json({error:'epass_test_failed',status:r.status},502);return json({ok:true,status:r.status})}if(action!=='sync')return json({error:'unknown_action'},400);
 const requested:string[]=Array.isArray(b.resources)?b.resources:Object.keys(cfg.endpoints??{}),invalid=requested.filter(k=>!RES[k]||!cfg.endpoints[k]);if(invalid.length)return json({error:'resource_not_configured',resources:invalid},400);const {data:job,error:je}=await db.from('platform_sync_jobs').insert({connection_id:cid,job_type:'epass_sync',direction:'inbound',status:'running',requested_by:user.id,started_at:new Date().toISOString()}).select('id').single();if(je)return json({error:je.message},500);const result:any={job_id:job.id,resources:{},processed:0,failed:0};try{for(const key of requested){const et=RES[key];let pu=join(cfg.base_url,String(cfg.endpoints[key])),pages=0,count=0,fail=0;while(pu&&pages<100){pages++;const r=await fetch(pu,{headers});if(!r.ok)throw new Error(`${key} fetch failed ${r.status}`);const payload=await r.json();for(const row of rows(payload)){const eid=first(row,IDS[et]);if(!eid){fail++;continue}const ir=await fetch(`${url}/functions/v1/connector-ingest`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':auth,'apikey':anon},body:JSON.stringify({connection_id:cid,external_entity_type:et,external_id:eid,canonical_name:first(row,NAMES[et])||eid,payload:row,occurred_at:first(row,['updated_at','updatedAt','modified_at','modifiedAt','date','invoice_date','invoiceDate'])||new Date().toISOString()})});if(!ir.ok){fail++;continue}count++}const nx=next(payload);pu=nx?join(cfg.base_url,String(nx)):''}result.resources[key]={processed:count,failed:fail,pages};result.processed+=count;result.failed+=fail}
 let bridge:any=null;if(requested.includes('invoices')){const r=await fetch(`${url}/functions/v1/epass-performance-bridge`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':auth,'apikey':anon},body:JSON.stringify({connection_id:cid})});bridge=await r.json().catch(()=>({}));if(!r.ok)result.failed++}result.performance_bridge=bridge;const status=result.failed?'partial':'success';await db.from('platform_sync_jobs').update({status,completed_at:new Date().toISOString(),stats:result,error_details:result.failed?{message:`${result.failed} ePASS records/stages failed`}:null}).eq('id',job.id);await db.from('platform_connector_connections').update({status:'active',auth_status:'valid',last_sync_at:new Date().toISOString(),last_success_at:status==='success'?new Date().toISOString():c.last_success_at,last_error:result.failed?`${result.failed} ePASS records/stages failed`:null,updated_at:new Date().toISOString()}).eq('id',cid);return json({ok:true,status,...result})}catch(e){const msg=String((e as any)?.message??e);await db.from('platform_sync_jobs').update({status:'failed',completed_at:new Date().toISOString(),stats:result,error_details:{message:msg}}).eq('id',job.id);return json({error:'epass_sync_failed',detail:msg,...result},502)}});
