import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const n=(v:any)=>{const x=Number(v);return Number.isFinite(x)?x:0};
const first=(o:any,fs:string[])=>{for(const f of fs){const v=o?.[f];if(v!==undefined&&v!==null&&String(v)!=='')return v}return null};
const arr=(o:any,fs:string[])=>{for(const f of fs){if(Array.isArray(o?.[f]))return o[f]}return []};
const text=(...v:any[])=>v.filter(Boolean).join(' ').toLowerCase();
const is=(s:string,r:RegExp)=>r.test(s);
const iso=(v:any)=>{const d=new Date(v||Date.now());return Number.isNaN(d.valueOf())?new Date().toISOString():d.toISOString()};
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'POST required'},405);
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,auth=req.headers.get('Authorization')??'';
 const uc=createClient(url,anon,{global:{headers:{Authorization:auth}}}),db=createClient(url,service);const {data:{user}}=await uc.auth.getUser();if(!user)return json({error:'unauthorized'},401);
 let b:any;try{b=await req.json()}catch{return json({error:'invalid_json'},400)}const cid=String(b.connection_id??'');if(!cid)return json({error:'connection_id_required'},400);
 const {data:c}=await db.from('platform_connector_connections').select('id,organization_id,store_id,connector_id').eq('id',cid).maybeSingle();if(!c)return json({error:'connection_not_found'},404);
 const {data:m}=await db.from('organization_members').select('role,status').eq('organization_id',c.organization_id).eq('user_id',user.id).eq('status','active').maybeSingle();if(!m||!['owner','admin','super_admin'].includes(String(m.role)))return json({error:'admin_required'},403);
 const {data:co}=await db.from('platform_connectors').select('key').eq('id',c.connector_id).single();if(co?.key!=='storis')return json({error:'not_storis_connection'},400);
 const {data:ks,error:ke}=await db.from('platform_connector_ingestion_keys').select('external_id,intelligence_event_id').eq('connection_id',cid).eq('external_entity_type','salesOrder').not('intelligence_event_id','is',null).limit(5000);if(ke)return json({error:ke.message},500);
 const ids=(ks??[]).map((x:any)=>x.intelligence_event_id);if(!ids.length)return json({ok:true,processed:0,message:'No STORIS sales orders available.'});
 const {data:evs,error:ee}=await db.from('intelligence_events').select('id,payload,occurred_at').in('id',ids);if(ee)return json({error:ee.message},500);const by=new Map((evs??[]).map((x:any)=>[x.id,x]));let processed=0,linesN=0,mapped=0,skipped=0,failed=0;const errors:any[]=[];
 for(const k of ks??[]){try{const ev:any=by.get(k.intelligence_event_id);if(!ev)continue;const o=ev.payload??{};const status=String(first(o,['status','orderStatus','salesOrderStatus','state'])??'').toLowerCase();const completed=Boolean(first(o,['completed','isCompleted','posted','invoiced']))||/(complete|closed|posted|invoice|delivered|final)/.test(status);if(!completed&&b.include_open!==true){skipped++;continue}
 const no=String(first(o,['orderNumber','salesOrderNumber','number','id'])??k.external_id);const dt=iso(first(o,['completedAt','invoiceDate','orderDate','transactionDate','date','createdAt'])??ev.occurred_at);const sp=String(first(o,['salespersonId','salespersonCode','employeeId','associateId','salesperson','salesAssociateId'])??'')||null;const loc=String(first(o,['locationId','locationCode','storeId','storeCode'])??'')||null;const customer=String(first(o,['customerId','customerNumber','customerCode'])??'')||null;const lines=arr(o,['lines','lineItems','items','orderLines','salesOrderLines']);let revenue=0,cost=0,discount=0,warranty=0,delivery=0,install=0,haul=0,itemCount=0;const facts:any[]=[];
 for(let i=0;i<lines.length;i++){const l=lines[i]??{};const qty=n(first(l,['quantity','qty','orderedQuantity'])??1);const unit=n(first(l,['unitPrice','price','sellingPrice','netUnitPrice']));const amount=n(first(l,['lineTotal','extendedPrice','netAmount','amount','extendedAmount']))||(unit*qty);const uc=n(first(l,['unitCost','cost','averageCost']));const lc=n(first(l,['extendedCost','lineCost','costAmount']))||(uc*qty);const desc=String(first(l,['description','name','productDescription','itemDescription'])??'');const cat=String(first(l,['category','categoryName','productCategory','department'])??'');const brand=String(first(l,['brand','manufacturer','brandName'])??'')||null;const s=text(desc,cat,first(l,['sku','itemNumber','productCode']));const iw=is(s,/warranty|protection|extended service|service plan/),id=is(s,/delivery|freight|shipping/),ii=is(s,/install|installation/),ih=is(s,/haul|removal|take.?away/),isvc=iw||id||ii||ih||is(s,/service/);if(iw)warranty+=amount;if(id)delivery+=amount;if(ii)install+=amount;if(ih)haul+=amount;if(!isvc)itemCount+=Math.max(0,qty);revenue+=amount;cost+=lc;discount+=n(first(l,['discountAmount','lineDiscount','discount']));facts.push({l,qty,unit,amount,uc,lc,desc,cat,brand,iw,id,ii,ih,isvc,i});}
 revenue=n(first(o,['totalAmount','orderTotal','grandTotal','netTotal','subtotal']))||revenue;cost=n(first(o,['costAmount','totalCost','merchandiseCost']))||cost;discount=n(first(o,['discountAmount','totalDiscount']))||discount;const gross=revenue-cost,gp=revenue?gross/revenue*100:null;
 let storeId=c.store_id;if(loc){const {data:lm}=await db.from('platform_connector_entity_map').select('local_id,local_entity_type').eq('connection_id',cid).eq('external_entity_type','location').eq('external_id',loc).maybeSingle();if(lm?.local_entity_type==='org_location')storeId=lm.local_id;}
 const pr={organization_id:c.organization_id,store_id:storeId,pos_transaction_id:`storis:${no}`,pos_employee_id:sp,transaction_amount:revenue,transaction_date:dt,line_items:lines,warranty_items:facts.filter(x=>x.iw).map(x=>x.l),synced_at:new Date().toISOString(),source_system:'storis',source_connection_id:cid,customer_external_id:customer,salesperson_external_id:sp,currency_code:first(o,['currencyCode','currency'])??null,subtotal:revenue,discount_amount:discount,cost_amount:cost,gross_margin_amount:gross,gross_margin_pct:gp,source_payload:o};const {data:p,error:pe}=await db.from('iq_pos_transactions').upsert(pr,{onConflict:'organization_id,pos_transaction_id'}).select('id').single();if(pe)throw pe;
 for(const f of facts){const l=f.l;const mg=f.amount-f.lc;const row={organization_id:c.organization_id,transaction_id:p.id,source_connection_id:cid,external_line_id:String(first(l,['id','lineId','lineNumber','sequence'])??`${no}-${f.i}`),external_item_id:first(l,['productId','itemId','sku','itemNumber'])??null,item_number:first(l,['sku','itemNumber','productCode','modelNumber'])??null,description:f.desc||null,brand:f.brand,product_category:f.cat||null,quantity:f.qty,unit_price:f.unit,line_amount:f.amount,discount_amount:n(first(l,['discountAmount','lineDiscount','discount'])),unit_cost:f.uc||null,line_cost:f.lc||null,gross_margin_amount:mg,gross_margin_pct:f.amount?mg/f.amount*100:null,is_warranty:f.iw,is_service:f.isvc,is_delivery:f.id,is_installation:f.ii,is_haul_away:f.ih,occurred_at:dt,metadata:{source:'storis'}};const {error}=await db.from('iq_transaction_line_facts').upsert(row,{onConflict:'organization_id,transaction_id,external_line_id'});if(error)throw error;linesN++;}
 let uid=null;if(sp){const {data:mm}=await db.from('iq_pos_employee_map').select('salesperson_user_id').eq('organization_id',c.organization_id).eq('pos_employee_id',sp).eq('is_active',true).maybeSingle();uid=mm?.salesperson_user_id??null;if(uid)mapped++;}
 const sr:any={organization_id:c.organization_id,location_id:storeId,user_id:uid,transaction_date:dt.slice(0,10),item_count:Math.round(itemCount),item_value:revenue,order_total:revenue,warranty_offered:false,warranty_sold:warranty>0,warranty_value:warranty,delivery_value:delivery,install_value:install,haul_away_value:haul,invoice_number:`STORIS-${no}`,is_return:revenue<0,metadata:{source:'storis',source_connection_id:cid,pos_transaction_id:p.id,cost_amount:cost,gross_margin_amount:gross,gross_margin_pct:gp,salesperson_external_id:sp,customer_external_id:customer,storis_order_status:status}};const {data:old}=await db.from('sales_transactions').select('id').eq('organization_id',c.organization_id).eq('invoice_number',sr.invoice_number).maybeSingle();const wr=old?.id?await db.from('sales_transactions').update(sr).eq('id',old.id):await db.from('sales_transactions').insert(sr);if(wr.error)throw wr.error;processed++;
 }catch(e){failed++;errors.push({external_id:k.external_id,error:String((e as any)?.message??e)})}}
 try{await db.rpc('refresh_command_center_connector_metrics',{p_connection_id:cid});}catch(_e){}
 return json({ok:failed===0,connection_id:cid,processed,lines:linesN,mapped_reps:mapped,skipped_open_orders:skipped,failed,errors:errors.slice(0,20)});
});
