import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import { XMLParser } from "npm:fast-xml-parser@4.5.3";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const J=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const first=(o:any,ks:string[])=>{for(const k of ks){const v=o?.[k];if(v!==undefined&&v!==null&&String(v)!=='')return v}return null};
const rows=(x:any)=>Array.isArray(x)?x:Array.isArray(x?.items)?x.items:Array.isArray(x?.data)?x.data:Array.isArray(x?.results)?x.results:Array.isArray(x?.value)?x.value:[];
const join=(b:string,p:string)=>/^https?:\/\//i.test(p)?p:b.replace(/\/$/,'')+'/'+p.replace(/^\//,'');
const n=(v:any)=>Number.isFinite(Number(v))?Number(v):0;
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return J({error:'POST required'},405);
 const su=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,auth=req.headers.get('Authorization')??'';
 const uc=createClient(su,anon,{global:{headers:{Authorization:auth}}}),db=createClient(su,service);const {data:{user}}=await uc.auth.getUser();if(!user)return J({error:'unauthorized'},401);
 let b:any={};try{b=await req.json()}catch{}const cid=String(b.connection_id??'');if(!cid)return J({error:'connection_id_required'},400);
 const {data:c}=await db.from('platform_connector_connections').select('*').eq('id',cid).maybeSingle();if(!c)return J({error:'connection_not_found'},404);
 const {data:m}=await db.from('organization_members').select('role,status').eq('organization_id',c.organization_id).eq('user_id',user.id).eq('status','active').maybeSingle();if(!m||!['owner','admin','super_admin'].includes(String(m.role)))return J({error:'admin_required'},403);
 const {data:co}=await db.from('platform_connectors').select('key').eq('id',c.connector_id).single();if(co?.key!=='oracle_xstore')return J({error:'not_oracle_xstore'},400);
 const action=String(b.action??'status'),settings:any=c.settings??{},xs:any=settings.oracle_xstore??{};
 if(action==='status')return J({ok:true,connection:{id:c.id,status:c.status,auth_status:c.auth_status,last_sync_at:c.last_sync_at,last_success_at:c.last_success_at,last_error:c.last_error},configuration:{base_url:xs.base_url??null,token_url:xs.token_url??null,tenancy_id:xs.tenancy_id??null,org_id:xs.org_id??null,endpoints:xs.endpoints??{},configured:Boolean(xs.base_url&&xs.token_url)}});
 if(action==='configure'){const base=String(b.base_url??'').trim(),token=String(b.token_url??'').trim();if(!/^https:\/\//i.test(base)||!/^https:\/\//i.test(token))return J({error:'https_base_and_token_url_required'},400);const endpoints=b.endpoints&&typeof b.endpoints==='object'?b.endpoints:{};let ref=c.credential_ref;const cred={client_id:String(b.client_id??''),client_secret:String(b.client_secret??''),scope:String(b.scope??'')};if(!cred.client_id||!cred.client_secret)return J({error:'client_credentials_required'},400);if(ref){const {error}=await db.rpc('platform_update_connector_secret',{p_id:ref,p_secret:JSON.stringify(cred)});if(error)return J({error:error.message},500)}else{const {data,error}=await db.rpc('platform_store_connector_secret',{p_name:`oracle_xstore_${cid}`,p_secret:JSON.stringify(cred),p_description:`Oracle Xstore OAuth credentials for ${cid}`});if(error)return J({error:error.message},500);ref=data}
   const cfg={...settings,oracle_xstore:{base_url:base,token_url:token,tenancy_id:b.tenancy_id??null,org_id:b.org_id??'DEFAULT',api_version:b.api_version??null,endpoints,configured_at:new Date().toISOString()}};await db.from('platform_connector_connections').update({settings:cfg,credential_ref:ref,auth_status:'configured',status:'pending',updated_at:new Date().toISOString(),last_error:null}).eq('id',cid);return J({ok:true,configured:true,resources:Object.keys(endpoints)})}
 if(!c.credential_ref||!xs.base_url||!xs.token_url)return J({error:'xstore_not_configured'},409);
 const {data:sec,error:se}=await db.rpc('platform_get_connector_secret',{p_id:c.credential_ref});if(se||!sec)return J({error:'credential_read_failed'},500);const cred=JSON.parse(sec);
 async function token(){const body=new URLSearchParams({grant_type:'client_credentials',client_id:cred.client_id,client_secret:cred.client_secret});if(cred.scope)body.set('scope',cred.scope);const r=await fetch(xs.token_url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const x=await r.json().catch(()=>({}));if(!r.ok||!x.access_token)throw new Error(x.error_description||x.error||`OAuth ${r.status}`);return x.access_token as string}
 const at=await token();const hdr={Authorization:`Bearer ${at}`,Accept:'application/json, application/xml, text/xml'};
 if(action==='test'){const p=String(b.path??xs.endpoints?.locations??xs.endpoints?.transactions??'');if(!p)return J({error:'test_endpoint_required'},400);const r=await fetch(join(xs.base_url,p),{headers:hdr});if(!r.ok)return J({error:'xstore_test_failed',status:r.status},502);await db.from('platform_connector_connections').update({auth_status:'valid',last_error:null,updated_at:new Date().toISOString()}).eq('id',cid);return J({ok:true,status:r.status,content_type:r.headers.get('content-type')})}
 if(action!=='sync')return J({error:'unknown_action'},400);
 const endpointMap:any={customers:'customer',products:'product',employees:'employee',locations:'location',inventory:'inventory',prices:'price',transactions:'transaction'};const eps:any=xs.endpoints??{},requested:string[]=Array.isArray(b.resources)?b.resources:Object.keys(eps);const {data:job,error:je}=await db.from('platform_sync_jobs').insert({connection_id:cid,job_type:String(b.sync_type??'initial'),direction:'inbound',status:'running',requested_by:user.id,started_at:new Date().toISOString()}).select('id').single();if(je)return J({error:je.message},500);const stats:any={job_id:job.id,resources:{},processed:0,failed:0};
 try{for(const key of requested){const et=endpointMap[key];if(!et||!eps[key])continue;let nextUrl=join(xs.base_url,String(eps[key])),count=0,fail=0,pages=0;while(nextUrl&&pages<100){pages++;const r=await fetch(nextUrl,{headers:hdr});if(!r.ok)throw new Error(`${key} fetch failed ${r.status}`);const ct=r.headers.get('content-type')||'';let payload:any;if(ct.includes('xml')||ct.includes('text/plain')){const txt=await r.text();payload=new XMLParser({ignoreAttributes:false,attributeNamePrefix:''}).parse(txt)}else payload=await r.json();let list=rows(payload);if(!list.length&&et==='transaction'){const roots=[payload?.POSLog,payload?.posLog,payload?.Transaction,payload?.transaction].filter(Boolean);list=roots.flatMap((x:any)=>Array.isArray(x)?x:[x])}
      for(const row of list){try{const id=String(first(row,['id','transactionId','receiptId','customerId','itemId','employeeId','storeId','locationId','sku','code'])??crypto.randomUUID());const name=String(first(row,['displayName','name','description','receiptId','transactionId','code'])??id);const ir=await fetch(`${su}/functions/v1/connector-ingest`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':auth,'apikey':anon},body:JSON.stringify({connection_id:cid,external_entity_type:et,external_id:id,canonical_name:name,payload:row,occurred_at:first(row,['updatedAt','transactionDate','businessDate','date','createdAt'])??new Date().toISOString()})});if(!ir.ok)throw new Error(`ingest ${ir.status}`);if(et==='transaction'){const br=await fetch(`${su}/functions/v1/oracle-xstore-performance-bridge`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':auth,'apikey':anon},body:JSON.stringify({connection_id:cid,payload:row})});if(!br.ok)throw new Error(`performance ${br.status}`)}count++;}catch{fail++;}}
      const nx=payload?.nextLink??payload?.next??payload?.links?.next??payload?.['@odata.nextLink'];nextUrl=nx?join(xs.base_url,String(nx)):''}
    stats.resources[key]={processed:count,failed:fail,pages};stats.processed+=count;stats.failed+=fail}
   const done=new Date().toISOString(),status=stats.failed?'partial':'success';await db.from('platform_sync_jobs').update({status,completed_at:done,stats,error_details:stats.failed?{message:`${stats.failed} records failed`}:null}).eq('id',job.id);await db.from('platform_connector_connections').update({status:'active',auth_status:'valid',last_sync_at:done,last_success_at:status==='success'?done:c.last_success_at,last_error:stats.failed?`${stats.failed} records failed`:null,initial_sync_completed_at:done,initial_sync_stats:stats,updated_at:done}).eq('id',cid);return J({ok:true,status,...stats})
 }catch(e){const msg=String((e as any)?.message??e);await db.from('platform_sync_jobs').update({status:'failed',completed_at:new Date().toISOString(),stats,error_details:{message:msg}}).eq('id',job.id);await db.from('platform_connector_connections').update({last_sync_at:new Date().toISOString(),last_error:msg,updated_at:new Date().toISOString()}).eq('id',cid);return J({error:'xstore_sync_failed',detail:msg,stats},502)}});
