-- Read-only post-execution report. Compare snapshots to pre_migration_verification.sql output.
WITH expected_columns(table_name, column_name, expected_type, expected_nullable, expected_default) AS (
  VALUES
    ('mfr_members','role','text','YES',NULL), ('mfr_members','status','text','YES',NULL), ('mfr_members','invited_by','uuid','YES',NULL), ('mfr_members','approved_by','uuid','YES',NULL), ('mfr_members','invitation_id','uuid','YES',NULL), ('mfr_members','approved_at','timestamp with time zone','YES',NULL), ('mfr_members','activated_at','timestamp with time zone','YES',NULL), ('mfr_members','suspended_at','timestamp with time zone','YES',NULL), ('mfr_members','revoked_at','timestamp with time zone','YES',NULL), ('mfr_members','expires_at','timestamp with time zone','YES',NULL), ('mfr_members','updated_at','timestamp with time zone','YES',NULL), ('mfr_members','created_by','uuid','YES',NULL), ('mfr_members','updated_by','uuid','YES',NULL), ('mfr_members','metadata','jsonb','NO','{}'::jsonb),
    ('mfr_invites','vendor_id','uuid','YES',NULL), ('mfr_invites','invited_user_id','uuid','YES',NULL), ('mfr_invites','intended_role','text','YES',NULL), ('mfr_invites','intended_status','text','YES',NULL), ('mfr_invites','approved_by','uuid','YES',NULL), ('mfr_invites','token_hash','text','YES',NULL), ('mfr_invites','token_version','integer','NO','1'), ('mfr_invites','expires_at','timestamp with time zone','YES',NULL), ('mfr_invites','accepted_by','uuid','YES',NULL), ('mfr_invites','revoked_at','timestamp with time zone','YES',NULL), ('mfr_invites','revoked_by','uuid','YES',NULL), ('mfr_invites','superseded_by','uuid','YES',NULL), ('mfr_invites','metadata','jsonb','NO','{}'::jsonb)
), actual_columns AS (
  SELECT table_name,column_name,data_type,is_nullable,regexp_replace(coalesce(column_default,''), '\s+', '', 'g') AS column_default
  FROM information_schema.columns WHERE table_schema='public'
), expected_indexes(indexname) AS (VALUES ('mfr_members_invitation_id_idx'),('mfr_members_vendor_status_idx'),('mfr_invites_vendor_id_idx'),('mfr_invites_invited_user_id_idx')),
current_counts AS (
  SELECT 'mfr_members'::text AS table_name, count(*)::bigint AS actual_rows FROM public.mfr_members
  UNION ALL SELECT 'mfr_invites', count(*) FROM public.mfr_invites
  UNION ALL SELECT 'mfr_user_roles', count(*) FROM public.mfr_user_roles
  UNION ALL SELECT 'mfr_vendors', count(*) FROM public.mfr_vendors
)
SELECT jsonb_build_object(
  'column_mismatches', (SELECT coalesce(jsonb_agg(jsonb_build_object('table',e.table_name,'column',e.column_name,'expected_type',e.expected_type,'actual_type',a.data_type,'expected_nullable',e.expected_nullable,'actual_nullable',a.is_nullable,'actual_default',a.column_default) ORDER BY e.table_name,e.column_name) FILTER (WHERE a.column_name IS NULL OR a.data_type<>e.expected_type OR a.is_nullable<>e.expected_nullable OR (e.expected_default IS NOT NULL AND a.column_default<>regexp_replace(e.expected_default, '\s+', '', 'g'))), '[]'::jsonb) FROM expected_columns e LEFT JOIN actual_columns a USING (table_name,column_name)),
  'missing_indexes', (SELECT coalesce(jsonb_agg(e.indexname ORDER BY e.indexname) FILTER (WHERE i.indexname IS NULL),'[]'::jsonb) FROM expected_indexes e LEFT JOIN pg_indexes i ON i.schemaname='public' AND i.indexname=e.indexname),
  'new_foreign_keys', (SELECT coalesce(jsonb_agg(c.conname ORDER BY c.conname) FILTER (WHERE c.conname IN ('mfr_members_invited_by_fkey','mfr_members_approved_by_fkey','mfr_members_invitation_id_fkey','mfr_members_created_by_fkey','mfr_members_updated_by_fkey','mfr_invites_vendor_id_fkey','mfr_invites_invited_user_id_fkey','mfr_invites_approved_by_fkey','mfr_invites_accepted_by_fkey','mfr_invites_revoked_by_fkey','mfr_invites_superseded_by_fkey')),'[]'::jsonb) FROM pg_constraint c WHERE c.conrelid IN ('public.mfr_members'::regclass,'public.mfr_invites'::regclass) AND c.contype='f'),
  'constraint_snapshot', (SELECT jsonb_agg(jsonb_build_object('table',r.relname,'name',c.conname,'type',c.contype,'definition',pg_get_constraintdef(c.oid)) ORDER BY r.relname,c.conname) FROM pg_constraint c JOIN pg_class r ON r.oid=c.conrelid JOIN pg_namespace n ON n.oid=r.relnamespace WHERE n.nspname='public' AND r.relname IN ('mfr_members','mfr_invites','mfr_user_roles','mfr_vendors')),
  'index_snapshot', (SELECT jsonb_agg(jsonb_build_object('table',tablename,'name',indexname,'definition',indexdef) ORDER BY tablename,indexname) FROM pg_indexes WHERE schemaname='public' AND tablename IN ('mfr_members','mfr_invites','mfr_user_roles','mfr_vendors')),
  'rows', (SELECT jsonb_object_agg(table_name,actual_rows) FROM current_counts),
  'rls_snapshot', (SELECT jsonb_agg(jsonb_build_object('table',tablename,'enabled',rowsecurity) ORDER BY tablename) FROM pg_tables WHERE schemaname='public' AND tablename IN ('mfr_members','mfr_invites','mfr_user_roles','mfr_vendors')),
  'policy_snapshot', (SELECT jsonb_agg(jsonb_build_object('table',tablename,'name',policyname,'command',cmd) ORDER BY tablename,policyname) FROM pg_policies WHERE schemaname='public' AND tablename IN ('mfr_members','mfr_invites','mfr_user_roles','mfr_vendors')),
  'trigger_snapshot', (SELECT coalesce(jsonb_agg(jsonb_build_object('table',event_object_table,'name',trigger_name) ORDER BY event_object_table,trigger_name),'[]'::jsonb) FROM information_schema.triggers WHERE trigger_schema='public' AND event_object_table IN ('mfr_members','mfr_invites')),
  'manual_comparisons_required', 'Compare pre/post constraint and index snapshots to prove no unique/check/FK additions beyond the approved four indexes. Compare RLS, policies, helpers, Storage, application behavior, and migration history outside this read-only script.'
) AS post_migration_report;
