-- Phase 3 connected intelligence core. Applied to production 2026-08-13.
alter table public.intelligence_events add column if not exists subject_entity_type text;
alter table public.intelligence_events add column if not exists store_id uuid;
alter table public.intelligence_events add column if not exists event_version integer not null default 1;
alter table public.intelligence_events add column if not exists dedupe_key text;
alter table public.intelligence_events add column if not exists processing_status text not null default 'ready';
alter table public.intelligence_events add column if not exists identity_confidence numeric;
alter table public.intelligence_events add column if not exists metadata jsonb not null default '{}'::jsonb;
create unique index if not exists ux_intelligence_events_dedupe on public.intelligence_events(organization_id,source_system,dedupe_key) where dedupe_key is not null;
create index if not exists idx_intelligence_events_org_time on public.intelligence_events(organization_id,occurred_at desc);
create index if not exists idx_intelligence_events_type_time on public.intelligence_events(event_type,occurred_at desc);
create index if not exists idx_intelligence_events_store_time on public.intelligence_events(store_id,occurred_at desc) where store_id is not null;

insert into public.platform_canonical_entity_types(key,name,description,intelligence_entity_type,active,metadata) values
('interaction','Customer Interaction','Retail customer interaction / UP lifecycle','interaction',true,'{}'),
('learning','Learning Activity','Academy learning and assessment activity','learning',true,'{}'),
('field_visit','Field Visit','Field execution and store assessment activity','field_visit',true,'{}') on conflict(key) do nothing;
insert into public.platform_canonical_event_types(key,name,description,subject_entity_type,outcome_relevant,coaching_relevant,active,metadata) values
('traffic.observed','Traffic Observed','Store traffic/counter observation','store',false,true,true,'{}'),
('interaction.started','Interaction Started','Salesperson accepted or began a customer interaction','interaction',false,true,true,'{}'),
('interaction.completed','Interaction Completed','Customer interaction ended with a recorded outcome','interaction',true,true,true,'{}'),
('interaction.no_sale','Interaction No Sale','Customer interaction ended without a purchase','interaction',true,true,true,'{}'),
('learning.progressed','Learning Progressed','Academy learning activity progressed','learning',false,true,true,'{}'),
('learning.completed','Learning Completed','Academy learning activity completed','learning',true,true,true,'{}'),
('field.score_recorded','Field Score Recorded','Field store score recorded','field_visit',true,false,true,'{}') on conflict(key) do nothing;

create table if not exists public.platform_identity_links(
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
 entity_type text not null, canonical_id uuid not null, canonical_table text not null, source_system text not null, source_table text not null,
 source_record_id text not null, external_id text, display_name text, confidence numeric not null default 1.0 check(confidence>=0 and confidence<=1),
 match_method text not null default 'native', is_primary boolean not null default false, verified_at timestamptz,
 first_seen_at timestamptz not null default now(), last_seen_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb,
 unique(organization_id,entity_type,source_system,source_table,source_record_id));
alter table public.platform_identity_links enable row level security;
create index if not exists idx_identity_links_canonical on public.platform_identity_links(organization_id,entity_type,canonical_id);
create index if not exists idx_identity_links_external on public.platform_identity_links(organization_id,entity_type,source_system,external_id) where external_id is not null;
revoke all on public.platform_identity_links from anon,authenticated; grant all on public.platform_identity_links to service_role;

create table if not exists public.platform_intelligence_unresolved_events(
 id uuid primary key default gen_random_uuid(), source_system text not null, source_table text not null, source_record_id text not null,
 event_type text not null, reason text not null, candidate_organization_ids uuid[] not null default '{}', payload jsonb not null default '{}'::jsonb,
 status text not null default 'open' check(status in ('open','resolved','ignored')), created_at timestamptz not null default now(), resolved_at timestamptz,
 metadata jsonb not null default '{}'::jsonb, unique(source_system,source_table,source_record_id,event_type,status));
alter table public.platform_intelligence_unresolved_events enable row level security;
revoke all on public.platform_intelligence_unresolved_events from anon,authenticated; grant all on public.platform_intelligence_unresolved_events to service_role;

create or replace function public.platform_upsert_identity_link(p_organization_id uuid,p_entity_type text,p_canonical_id uuid,p_canonical_table text,p_source_system text,p_source_table text,p_source_record_id text,p_external_id text default null,p_display_name text default null,p_confidence numeric default 1,p_match_method text default 'native',p_is_primary boolean default false,p_metadata jsonb default '{}'::jsonb)
returns uuid language plpgsql security definer set search_path=public as $$ declare v_id uuid; begin
 if not exists(select 1 from public.platform_canonical_entity_types where key=p_entity_type and active=true) then raise exception 'unknown_entity_type:%',p_entity_type; end if;
 insert into public.platform_identity_links(organization_id,entity_type,canonical_id,canonical_table,source_system,source_table,source_record_id,external_id,display_name,confidence,match_method,is_primary,metadata,last_seen_at)
 values(p_organization_id,p_entity_type,p_canonical_id,p_canonical_table,p_source_system,p_source_table,p_source_record_id,p_external_id,p_display_name,least(greatest(coalesce(p_confidence,1),0),1),coalesce(p_match_method,'native'),coalesce(p_is_primary,false),coalesce(p_metadata,'{}'::jsonb),now())
 on conflict(organization_id,entity_type,source_system,source_table,source_record_id) do update set canonical_id=excluded.canonical_id,canonical_table=excluded.canonical_table,external_id=coalesce(excluded.external_id,platform_identity_links.external_id),display_name=coalesce(excluded.display_name,platform_identity_links.display_name),confidence=excluded.confidence,match_method=excluded.match_method,is_primary=excluded.is_primary,metadata=platform_identity_links.metadata||excluded.metadata,last_seen_at=now() returning id into v_id; return v_id; end $$;
revoke all on function public.platform_upsert_identity_link(uuid,text,uuid,text,text,text,text,text,text,numeric,text,boolean,jsonb) from public,anon,authenticated; grant execute on function public.platform_upsert_identity_link(uuid,text,uuid,text,text,text,text,text,text,numeric,text,boolean,jsonb) to service_role;

-- Initial emitter is superseded by 20260813010808_phase3_intelligence_entity_envelope_fix.sql.

create or replace function public.phase3_publish_contact_event() returns trigger language plpgsql security definer set search_path=public as $$ declare ev text; label text; begin ev:=case when tg_op='INSERT' then 'customer.created' else 'customer.updated' end; label:=trim(coalesce(new.preferred_name,'')||' '||coalesce(new.first_name,'')||' '||coalesce(new.last_name,'')); perform public.platform_upsert_identity_link(new.organization_id,'customer',new.id,'contacts','crm','contacts',new.id::text,coalesce(new.email,new.phone),nullif(label,''),1,'native',true,jsonb_build_object('lifecycle_stage',new.lifecycle_stage)); perform public.platform_emit_intelligence_event(new.organization_id,ev,'crm',new.id::text,'customer',new.id,null,new.assigned_salesperson_id,null,null,ev||':'||new.id::text||':'||coalesce(new.updated_at,new.created_at)::text,jsonb_build_object('contact_id',new.id,'lifecycle_stage',new.lifecycle_stage,'assigned_salesperson_id',new.assigned_salesperson_id),coalesce(new.updated_at,new.created_at),1,'{}'); return new; end $$;
revoke all on function public.phase3_publish_contact_event() from public,anon,authenticated; drop trigger if exists trg_phase3_contact_event on public.contacts; create trigger trg_phase3_contact_event after insert or update of first_name,last_name,preferred_name,email,phone,lifecycle_stage,assigned_salesperson_id on public.contacts for each row execute function public.phase3_publish_contact_event();

create or replace function public.phase3_publish_product_event() returns trigger language plpgsql security definer set search_path=public as $$ declare ev text; cid uuid; label text; begin ev:=case when tg_op='INSERT' then 'product.created' else 'product.updated' end; cid:=coalesce(new.aiq_product_id,new.id); label:=trim(coalesce(new.brand,'')||' '||coalesce(new.model,'')||' '||coalesce(new.name,'')); perform public.platform_upsert_identity_link(new.organization_id,'product',cid,'products','product_iq','products',new.id::text,new.model,nullif(label,''),case when new.aiq_product_id is null then .9 else 1 end,case when new.aiq_product_id is null then 'local_product' else 'aiq_product_id' end,true,jsonb_build_object('local_product_id',new.id,'category',new.category)); perform public.platform_emit_intelligence_event(new.organization_id,ev,'product_iq',new.id::text,'product',cid,null,null,null,null,ev||':'||new.id::text||':'||coalesce(new.updated_at,new.created_at)::text,jsonb_build_object('product_id',new.id,'aiq_product_id',new.aiq_product_id,'brand',new.brand,'model',new.model,'category',new.category,'msrp',new.msrp,'in_stock',new.in_stock),coalesce(new.updated_at,new.created_at),case when new.aiq_product_id is null then .9 else 1 end,'{}'); return new; end $$;
revoke all on function public.phase3_publish_product_event() from public,anon,authenticated; drop trigger if exists trg_phase3_product_event on public.products; create trigger trg_phase3_product_event after insert or update of brand,model,name,category,msrp,cost,in_stock,aiq_product_id on public.products for each row execute function public.phase3_publish_product_event();

create or replace function public.phase3_publish_store_event() returns trigger language plpgsql security definer set search_path=public as $$ begin perform public.platform_upsert_identity_link(new.organization_id,'store',new.id,'org_locations','platform','org_locations',new.id::text,new.code,new.name,1,'native',true,jsonb_build_object('location_type',new.location_type)); if tg_op='UPDATE' then perform public.platform_emit_intelligence_event(new.organization_id,'store.updated','platform',new.id::text,'store',new.id,new.id,null,null,null,'store.updated:'||new.id::text||':'||new.updated_at::text,jsonb_build_object('name',new.name,'code',new.code,'location_type',new.location_type,'is_active',new.is_active),new.updated_at,1,'{}'); end if; return new; end $$;
revoke all on function public.phase3_publish_store_event() from public,anon,authenticated; drop trigger if exists trg_phase3_store_event on public.org_locations; create trigger trg_phase3_store_event after insert or update of name,code,location_type,is_active,address,city,province_state,country on public.org_locations for each row execute function public.phase3_publish_store_event();

create or replace function public.phase3_publish_pos_event() returns trigger language plpgsql security definer set search_path=public as $$ declare ev text; emp uuid; conf numeric:=null; begin ev:=case when coalesce(new.transaction_amount,0)<0 then 'transaction.refunded' else 'transaction.completed' end; select salesperson_user_id into emp from public.iq_pos_employee_map where organization_id=new.organization_id and pos_system=coalesce(new.source_system,pos_system) and pos_employee_id=coalesce(new.salesperson_external_id,new.pos_employee_id) and is_active=true order by updated_at desc limit 1; if emp is not null then conf:=1; perform public.platform_upsert_identity_link(new.organization_id,'employee',emp,'auth.users',coalesce(new.source_system,'pos'),'iq_pos_employee_map',coalesce(new.salesperson_external_id,new.pos_employee_id,emp::text),coalesce(new.salesperson_external_id,new.pos_employee_id),null,1,'pos_employee_map',false,'{}'); end if; perform public.platform_emit_intelligence_event(new.organization_id,ev,coalesce(new.source_system,'pos'),new.pos_transaction_id,'transaction',new.id,new.store_id,emp,null,null,ev||':'||coalesce(new.source_system,'pos')||':'||new.pos_transaction_id,jsonb_build_object('transaction_id',new.id,'pos_transaction_id',new.pos_transaction_id,'amount',new.transaction_amount,'subtotal',new.subtotal,'discount_amount',new.discount_amount,'gross_margin_amount',new.gross_margin_amount,'gross_margin_pct',new.gross_margin_pct,'currency_code',new.currency_code,'customer_external_id',new.customer_external_id,'salesperson_external_id',coalesce(new.salesperson_external_id,new.pos_employee_id),'line_items',new.line_items,'warranty_items',new.warranty_items),coalesce(new.transaction_date,new.created_at),conf,jsonb_build_object('source_connection_id',new.source_connection_id)); return new; end $$;
revoke all on function public.phase3_publish_pos_event() from public,anon,authenticated; drop trigger if exists trg_phase3_pos_event on public.iq_pos_transactions; create trigger trg_phase3_pos_event after insert on public.iq_pos_transactions for each row execute function public.phase3_publish_pos_event();

create or replace function public.phase3_publish_traffic_event() returns trigger language plpgsql security definer set search_path=public as $$ begin perform public.platform_emit_intelligence_event(new.organization_id,'traffic.observed','up_system',new.id::text,'store',new.store_id,new.store_id,new.created_by,null,null,'traffic.observed:'||new.id::text,jsonb_build_object('raw_entries',new.raw_entries,'adjusted_entries',new.adjusted_entries,'customer_groups',new.customer_groups,'traffic_source_id',new.traffic_source_id),new.captured_at,1,'{}'); return new; end $$;
revoke all on function public.phase3_publish_traffic_event() from public,anon,authenticated; drop trigger if exists trg_phase3_traffic_event on public.iq_traffic_events; create trigger trg_phase3_traffic_event after insert on public.iq_traffic_events for each row execute function public.phase3_publish_traffic_event();

create or replace function public.phase3_publish_interaction_event() returns trigger language plpgsql security definer set search_path=public as $$ declare ev text; begin if tg_op='INSERT' then ev:='interaction.started'; elsif new.ended_at is not null and (old.ended_at is distinct from new.ended_at or old.outcome is distinct from new.outcome) then ev:=case when coalesce(new.sale_amount,0)>0 or lower(coalesce(new.outcome,'')) in ('closed','sale','sold','purchased') then 'interaction.completed' else 'interaction.no_sale' end; else return new; end if; perform public.platform_emit_intelligence_event(new.organization_id,ev,'up_system',new.id::text,'interaction',new.id,new.store_id,new.salesperson_user_id,null,null,ev||':'||new.id::text||':'||coalesce(new.ended_at,new.started_at,new.created_at)::text,jsonb_build_object('interaction_id',new.id,'contact_id',new.contact_id,'salesperson_user_id',new.salesperson_user_id,'outcome',new.outcome,'sale_amount',new.sale_amount,'reason_not_purchased',new.reason_not_purchased,'no_sale_reason',new.no_sale_reason,'pos_transaction_id',new.pos_transaction_id,'pos_matched',new.pos_matched),coalesce(new.ended_at,new.started_at,new.created_at),case when new.contact_id is null then .5 else 1 end,'{}'); return new; end $$;
revoke all on function public.phase3_publish_interaction_event() from public,anon,authenticated; drop trigger if exists trg_phase3_interaction_event on public.iq_customer_interactions; create trigger trg_phase3_interaction_event after insert or update of ended_at,outcome,sale_amount,pos_matched,pos_transaction_id on public.iq_customer_interactions for each row execute function public.phase3_publish_interaction_event();

create or replace function public.phase3_publish_academy_event() returns trigger language plpgsql security definer set search_path=public as $$ declare orgs uuid[]; org_count int; org_id uuid; ev text; begin select array_agg(organization_id),count(*) into orgs,org_count from public.organization_members where user_id=new.user_id and status='active'; ev:=case when lower(new.event_type) like '%complet%' then 'learning.completed' else 'learning.progressed' end; if org_count=1 then org_id:=orgs[1]; perform public.platform_upsert_identity_link(org_id,'employee',new.user_id,'auth.users','academy','academy_learning_events',new.user_id::text,new.user_id::text,null,1,'auth_user',false,'{}'); perform public.platform_emit_intelligence_event(org_id,ev,'academy',new.id::text,'learning',new.user_id,null,new.user_id,null,null,ev||':'||new.id::text,jsonb_build_object('academy_event_id',new.id,'user_id',new.user_id,'event_type',new.event_type,'pillar',new.pillar,'course_key',new.course_key,'content',new.content,'metadata',new.metadata),new.created_at,1,'{}'); else insert into public.platform_intelligence_unresolved_events(source_system,source_table,source_record_id,event_type,reason,candidate_organization_ids,payload) values('academy','academy_learning_events',new.id::text,ev,case when org_count=0 then 'organization_not_found' else 'ambiguous_organization' end,coalesce(orgs,'{}'),jsonb_build_object('user_id',new.user_id,'event_type',new.event_type,'course_key',new.course_key)) on conflict do nothing; end if; return new; end $$;
revoke all on function public.phase3_publish_academy_event() from public,anon,authenticated; drop trigger if exists trg_phase3_academy_event on public.academy_learning_events; create trigger trg_phase3_academy_event after insert on public.academy_learning_events for each row execute function public.phase3_publish_academy_event();

create or replace function public.phase3_publish_field_score_event() returns trigger language plpgsql security definer set search_path=public as $$ declare org_id uuid; loc_id uuid; begin select ol.organization_id,fs.org_location_id into org_id,loc_id from public.field_stores fs left join public.org_locations ol on ol.id=fs.org_location_id where fs.id=new.store_id; if org_id is null then insert into public.platform_intelligence_unresolved_events(source_system,source_table,source_record_id,event_type,reason,payload) values('field','field_store_scores',new.id::text,'field.score_recorded','organization_not_found',jsonb_build_object('field_store_id',new.store_id,'overall_score',new.overall_score)) on conflict do nothing; return new; end if; perform public.platform_emit_intelligence_event(org_id,'field.score_recorded','field',new.id::text,'field_visit',new.visit_id,loc_id,null,null,null,'field.score_recorded:'||new.id::text,jsonb_build_object('score_id',new.id,'visit_id',new.visit_id,'field_store_id',new.store_id,'overall_score',new.overall_score,'score_date',new.score_date),new.created_at,1,'{}'); return new; end $$;
revoke all on function public.phase3_publish_field_score_event() from public,anon,authenticated; drop trigger if exists trg_phase3_field_score_event on public.field_store_scores; create trigger trg_phase3_field_score_event after insert on public.field_store_scores for each row execute function public.phase3_publish_field_score_event();

-- Existing identity seed.
insert into public.platform_identity_links(organization_id,entity_type,canonical_id,canonical_table,source_system,source_table,source_record_id,external_id,display_name,confidence,match_method,is_primary,metadata) select c.organization_id,'customer',c.id,'contacts','crm','contacts',c.id::text,coalesce(c.email,c.phone),nullif(trim(coalesce(c.preferred_name,'')||' '||coalesce(c.first_name,'')||' '||coalesce(c.last_name,'')),''),1,'native',true,jsonb_build_object('seeded',true) from public.contacts c where c.organization_id is not null on conflict do nothing;
insert into public.platform_identity_links(organization_id,entity_type,canonical_id,canonical_table,source_system,source_table,source_record_id,external_id,display_name,confidence,match_method,is_primary,metadata) select p.organization_id,'product',coalesce(p.aiq_product_id,p.id),'products','product_iq','products',p.id::text,p.model,nullif(trim(coalesce(p.brand,'')||' '||coalesce(p.model,'')||' '||coalesce(p.name,'')),''),case when p.aiq_product_id is null then .9 else 1 end,case when p.aiq_product_id is null then 'local_product' else 'aiq_product_id' end,true,jsonb_build_object('seeded',true,'local_product_id',p.id) from public.products p where p.organization_id is not null on conflict do nothing;
insert into public.platform_identity_links(organization_id,entity_type,canonical_id,canonical_table,source_system,source_table,source_record_id,external_id,display_name,confidence,match_method,is_primary,metadata) select l.organization_id,'store',l.id,'org_locations','platform','org_locations',l.id::text,l.code,l.name,1,'native',true,jsonb_build_object('seeded',true,'location_type',l.location_type) from public.org_locations l on conflict do nothing;
insert into public.platform_identity_links(organization_id,entity_type,canonical_id,canonical_table,source_system,source_table,source_record_id,external_id,display_name,confidence,match_method,is_primary,metadata) select m.organization_id,'employee',m.salesperson_user_id,'auth.users',coalesce(m.pos_system,'pos'),'iq_pos_employee_map',m.id::text,m.pos_employee_id,m.display_name,1,'pos_employee_map',false,jsonb_build_object('seeded',true,'store_id',m.store_id) from public.iq_pos_employee_map m where m.salesperson_user_id is not null on conflict do nothing;