-- =============================================================================
-- HISTORICAL MARKER — phase_7_aicrm_enrichment_framework_recovery
-- Version: 20260720141106
-- Applied to production: yes (via MCP, original SQL not preserved in version control)
-- Original SQL: UNAVAILABLE — applied interactively, not recoverable
-- Domain: AI CRM enrichment
-- Objects created: aicrm_ai_enrichment_jobs, aicrm_enrichment_runs, aicrm_ai_profiles, aicrm_ai_research, aicrm_account_custom_fields, aicrm_account_custom_field_values
-- Current schema reference: Query production with information_schema or pg_catalog
-- Execute in new environment: NO — this file contains no DDL
-- Execute against production: NO — already applied
-- 
-- This file exists solely to align the repository migration history with
-- supabase_migrations.schema_migrations in production. It does NOT recreate
-- the objects listed above. A separate baseline migration or manual schema
-- export is required to reproduce these objects in a new environment.
-- =============================================================================
