CREATE OR REPLACE FUNCTION tj_private.epass_performance_bridge(p_body jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
<<bridge>>
DECLARE conn tj.platform_connector_connections%rowtype;actor uuid:=tj_private.current_source_user_id();prof tj.platform_connector_onboarding_profiles%rowtype;
 rec record;inv jsonb;raw_lines jsonb;line jsonb;facts jsonb;f jsonb;warranty_lines jsonb;event_id uuid;tx_id uuid;sales_id uuid;store uuid;person uuid;
 external text;invoice_no text;employee_code text;location_code text;customer text;currency text;tx_key text;line_id text;seen_ids text[];date_text text;dt timestamptz;
 qty numeric;unit numeric;amount numeric;unit_cost numeric;line_cost numeric;line_discount numeric;revenue numeric;cost numeric;discount numeric;units numeric;warranty numeric;delivery numeric;install numeric;haul numeric;
 desc_text text;category text;brand text;classifier text;iw boolean;idel boolean;iinst boolean;ihaul boolean;isvc boolean;candidate_count integer;idx integer;
 page_limit integer:=coalesce((p_body->>'limit')::integer,25);after_external text:=p_body->>'after_external_id';next_external text;processed integer:=0;failed integer:=0;lines_n integer:=0;mapped_n integer:=0;scanned integer:=0;state text;errors jsonb:='[]';has_more boolean;
BEGIN
 IF p_body IS NULL OR jsonb_typeof(p_body)<>'object' OR octet_length(p_body::text)>8192 OR EXISTS(SELECT 1 FROM jsonb_object_keys(p_body)k WHERE k NOT IN('connection_id','limit','after_external_id')) OR page_limit NOT BETWEEN 1 AND 100 OR length(coalesce(after_external,''))>500 THEN RAISE EXCEPTION 'invalid_request' USING ERRCODE='22023';END IF;
 conn:=tj_private.epass_connection(nullif(p_body->>'connection_id','')::uuid,actor);
 IF conn.status IN('paused','disconnected') THEN RAISE EXCEPTION 'connection_not_ready' USING ERRCODE='40001';END IF;
 SELECT * INTO prof FROM tj.platform_connector_onboarding_profiles p WHERE p.connector_id=conn.connector_id AND p.variant_id IS NOT DISTINCT FROM conn.variant_id AND p.is_active;
 IF NOT FOUND THEN RAISE EXCEPTION 'onboarding_profile_required' USING ERRCODE='40001';END IF;
 -- The stable cursor is the external invoice identity; never iterate every historical payload hash.
 FOR rec IN SELECT DISTINCT k.external_id FROM tj.platform_connector_ingestion_keys k WHERE k.connection_id=conn.id AND k.external_entity_type='invoice' AND k.intelligence_event_id IS NOT NULL AND (after_external IS NULL OR k.external_id>after_external) ORDER BY k.external_id LIMIT page_limit LOOP
  external:=rec.external_id;next_external:=external;scanned:=scanned+1;
  BEGIN
   SELECT ev.id,ev.payload,ev.occurred_at INTO event_id,inv,dt FROM tj.platform_connector_ingestion_keys k JOIN tj.intelligence_events ev ON ev.id=k.intelligence_event_id WHERE k.connection_id=conn.id AND k.external_entity_type='invoice' AND k.external_id=external ORDER BY ev.created_at DESC,ev.id DESC,k.first_seen_at DESC,k.id DESC LIMIT 1;
   IF event_id IS NULL OR NOT EXISTS(SELECT 1 FROM tj.intelligence_events e WHERE e.id=event_id AND e.organization_id=conn.organization_id AND e.payload->>'connector_connection_id'=conn.id::text AND e.payload->>'external_id'=external) OR jsonb_typeof(inv)<>'object' OR octet_length(inv::text)>262144 THEN RAISE EXCEPTION 'invalid_invoice_event_scope' USING ERRCODE='42501';END IF;
   invoice_no:=coalesce(tj_private.onboarding_field(inv,ARRAY['invoice_number','invoiceNumber','number','invoice_id','invoiceId','id']),external);
   date_text:=tj_private.onboarding_field(inv,ARRAY['invoice_date','invoiceDate','posting_date','postingDate','date','created_at','createdAt']);IF date_text IS NOT NULL THEN dt:=date_text::timestamptz;END IF;
   IF dt IS NULL OR NOT isfinite(dt) OR dt<'1900-01-01'::timestamptz OR dt>clock_timestamp()+interval '1 day' THEN RAISE EXCEPTION 'invalid_invoice_date' USING ERRCODE='22023';END IF;
   employee_code:=tj_private.onboarding_field(inv,ARRAY['salesperson_id','salespersonId','employee_id','employeeId','salesperson_code','salespersonCode']);location_code:=tj_private.onboarding_field(inv,ARRAY['location_id','locationId','store_id','storeId','store_code','storeCode']);customer:=tj_private.onboarding_field(inv,ARRAY['customer_id','customerId','customer_number','customerNumber']);currency:=tj_private.onboarding_field(inv,ARRAY['currency','currency_code','currencyCode']);IF currency IS NOT NULL AND currency!~'^[A-Z]{3}$' THEN RAISE EXCEPTION 'invalid_currency' USING ERRCODE='22023';END IF;
   store:=conn.store_id;
   IF location_code IS NOT NULL THEN
    SELECT count(DISTINCT m.local_id),min(m.local_id::text)::uuid INTO candidate_count,store FROM tj.platform_connector_entity_map m JOIN tj.org_locations l ON l.id=m.local_id AND l.organization_id=conn.organization_id AND l.is_active WHERE m.connection_id=conn.id AND m.external_entity_type=ANY(prof.location_entity_types) AND m.external_id=location_code AND m.local_entity_type='org_location' AND m.metadata->>'us_onboarding_reviewed'='true';
    IF store IS NULL OR candidate_count<>1 THEN RAISE EXCEPTION 'location_review_required' USING ERRCODE='42501';END IF;
   END IF;
   person:=NULL;
   IF employee_code IS NOT NULL THEN
    SELECT count(DISTINCT m.salesperson_user_id),min(m.salesperson_user_id::text)::uuid INTO candidate_count,person FROM tj.iq_pos_employee_map m JOIN tj.platform_connector_match_queue q ON q.connection_id=conn.id AND q.organization_id=conn.organization_id AND q.external_entity_type='employee' AND coalesce(nullif(q.external_code,''),q.external_id)=employee_code AND q.candidate_id=m.salesperson_user_id AND q.status='confirmed' AND q.metadata->>'us_onboarding_reviewed'='true' JOIN tj.organization_members om ON om.organization_id=conn.organization_id AND om.user_id=m.salesperson_user_id AND om.status='active' WHERE m.organization_id=conn.organization_id AND m.pos_system=prof.pos_system_key AND m.pos_employee_id=employee_code AND m.is_active AND (m.store_id IS NULL OR m.store_id=store);
    IF candidate_count>1 THEN RAISE EXCEPTION 'ambiguous_employee_mapping' USING ERRCODE='42501';END IF;
   END IF;
   raw_lines:=coalesce(inv->'items',inv->'lines',inv->'line_items',inv->'lineItems',inv->'invoiceLines');IF jsonb_typeof(raw_lines) IS DISTINCT FROM 'array' OR jsonb_array_length(raw_lines) NOT BETWEEN 1 AND 200 THEN RAISE EXCEPTION 'invoice_lines_required' USING ERRCODE='22023';END IF;
   revenue:=0;cost:=0;discount:=0;units:=0;warranty:=0;delivery:=0;install:=0;haul:=0;facts:='[]';warranty_lines:='[]';idx:=0;seen_ids:=ARRAY[]::text[];
   FOR line IN SELECT value FROM jsonb_array_elements(raw_lines) LOOP
    IF jsonb_typeof(line)<>'object' THEN RAISE EXCEPTION 'invalid_invoice_line' USING ERRCODE='22023';END IF;
    qty:=coalesce(tj_private.epass_number(line,ARRAY['quantity','qty']),1);unit:=tj_private.epass_number(line,ARRAY['unit_price','unitPrice','price','retail_price','retailPrice']);amount:=coalesce(tj_private.epass_number(line,ARRAY['line_total','lineTotal','extended_price','extendedPrice','net_amount','netAmount','amount']),unit*qty);unit_cost:=tj_private.epass_number(line,ARRAY['unit_cost','unitCost','cost']);line_cost:=coalesce(tj_private.epass_number(line,ARRAY['line_cost','lineCost','extended_cost','extendedCost','cost_amount','costAmount']),unit_cost*qty);line_discount:=coalesce(tj_private.epass_number(line,ARRAY['discount_amount','discountAmount','discount']),0);
    IF amount IS NULL OR abs(amount)>1000000000 THEN RAISE EXCEPTION 'line_amount_required' USING ERRCODE='22023';END IF;
    -- Missing cost stays unknown; explicit zero remains zero.
    desc_text:=tj_private.onboarding_field(line,ARRAY['description','name','model_description','modelDescription']);category:=tj_private.onboarding_field(line,ARRAY['category','category_name','categoryName','product_category','productCategory']);brand:=tj_private.onboarding_field(line,ARRAY['brand','brand_name','brandName','manufacturer']);classifier:=lower(coalesce(desc_text,'')||' '||coalesce(category,'')||' '||coalesce(tj_private.onboarding_field(line,ARRAY['sku','model','item_number','itemNumber']),''));
    iw:=classifier~'warranty|protection|extended service|service plan';idel:=classifier~'delivery|freight|shipping';iinst:=classifier~'install|installation';ihaul:=classifier~'haul|removal|take.?away';isvc:=iw OR idel OR iinst OR ihaul OR classifier~'service';
    IF iw THEN warranty:=warranty+amount;warranty_lines:=warranty_lines||jsonb_build_array(line);END IF;IF idel THEN delivery:=delivery+amount;END IF;IF iinst THEN install:=install+amount;END IF;IF ihaul THEN haul:=haul+amount;END IF;IF NOT isvc THEN units:=units+qty;END IF;
    revenue:=revenue+amount;cost:=cost+line_cost;discount:=discount+line_discount;
    line_id:=coalesce(tj_private.onboarding_field(line,ARRAY['line_id','lineId','id','line_number','lineNumber']),external||'-'||idx::text);IF line_id=ANY(seen_ids) THEN RAISE EXCEPTION 'duplicate_line_id' USING ERRCODE='22023';END IF;seen_ids:=array_append(seen_ids,line_id);idx:=idx+1;
    facts:=facts||jsonb_build_array(jsonb_build_object('external_line_id',line_id,'external_item_id',tj_private.onboarding_field(line,ARRAY['model_id','modelId','product_id','productId','sku','model']),'item_number',tj_private.onboarding_field(line,ARRAY['model','sku','item_number','itemNumber']),'description',desc_text,'brand',brand,'product_category',category,'quantity',qty,'unit_price',unit,'line_amount',amount,'discount_amount',line_discount,'unit_cost',unit_cost,'line_cost',line_cost,'gross_margin_amount',amount-line_cost,'gross_margin_pct',CASE WHEN amount<>0 THEN (amount-line_cost)/amount*100 END,'is_warranty',iw,'is_service',isvc,'is_delivery',idel,'is_installation',iinst,'is_haul_away',ihaul));
   END LOOP;
   revenue:=coalesce(tj_private.epass_number(inv,ARRAY['total','invoice_total','invoiceTotal','total_amount','totalAmount','subtotal']),revenue);cost:=coalesce(tj_private.epass_number(inv,ARRAY['cost','total_cost','totalCost','cost_amount','costAmount']),cost);discount:=coalesce(tj_private.epass_number(inv,ARRAY['discount','discount_amount','discountAmount','total_discount','totalDiscount']),discount);
   IF abs(revenue)>1000000000 OR abs(coalesce(cost,0))>1000000000 OR abs(units)>1000000 OR units<>round(units) THEN RAISE EXCEPTION 'invalid_invoice_totals' USING ERRCODE='22023';END IF;
   tx_key:='epass:'||conn.id::text||':'||external;
   INSERT INTO tj.iq_pos_transactions(organization_id,store_id,pos_transaction_id,pos_employee_id,transaction_amount,transaction_date,line_items,warranty_items,synced_at,source_system,source_connection_id,customer_external_id,salesperson_external_id,currency_code,subtotal,discount_amount,cost_amount,gross_margin_amount,gross_margin_pct,source_payload)
    VALUES(conn.organization_id,store,tx_key,employee_code,revenue,dt,raw_lines,warranty_lines,clock_timestamp(),'epass',conn.id,customer,employee_code,currency,revenue,discount,cost,revenue-cost,CASE WHEN revenue<>0 THEN (revenue-cost)/revenue*100 END,inv)
    ON CONFLICT ON CONSTRAINT iq_pos_transactions_organization_id_pos_transaction_id_key DO UPDATE SET store_id=excluded.store_id,pos_employee_id=excluded.pos_employee_id,transaction_amount=excluded.transaction_amount,transaction_date=excluded.transaction_date,line_items=excluded.line_items,warranty_items=excluded.warranty_items,synced_at=excluded.synced_at,customer_external_id=excluded.customer_external_id,salesperson_external_id=excluded.salesperson_external_id,currency_code=excluded.currency_code,subtotal=excluded.subtotal,discount_amount=excluded.discount_amount,cost_amount=excluded.cost_amount,gross_margin_amount=excluded.gross_margin_amount,gross_margin_pct=excluded.gross_margin_pct,source_payload=excluded.source_payload WHERE tj.iq_pos_transactions.source_connection_id=conn.id AND tj.iq_pos_transactions.source_system='epass' RETURNING id INTO tx_id;
   IF tx_id IS NULL THEN RAISE EXCEPTION 'transaction_scope_conflict' USING ERRCODE='42501';END IF;
   DELETE FROM tj.iq_transaction_line_facts lf WHERE lf.organization_id=conn.organization_id AND lf.transaction_id=tx_id AND lf.source_connection_id=conn.id;
   FOR f IN SELECT value FROM jsonb_array_elements(facts) LOOP
    INSERT INTO tj.iq_transaction_line_facts(organization_id,transaction_id,source_connection_id,external_line_id,external_item_id,item_number,description,brand,product_category,quantity,unit_price,line_amount,discount_amount,unit_cost,line_cost,gross_margin_amount,gross_margin_pct,is_warranty,is_service,is_delivery,is_installation,is_haul_away,occurred_at,metadata)
     VALUES(conn.organization_id,tx_id,conn.id,f->>'external_line_id',f->>'external_item_id',f->>'item_number',f->>'description',f->>'brand',f->>'product_category',(f->>'quantity')::numeric,(f->>'unit_price')::numeric,(f->>'line_amount')::numeric,(f->>'discount_amount')::numeric,(f->>'unit_cost')::numeric,(f->>'line_cost')::numeric,(f->>'gross_margin_amount')::numeric,(f->>'gross_margin_pct')::numeric,(f->>'is_warranty')::boolean,(f->>'is_service')::boolean,(f->>'is_delivery')::boolean,(f->>'is_installation')::boolean,(f->>'is_haul_away')::boolean,dt,jsonb_build_object('source','epass','source_event_id',event_id,'us_epass_bridge_version',1));
   END LOOP;
   SELECT count(*),min(s.id::text)::uuid INTO candidate_count,sales_id FROM tj.sales_transactions s WHERE s.organization_id=conn.organization_id AND s.invoice_number=tx_key;
   IF candidate_count>1 OR (sales_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM tj.sales_transactions s WHERE s.id=sales_id AND s.metadata->>'source_connection_id'=conn.id::text)) THEN RAISE EXCEPTION 'sales_transaction_scope_conflict' USING ERRCODE='42501';END IF;
   IF sales_id IS NULL THEN
    INSERT INTO tj.sales_transactions(organization_id,location_id,user_id,transaction_date,item_count,item_value,order_total,warranty_offered,warranty_sold,warranty_value,delivery_value,install_value,haul_away_value,invoice_number,is_return,metadata)
     VALUES(conn.organization_id,store,person,(dt AT TIME ZONE 'UTC')::date,units::integer,revenue,revenue,NULL,warranty<>0,warranty,delivery,install,haul,tx_key,revenue<0,jsonb_build_object('source','epass','source_connection_id',conn.id,'pos_transaction_id',tx_id,'source_event_id',event_id,'us_epass_bridge_version',1,'invoice_number',invoice_no,'cost_amount',cost,'gross_margin_amount',revenue-cost,'gross_margin_pct',CASE WHEN revenue<>0 THEN (revenue-cost)/revenue*100 END,'salesperson_external_id',employee_code,'customer_external_id',customer,'reviewed_employee',person IS NOT NULL));
   ELSE
    UPDATE tj.sales_transactions SET location_id=store,user_id=person,transaction_date=(dt AT TIME ZONE 'UTC')::date,item_count=units::integer,item_value=revenue,order_total=revenue,warranty_offered=NULL,warranty_sold=warranty<>0,warranty_value=warranty,delivery_value=delivery,install_value=install,haul_away_value=haul,is_return=revenue<0,metadata=jsonb_build_object('source','epass','source_connection_id',conn.id,'pos_transaction_id',tx_id,'source_event_id',event_id,'us_epass_bridge_version',1,'invoice_number',invoice_no,'cost_amount',cost,'gross_margin_amount',revenue-cost,'gross_margin_pct',CASE WHEN revenue<>0 THEN (revenue-cost)/revenue*100 END,'salesperson_external_id',employee_code,'customer_external_id',customer,'reviewed_employee',person IS NOT NULL),updated_at=clock_timestamp() WHERE id=sales_id AND organization_id=conn.organization_id;
   END IF;
   processed:=processed+1;lines_n:=lines_n+idx;IF person IS NOT NULL THEN mapped_n:=mapped_n+1;END IF;
  EXCEPTION WHEN OTHERS THEN
   GET STACKED DIAGNOSTICS state=RETURNED_SQLSTATE;failed:=failed+1;IF jsonb_array_length(errors)<20 THEN errors:=errors||jsonb_build_array(jsonb_build_object('external_id',external,'error',CASE WHEN state='42501' THEN 'invoice_mapping_or_scope_rejected' WHEN state IN('22023','22007','22008','22P02') THEN 'invalid_invoice' ELSE 'invoice_write_failed' END,'sqlstate',state));END IF;
  END;
 END LOOP;
 SELECT EXISTS(SELECT 1 FROM tj.platform_connector_ingestion_keys k WHERE k.connection_id=conn.id AND k.external_entity_type='invoice' AND k.intelligence_event_id IS NOT NULL AND k.external_id>coalesce(next_external,after_external,'')) INTO has_more;
 RETURN jsonb_build_object('ok',failed=0,'connection_id',conn.id,'processed',processed,'scanned',scanned,'lines',lines_n,'mapped_reps',mapped_n,'failed',failed,'errors',errors,'next_cursor',CASE WHEN has_more THEN next_external END,'metrics_refreshed',false,'metrics_status','reviewed_metric_refresh_pending');
END $$;
NOTIFY pgrst,'reload schema';
