-- =============================================================================
-- HISTORICAL MARKER — phase_11_6_platform_configuration_engine_recovery
-- Version: 20260720142355
-- Applied to production: yes (via MCP, original SQL not preserved in version control)
-- Original SQL: UNAVAILABLE — applied interactively, not recoverable
-- Domain: Platform configuration engine
-- Objects created: aicrm_platform_config_snapshot() RPC, aicrm_business_units, aicrm_route_plans
-- Current schema reference: Query production with information_schema or pg_catalog
-- Execute in new environment: NO — this file contains no DDL
-- Execute against production: NO — already applied
-- 
-- This file exists solely to align the repository migration history with
-- supabase_migrations.schema_migrations in production. It does NOT recreate
-- the objects listed above. A separate baseline migration or manual schema
-- export is required to reproduce these objects in a new environment.
-- =============================================================================
