-- =============================================================================
-- HISTORICAL MARKER — phase_11_5_aicrm_product_fit_matrix_recovery
-- Version: 20260720142043
-- Applied to production: yes (via MCP, original SQL not preserved in version control)
-- Original SQL: UNAVAILABLE — applied interactively, not recoverable
-- Domain: AI CRM product fit matrix
-- Objects created: aicrm_product_fit_matrix() RPC, aicrm_product_fit_dashboard() RPC
-- Current schema reference: Query production with information_schema or pg_catalog
-- Execute in new environment: NO — this file contains no DDL
-- Execute against production: NO — already applied
-- 
-- This file exists solely to align the repository migration history with
-- supabase_migrations.schema_migrations in production. It does NOT recreate
-- the objects listed above. A separate baseline migration or manual schema
-- export is required to reproduce these objects in a new environment.
-- =============================================================================
