-- =============================================================================
-- HISTORICAL MARKER — phase_17_territory_coverage_intelligence_recovery_v2
-- Version: 20260720143401
-- Applied to production: yes (via MCP, original SQL not preserved in version control)
-- Original SQL: UNAVAILABLE — applied interactively, not recoverable
-- Domain: Territory and coverage intelligence
-- Objects created: aicrm_territories, aicrm_territory_heatmaps, provision_aicrm_territory_defaults_for_organization()
-- Current schema reference: Query production with information_schema or pg_catalog
-- Execute in new environment: NO — this file contains no DDL
-- Execute against production: NO — already applied
-- 
-- This file exists solely to align the repository migration history with
-- supabase_migrations.schema_migrations in production. It does NOT recreate
-- the objects listed above. A separate baseline migration or manual schema
-- export is required to reproduce these objects in a new environment.
-- =============================================================================
