-- =============================================================================
-- HISTORICAL MARKER — phase_6_aicrm_operating_layer_recovery
-- Version: 20260720140952
-- Applied to production: yes (via MCP, original SQL not preserved in version control)
-- Original SQL: UNAVAILABLE — applied interactively, not recoverable
-- Domain: AI CRM operating layer
-- Objects created: aicrm_opportunities, aicrm_pipeline_stages, aicrm_opportunity_health, aicrm_opportunity_timelines, aicrm_people, aicrm_employment_history, aicrm_buying_committee, aicrm_kpis, private.aicrm_record_opportunity_timeline_event(), private.aicrm_sync_person_current_employment()
-- Current schema reference: Query production with information_schema or pg_catalog
-- Execute in new environment: NO — this file contains no DDL
-- Execute against production: NO — already applied
-- 
-- This file exists solely to align the repository migration history with
-- supabase_migrations.schema_migrations in production. It does NOT recreate
-- the objects listed above. A separate baseline migration or manual schema
-- export is required to reproduce these objects in a new environment.
-- =============================================================================
