-- Product projection omits dealer cost. Row visibility uses mapped identities and approved scope.
CREATE FUNCTION tj_private.is_product_governance_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT tj_private.has_active_mapped_org() AND EXISTS(SELECT 1 FROM tj.product_iq_platform_roles r WHERE r.user_id=tj_private.current_source_user_id() AND r.status='active' AND (r.expires_at IS NULL OR r.expires_at>now()) AND r.role IN('product_iq_super_admin','super_admin','data_reviewer','data_publisher') AND (r.organization_id IS NULL OR tj_private.can_read_runtime_org(r.organization_id)));
$$;
CREATE FUNCTION tj_private.can_read_catalog_product(p_product uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT tj_private.has_active_mapped_org() AND EXISTS(SELECT 1 FROM tj.aiq_products p JOIN tj.organizations o ON o.id=p.organization_id WHERE p.id=p_product AND o.status='active' AND o.deleted_at IS NULL AND (
 tj_private.is_product_governance_admin()
 OR (tj_private.can_read_runtime_org(p.organization_id) AND tj.is_org_admin(p.organization_id))
 OR EXISTS(SELECT 1 FROM tj.product_iq_brand_scopes s JOIN tj.mfr_members m ON m.vendor_id=s.vendor_id JOIN tj.brand_catalog b ON b.id=s.brand_id AND b.manufacturer_id=s.vendor_id
 WHERE (b.id=p.brand_id OR lower(b.brand_name)=lower(p.brand_name)) AND s.organization_id=p.organization_id AND s.status='active' AND (s.expires_at IS NULL OR s.expires_at>now())
 AND (s.capabilities && ARRAY['product_read','product_manage']) AND m.user_id=tj_private.current_source_user_id() AND m.status='active' AND m.revoked_at IS NULL AND m.suspended_at IS NULL AND (m.expires_at IS NULL OR m.expires_at>now())
 AND m.role IN('vendor_owner','vendor_admin','brand_admin','product_editor','product_reviewer','asset_editor','training_editor','viewer'))
 OR (p.public_visible AND p.approval_status='approved' AND p.status IN('active','discontinued','clearance','end_of_life','open_box','refurbished') AND EXISTS(SELECT 1 FROM tj.piq_retailer_brands rb JOIN tj.brand_catalog b ON b.id=rb.brand_id JOIN tj.mfr_user_roles r ON r.user_id=rb.user_id JOIN tj.piq_retailer_profiles rp ON rp.user_id=rb.user_id
 WHERE rb.user_id=tj_private.current_source_user_id() AND (b.id=p.brand_id OR lower(b.brand_name)=lower(p.brand_name)) AND (r.is_retailer OR r.is_builder OR r.is_designer OR r.is_admin) AND (rp.organization_id IS NULL OR tj_private.can_read_runtime_org(rp.organization_id))))
 ));
$$;
CREATE FUNCTION tj_private.catalog_asset_allowed(p_from timestamptz,p_until timestamptz,p_embargo boolean,p_tiers text[],p_codes text[]) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT tj_private.has_active_mapped_org() AND NOT coalesce(p_embargo,true) AND (p_from IS NULL OR p_from<=now()) AND (p_until IS NULL OR p_until>now())
 AND (coalesce(cardinality(p_tiers),0)=0 OR p_tiers && ARRAY['all','public'] OR EXISTS(SELECT 1 FROM tj.piq_retailer_profiles r WHERE r.user_id=tj_private.current_source_user_id() AND (r.organization_id IS NULL OR tj_private.can_read_runtime_org(r.organization_id)) AND (r.account_type=ANY(p_tiers) OR r.buying_group IS NOT NULL AND 'buying_group'=ANY(p_tiers))))
 AND (coalesce(cardinality(p_codes),0)=0 OR EXISTS(SELECT 1 FROM tj.piq_retailer_profiles r WHERE r.user_id=tj_private.current_source_user_id() AND (r.organization_id IS NULL OR tj_private.can_read_runtime_org(r.organization_id)) AND r.exclusive_codes && p_codes));
$$;
REVOKE ALL ON FUNCTION tj_private.is_product_governance_admin() FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION tj_private.is_product_governance_admin() TO authenticated;
REVOKE ALL ON FUNCTION tj_private.can_read_catalog_product(uuid) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION tj_private.can_read_catalog_product(uuid) TO authenticated;
REVOKE ALL ON FUNCTION tj_private.catalog_asset_allowed(timestamptz,timestamptz,boolean,text[],text[]) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION tj_private.catalog_asset_allowed(timestamptz,timestamptz,boolean,text[],text[]) TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.aiq_products'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.aiq_products'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: aiq_products'; END IF; END $guard$;
CREATE POLICY consolidation_catalog_read ON tj.aiq_products FOR SELECT TO authenticated USING(tj_private.can_read_catalog_product(id));
GRANT SELECT ("id","organization_id","manufacturer_name","brand_name","product_line","category","series","model","status","launch_date","discontinued_date","msrp","country_availability","product_family","short_description","public_visible","approval_status","version_number","created_at","updated_at","brand_id","manufacturer_id","source_type","source_reference","source_confidence","source_extracted_at","source_review_status","source_reviewed_by","source_reviewed_at","published_at","unpublished_at","created_by","updated_by","long_description","features_html","upc","ean","gtin","finish","color","color_family","energy_star","ada_compliant","made_in","weight_lbs","width_inches","height_inches","depth_inches","map_price","freight_class","ships_ltl","lead_time_days","min_order_qty","sale_price","lowest_price","lowest_price_source","price_currency","price_checked_at","condition_flags","is_discontinued","is_clearance","is_end_of_life","is_open_box","is_refurbished","replacement_model","condition_notes","specs_json","available_colors","capacity_cu_ft","voltage","amperage","wattage","frequency_hz","installation_type","depth_with_handles","depth_without_handles","market","is_parts_accessory","product_segment","subcategory","size_class","has_water_dispenser","has_ice_maker","has_ice_dispenser","is_counter_depth","fuel_type","door_style","noise_dba","defrost_type","is_retailer_exclusive","exclusive_retailer","discovered_via","retailer_description","bundle_skus") ON tj.aiq_products TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.pim_price_history'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.pim_price_history'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: pim_price_history'; END IF; END $guard$;
CREATE POLICY consolidation_catalog_read ON tj.pim_price_history FOR SELECT TO authenticated USING(tj_private.can_read_catalog_product(product_id));
GRANT SELECT ON tj.pim_price_history TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.pim_product_certifications'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.pim_product_certifications'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: pim_product_certifications'; END IF; END $guard$;
CREATE POLICY consolidation_catalog_read ON tj.pim_product_certifications FOR SELECT TO authenticated USING(tj_private.can_read_catalog_product(product_id));
GRANT SELECT ON tj.pim_product_certifications TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.pim_product_features'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.pim_product_features'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: pim_product_features'; END IF; END $guard$;
CREATE POLICY consolidation_catalog_read ON tj.pim_product_features FOR SELECT TO authenticated USING(tj_private.can_read_catalog_product(product_id));
GRANT SELECT ON tj.pim_product_features TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.pim_retailer_prices'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.pim_retailer_prices'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: pim_retailer_prices'; END IF; END $guard$;
CREATE POLICY consolidation_catalog_read ON tj.pim_retailer_prices FOR SELECT TO authenticated USING(tj_private.can_read_catalog_product(product_id));
GRANT SELECT ON tj.pim_retailer_prices TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.pim_product_documents'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.pim_product_documents'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: pim_product_documents'; END IF; END $guard$;
CREATE POLICY consolidation_catalog_read ON tj.pim_product_documents FOR SELECT TO authenticated USING(tj_private.can_read_catalog_product(product_id) AND approved IS TRUE AND tj_private.catalog_asset_allowed(available_from,available_until,embargoed,audience_tiers,exclusive_codes) AND is_current IS TRUE AND (expiry_date IS NULL OR expiry_date>=current_date));
GRANT SELECT ON tj.pim_product_documents TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.pim_product_images'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.pim_product_images'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: pim_product_images'; END IF; END $guard$;
CREATE POLICY consolidation_catalog_read ON tj.pim_product_images FOR SELECT TO authenticated USING(tj_private.can_read_catalog_product(product_id) AND approved IS TRUE AND tj_private.catalog_asset_allowed(available_from,available_until,embargoed,audience_tiers,exclusive_codes));
GRANT SELECT ON tj.pim_product_images TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.pim_product_videos'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.pim_product_videos'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: pim_product_videos'; END IF; END $guard$;
CREATE POLICY consolidation_catalog_read ON tj.pim_product_videos FOR SELECT TO authenticated USING(tj_private.can_read_catalog_product(product_id) AND approved IS TRUE AND tj_private.catalog_asset_allowed(available_from,available_until,embargoed,audience_tiers,exclusive_codes) AND is_current IS TRUE AND archived_at IS NULL);
GRANT SELECT ON tj.pim_product_videos TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.pim_price_changes'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.pim_price_changes'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: pim_price_changes'; END IF; END $guard$;
CREATE POLICY consolidation_catalog_read ON tj.pim_price_changes FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM tj.pim_retailer_prices r WHERE r.id=retailer_price_id));
GRANT SELECT ON tj.pim_price_changes TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.product_relationships'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.product_relationships'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: product_relationships'; END IF; END $guard$;
CREATE POLICY consolidation_catalog_read ON tj.product_relationships FOR SELECT TO authenticated USING(tj_private.can_read_catalog_product(source_product_id) AND tj_private.can_read_catalog_product(related_product_id));
GRANT SELECT ON tj.product_relationships TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.retailer_discovered_products'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.retailer_discovered_products'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: retailer_discovered_products'; END IF; END $guard$;
CREATE POLICY consolidation_catalog_read ON tj.retailer_discovered_products FOR SELECT TO authenticated USING(tj_private.can_read_catalog_product(aiq_product_id) OR (SELECT tj_private.is_product_governance_admin()));
GRANT SELECT ON tj.retailer_discovered_products TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.pim_brand_content'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.pim_brand_content'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: pim_brand_content'; END IF; END $guard$;
CREATE POLICY consolidation_catalog_read ON tj.pim_brand_content FOR SELECT TO authenticated USING((SELECT tj_private.is_product_governance_admin()));
GRANT SELECT ON tj.pim_brand_content TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.pim_scrape_runs'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.pim_scrape_runs'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: pim_scrape_runs'; END IF; END $guard$;
CREATE POLICY consolidation_catalog_read ON tj.pim_scrape_runs FOR SELECT TO authenticated USING((SELECT tj_private.is_product_governance_admin()));
GRANT SELECT ON tj.pim_scrape_runs TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.retailer_brand_pages'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.retailer_brand_pages'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: retailer_brand_pages'; END IF; END $guard$;
CREATE POLICY consolidation_catalog_read ON tj.retailer_brand_pages FOR SELECT TO authenticated USING((SELECT tj_private.is_product_governance_admin()));
GRANT SELECT ON tj.retailer_brand_pages TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.retailer_crawl_runs'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.retailer_crawl_runs'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: retailer_crawl_runs'; END IF; END $guard$;
CREATE POLICY consolidation_catalog_read ON tj.retailer_crawl_runs FOR SELECT TO authenticated USING((SELECT tj_private.is_product_governance_admin()));
GRANT SELECT ON tj.retailer_crawl_runs TO authenticated;
CREATE VIEW tj.aiq_products_app WITH(security_invoker=true,security_barrier=true) AS SELECT "id","organization_id","manufacturer_name","brand_name","product_line","category","series","model","status","launch_date","discontinued_date","msrp","country_availability","product_family","short_description","public_visible","approval_status","version_number","created_at","updated_at","brand_id","manufacturer_id","source_type","source_reference","source_confidence","source_extracted_at","source_review_status","source_reviewed_by","source_reviewed_at","published_at","unpublished_at","created_by","updated_by","long_description","features_html","upc","ean","gtin","finish","color","color_family","energy_star","ada_compliant","made_in","weight_lbs","width_inches","height_inches","depth_inches","map_price","freight_class","ships_ltl","lead_time_days","min_order_qty","sale_price","lowest_price","lowest_price_source","price_currency","price_checked_at","condition_flags","is_discontinued","is_clearance","is_end_of_life","is_open_box","is_refurbished","replacement_model","condition_notes","specs_json","available_colors","capacity_cu_ft","voltage","amperage","wattage","frequency_hz","installation_type","depth_with_handles","depth_without_handles","market","is_parts_accessory","product_segment","subcategory","size_class","has_water_dispenser","has_ice_maker","has_ice_dispenser","is_counter_depth","fuel_type","door_style","noise_dba","defrost_type","is_retailer_exclusive","exclusive_retailer","discovered_via","retailer_description","bundle_skus" FROM tj.aiq_products;
REVOKE ALL ON tj.aiq_products_app FROM PUBLIC,anon,authenticated;
GRANT SELECT ON tj.aiq_products_app TO authenticated;
NOTIFY pgrst,'reload schema';
