-- =============================================================================
-- HISTORICAL MARKER — phase_20_industry_knowledge_graph_engine_recovery
-- Version: 20260720143435
-- Applied to production: yes (via MCP, original SQL not preserved in version control)
-- Original SQL: UNAVAILABLE — applied interactively, not recoverable
-- Domain: Industry knowledge graph
-- Objects created: aiq_products, aiq_product_specifications, aiq_product_relationships, aiq_product_training_assets, aiq_documents, aiq_competitive_comparisons, aiq_industry_news, version tables, aiq_record_version(), aiq_touch_updated_at()
-- Current schema reference: Query production with information_schema or pg_catalog
-- Execute in new environment: NO — this file contains no DDL
-- Execute against production: NO — already applied
-- 
-- This file exists solely to align the repository migration history with
-- supabase_migrations.schema_migrations in production. It does NOT recreate
-- the objects listed above. A separate baseline migration or manual schema
-- export is required to reproduce these objects in a new environment.
-- =============================================================================
