create or replace function public.platform_resolve_identity(p_organization_id uuid,p_entity_type text,p_source_system text default null,p_external_id text default null,p_source_record_id text default null)
returns table(canonical_id uuid,canonical_table text,display_name text,confidence numeric,match_method text,source_system text,source_table text,source_record_id text,external_id text)
language sql security definer set search_path=public stable as $$
 select l.canonical_id,l.canonical_table,l.display_name,l.confidence,l.match_method,l.source_system,l.source_table,l.source_record_id,l.external_id from public.platform_identity_links l where l.organization_id=p_organization_id and l.entity_type=p_entity_type and (p_source_system is null or l.source_system=p_source_system) and (p_external_id is null or l.external_id=p_external_id) and (p_source_record_id is null or l.source_record_id=p_source_record_id) and exists(select 1 from public.organization_members m where m.organization_id=p_organization_id and m.user_id=auth.uid() and m.status='active') order by l.is_primary desc,l.confidence desc,l.last_seen_at desc limit 20;
$$;
revoke all on function public.platform_resolve_identity(uuid,text,text,text,text) from public,anon; grant execute on function public.platform_resolve_identity(uuid,text,text,text,text) to authenticated;

create or replace function public.platform_intelligence_store_rollup(p_organization_id uuid,p_since timestamptz default now()-interval '30 days')
returns table(store_id uuid,store_name text,traffic_groups numeric,interactions bigint,no_sales bigint,sales bigint,revenue numeric,refunds bigint,refund_amount numeric,conversion_pct numeric,avg_ticket numeric,field_score numeric)
language sql security definer set search_path=public stable as $$
 with e as (select coalesce(canonical_event_type,event_type) et,store_id,payload from public.intelligence_events where organization_id=p_organization_id and occurred_at>=coalesce(p_since,now()-interval '30 days')), a as (select store_id,coalesce(sum((payload->>'customer_groups')::numeric) filter(where et='traffic.observed'),0) traffic_groups,count(*) filter(where et in ('interaction.started','interaction.completed','interaction.no_sale','interaction.updated')) interactions,count(*) filter(where et='interaction.no_sale') no_sales,count(*) filter(where et='transaction.completed') sales,coalesce(sum((payload->>'amount')::numeric) filter(where et='transaction.completed'),0) revenue,count(*) filter(where et='transaction.refunded') refunds,coalesce(sum(abs((payload->>'amount')::numeric)) filter(where et='transaction.refunded'),0) refund_amount,round(avg((payload->>'overall_score')::numeric) filter(where et='field.score_recorded'),2) field_score from e where store_id is not null group by store_id)
 select a.store_id,l.name,a.traffic_groups,a.interactions,a.no_sales,a.sales,a.revenue,a.refunds,a.refund_amount,case when a.traffic_groups>0 then round((a.sales::numeric/a.traffic_groups)*100,2) end,case when a.sales>0 then round(a.revenue/a.sales,2) end,a.field_score from a left join public.org_locations l on l.id=a.store_id where exists(select 1 from public.organization_members m where m.organization_id=p_organization_id and m.user_id=auth.uid() and m.status='active') order by a.revenue desc nulls last;
$$;
revoke all on function public.platform_intelligence_store_rollup(uuid,timestamptz) from public,anon; grant execute on function public.platform_intelligence_store_rollup(uuid,timestamptz) to authenticated;

create or replace function public.platform_intelligence_employee_rollup(p_organization_id uuid,p_since timestamptz default now()-interval '30 days')
returns table(employee_id uuid,display_name text,interactions bigint,no_sales bigint,sales bigint,revenue numeric,conversion_pct numeric,avg_ticket numeric,learning_events bigint,coaching_reviews bigint)
language sql security definer set search_path=public stable as $$
 with e as (select coalesce(canonical_event_type,event_type) et,actor_id,payload from public.intelligence_events where organization_id=p_organization_id and occurred_at>=coalesce(p_since,now()-interval '30 days') and actor_id is not null), a as (select actor_id,count(*) filter(where et in ('interaction.started','interaction.completed','interaction.no_sale','interaction.updated')) interactions,count(*) filter(where et='interaction.no_sale') no_sales,count(*) filter(where et='transaction.completed') sales,coalesce(sum((payload->>'amount')::numeric) filter(where et='transaction.completed'),0) revenue,count(*) filter(where et like 'learning.%' or et='field.training_completed') learning_events,count(*) filter(where et='coaching.review_completed') coaching_reviews from e group by actor_id), n as (select canonical_id,max(display_name) display_name from public.platform_identity_links where organization_id=p_organization_id and entity_type='employee' group by canonical_id)
 select a.actor_id,coalesce(n.display_name,a.actor_id::text),a.interactions,a.no_sales,a.sales,a.revenue,case when a.interactions>0 then round((a.sales::numeric/a.interactions)*100,2) end,case when a.sales>0 then round(a.revenue/a.sales,2) end,a.learning_events,a.coaching_reviews from a left join n on n.canonical_id=a.actor_id where exists(select 1 from public.organization_members m where m.organization_id=p_organization_id and m.user_id=auth.uid() and m.status='active') order by a.revenue desc nulls last;
$$;
revoke all on function public.platform_intelligence_employee_rollup(uuid,timestamptz) from public,anon; grant execute on function public.platform_intelligence_employee_rollup(uuid,timestamptz) to authenticated;

update public.platform_modules set manifest=coalesce(manifest,'{}'::jsonb)||jsonb_build_object('intelligence',jsonb_build_object('feed_rpc','platform_intelligence_feed','summary_rpc','platform_intelligence_summary','store_rollup_rpc','platform_intelligence_store_rollup','employee_rollup_rpc','platform_intelligence_employee_rollup','identity_resolver_rpc','platform_resolve_identity','contract_version','1.0')) where key in ('command_center','intelligence_group');