-- =============================================================================
-- HISTORICAL MARKER — phase_4_aicrm_account_views_and_tags_recovery
-- Version: 20260720140746
-- Applied to production: yes (via MCP, original SQL not preserved in version control)
-- Original SQL: UNAVAILABLE — applied interactively, not recoverable
-- Domain: AI CRM accounts, tags, saved views
-- Objects created: aicrm_accounts, aicrm_tags, aicrm_account_tags, aicrm_saved_views, aicrm_contacts, aicrm_notes, aicrm_activities, aicrm_audit_log
-- Current schema reference: Query production with information_schema or pg_catalog
-- Execute in new environment: NO — this file contains no DDL
-- Execute against production: NO — already applied
-- 
-- This file exists solely to align the repository migration history with
-- supabase_migrations.schema_migrations in production. It does NOT recreate
-- the objects listed above. A separate baseline migration or manual schema
-- export is required to reproduce these objects in a new environment.
-- =============================================================================
