create or replace function public.platform_intelligence_feed(p_organization_id uuid,p_since timestamptz default now()-interval '30 days',p_limit integer default 200,p_event_types text[] default null)
returns table(id uuid,event_type text,subject_entity_type text,entity_id uuid,store_id uuid,actor_id uuid,source_system text,source_record_id text,payload jsonb,occurred_at timestamptz,correlation_id uuid,identity_confidence numeric,metadata jsonb)
language sql security definer set search_path=public stable as $$
 select e.id,coalesce(e.canonical_event_type,e.event_type),e.subject_entity_type,e.entity_id,e.store_id,e.actor_id,e.source_system,e.source_record_id,e.payload,e.occurred_at,e.correlation_id,e.identity_confidence,e.metadata from public.intelligence_events e where e.organization_id=p_organization_id and e.occurred_at>=coalesce(p_since,now()-interval '30 days') and (p_event_types is null or coalesce(e.canonical_event_type,e.event_type)=any(p_event_types)) and exists(select 1 from public.organization_members m where m.organization_id=p_organization_id and m.user_id=auth.uid() and m.status='active') order by e.occurred_at desc limit least(greatest(coalesce(p_limit,200),1),1000);
$$;
revoke all on function public.platform_intelligence_feed(uuid,timestamptz,integer,text[]) from public,anon; grant execute on function public.platform_intelligence_feed(uuid,timestamptz,integer,text[]) to authenticated;

create or replace function public.platform_intelligence_summary(p_organization_id uuid,p_since timestamptz default now()-interval '30 days')
returns jsonb language sql security definer set search_path=public stable as $$
 with e as (select coalesce(canonical_event_type,event_type) et,payload from public.intelligence_events where organization_id=p_organization_id and occurred_at>=coalesce(p_since,now()-interval '30 days')) select case when exists(select 1 from public.organization_members m where m.organization_id=p_organization_id and m.user_id=auth.uid() and m.status='active') then jsonb_build_object('since',p_since,'events',count(*),'sales',count(*) filter(where et='transaction.completed'),'refunds',count(*) filter(where et='transaction.refunded'),'traffic_groups',coalesce(sum((payload->>'customer_groups')::numeric) filter(where et='traffic.observed'),0),'interactions',count(*) filter(where et like 'interaction.%'),'no_sales',count(*) filter(where et='interaction.no_sale'),'learning_events',count(*) filter(where et like 'learning.%' or et='field.training_completed'),'field_scores',count(*) filter(where et='field.score_recorded'),'revenue',coalesce(sum((payload->>'amount')::numeric) filter(where et='transaction.completed'),0),'refund_amount',coalesce(sum(abs((payload->>'amount')::numeric)) filter(where et='transaction.refunded'),0),'recommendations',count(*) filter(where et='recommendation.generated'),'deals_won',count(*) filter(where et='deal.won'),'coaching_reviews',count(*) filter(where et='coaching.review_completed'),'avg_field_score',round(avg((payload->>'overall_score')::numeric) filter(where et='field.score_recorded'),2)) else '{}'::jsonb end from e;
$$;
revoke all on function public.platform_intelligence_summary(uuid,timestamptz) from public,anon; grant execute on function public.platform_intelligence_summary(uuid,timestamptz) to authenticated;