-- Explicit read policy batch; private/global-response caches and product assets remain gated.
CREATE FUNCTION tj_private.has_active_mapped_org() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT EXISTS(SELECT 1 FROM tj.organization_members m JOIN tj.organizations o ON o.id=m.organization_id WHERE m.user_id=(SELECT tj_private.current_source_user_id()) AND m.status='active' AND o.status='active' AND o.deleted_at IS NULL);
$$;
CREATE FUNCTION tj_private.is_source_self(p_user uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT p_user IS NOT NULL AND p_user=(SELECT tj_private.current_source_user_id()) AND tj_private.has_active_mapped_org();
$$;
CREATE FUNCTION tj_private.can_read_runtime_org(p_org uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT tj.is_org_member(p_org) AND EXISTS(SELECT 1 FROM tj.organizations o WHERE o.id=p_org AND o.status='active' AND o.deleted_at IS NULL);
$$;
CREATE FUNCTION tj_private.can_read_source_profile(p_user uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT tj_private.is_source_self(p_user) OR EXISTS(SELECT 1 FROM tj.organization_members m WHERE m.user_id=p_user AND m.status='active' AND tj_private.can_read_runtime_org(m.organization_id) AND tj.is_org_admin(m.organization_id));
$$;
REVOKE ALL ON FUNCTION tj_private.has_active_mapped_org() FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION tj_private.has_active_mapped_org() TO authenticated;
REVOKE ALL ON FUNCTION tj_private.is_source_self(uuid) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION tj_private.is_source_self(uuid) TO authenticated;
REVOKE ALL ON FUNCTION tj_private.can_read_runtime_org(uuid) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION tj_private.can_read_runtime_org(uuid) TO authenticated;
REVOKE ALL ON FUNCTION tj_private.can_read_source_profile(uuid) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION tj_private.can_read_source_profile(uuid) TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.academy_brand_certifications'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.academy_brand_certifications'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: academy_brand_certifications'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.academy_brand_certifications FOR SELECT TO authenticated USING(tj_private.is_source_self(user_id));
GRANT SELECT ON tj.academy_brand_certifications TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.academy_brand_progress'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.academy_brand_progress'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: academy_brand_progress'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.academy_brand_progress FOR SELECT TO authenticated USING(tj_private.is_source_self(user_id));
GRANT SELECT ON tj.academy_brand_progress TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.academy_daily_metrics'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.academy_daily_metrics'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: academy_daily_metrics'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.academy_daily_metrics FOR SELECT TO authenticated USING(tj_private.is_source_self(user_id));
GRANT SELECT ON tj.academy_daily_metrics TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.academy_learning_events'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.academy_learning_events'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: academy_learning_events'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.academy_learning_events FOR SELECT TO authenticated USING(tj_private.is_source_self(user_id));
GRANT SELECT ON tj.academy_learning_events TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.academy_progress'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.academy_progress'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: academy_progress'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.academy_progress FOR SELECT TO authenticated USING(tj_private.is_source_self(user_id));
GRANT SELECT ON tj.academy_progress TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.academy_quiz_scores'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.academy_quiz_scores'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: academy_quiz_scores'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.academy_quiz_scores FOR SELECT TO authenticated USING(tj_private.is_source_self(user_id));
GRANT SELECT ON tj.academy_quiz_scores TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.ai_conversation_turns'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.ai_conversation_turns'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: ai_conversation_turns'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.ai_conversation_turns FOR SELECT TO authenticated USING(tj_private.is_source_self(user_id));
GRANT SELECT ON tj.ai_conversation_turns TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.piq_retailer_brands'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.piq_retailer_brands'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: piq_retailer_brands'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.piq_retailer_brands FOR SELECT TO authenticated USING(tj_private.is_source_self(user_id));
GRANT SELECT ON tj.piq_retailer_brands TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.piq_retailer_profiles'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.piq_retailer_profiles'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: piq_retailer_profiles'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.piq_retailer_profiles FOR SELECT TO authenticated USING(tj_private.is_source_self(user_id));
GRANT SELECT ON tj.piq_retailer_profiles TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.mfr_members'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.mfr_members'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: mfr_members'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.mfr_members FOR SELECT TO authenticated USING(tj_private.is_source_self(user_id));
GRANT SELECT ON tj.mfr_members TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.mfr_user_roles'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.mfr_user_roles'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: mfr_user_roles'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.mfr_user_roles FOR SELECT TO authenticated USING(tj_private.is_source_self(user_id));
GRANT SELECT ON tj.mfr_user_roles TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.academy_notifications'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.academy_notifications'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: academy_notifications'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.academy_notifications FOR SELECT TO authenticated USING(tj_private.is_source_self(user_id) AND (organization_id IS NULL OR tj_private.can_read_runtime_org(organization_id)));
GRANT SELECT ON tj.academy_notifications TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.academy_chapters'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.academy_chapters'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: academy_chapters'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.academy_chapters FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.academy_chapters TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.academy_quizzes'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.academy_quizzes'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: academy_quizzes'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.academy_quizzes FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.academy_quizzes TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.academy_volumes'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.academy_volumes'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: academy_volumes'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.academy_volumes FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.academy_volumes TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.aiq_recalls'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.aiq_recalls'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: aiq_recalls'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.aiq_recalls FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.aiq_recalls TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.aiq_vendor_contacts'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.aiq_vendor_contacts'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: aiq_vendor_contacts'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.aiq_vendor_contacts FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.aiq_vendor_contacts TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.aiq_warranty_policies'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.aiq_warranty_policies'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: aiq_warranty_policies'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.aiq_warranty_policies FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.aiq_warranty_policies TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.brand_map_policies'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.brand_map_policies'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: brand_map_policies'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.brand_map_policies FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.brand_map_policies TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.buying_groups'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.buying_groups'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: buying_groups'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.buying_groups FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.buying_groups TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.competitive_cross_reference'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.competitive_cross_reference'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: competitive_cross_reference'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.competitive_cross_reference FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.competitive_cross_reference TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_replacement_cycles'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_replacement_cycles'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_replacement_cycles'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_replacement_cycles FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.crm_replacement_cycles TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.intel_news'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.intel_news'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: intel_news'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.intel_news FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.intel_news TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.iq_badges'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.iq_badges'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: iq_badges'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.iq_badges FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.iq_badges TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.iq_cards'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.iq_cards'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: iq_cards'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.iq_cards FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.iq_cards TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.iq_courses'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.iq_courses'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: iq_courses'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.iq_courses FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.iq_courses TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.iq_decks'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.iq_decks'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: iq_decks'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.iq_decks FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.iq_decks TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.iq_lanes'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.iq_lanes'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: iq_lanes'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.iq_lanes FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.iq_lanes TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.iq_product_cards'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.iq_product_cards'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: iq_product_cards'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.iq_product_cards FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.iq_product_cards TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.iq_zones'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.iq_zones'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: iq_zones'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.iq_zones FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.iq_zones TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.pim_category_map'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.pim_category_map'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: pim_category_map'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.pim_category_map FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.pim_category_map TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.platform_plan_modules'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.platform_plan_modules'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: platform_plan_modules'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.platform_plan_modules FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.platform_plan_modules TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.platform_seat_tiers'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.platform_seat_tiers'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: platform_seat_tiers'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.platform_seat_tiers FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.platform_seat_tiers TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.scraper_brand_sources'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.scraper_brand_sources'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: scraper_brand_sources'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.scraper_brand_sources FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.scraper_brand_sources TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.scraper_retailer_sources'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.scraper_retailer_sources'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: scraper_retailer_sources'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.scraper_retailer_sources FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()));
GRANT SELECT ON tj.scraper_retailer_sources TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.field_checklist_categories'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.field_checklist_categories'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: field_checklist_categories'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.field_checklist_categories FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()) AND is_active);
GRANT SELECT ON tj.field_checklist_categories TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.field_checklist_items'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.field_checklist_items'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: field_checklist_items'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.field_checklist_items FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()) AND is_active);
GRANT SELECT ON tj.field_checklist_items TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.platform_ai_credit_packs'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.platform_ai_credit_packs'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: platform_ai_credit_packs'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.platform_ai_credit_packs FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()) AND is_active);
GRANT SELECT ON tj.platform_ai_credit_packs TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.platform_plans'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.platform_plans'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: platform_plans'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.platform_plans FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()) AND is_active);
GRANT SELECT ON tj.platform_plans TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.service_iq_templates'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.service_iq_templates'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: service_iq_templates'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.service_iq_templates FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()) AND is_active);
GRANT SELECT ON tj.service_iq_templates TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.aiq_service_providers'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.aiq_service_providers'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: aiq_service_providers'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.aiq_service_providers FOR SELECT TO authenticated USING((SELECT tj_private.has_active_mapped_org()) AND status='active');
GRANT SELECT ON tj.aiq_service_providers TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.aicrm_outreach_campaigns'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.aicrm_outreach_campaigns'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: aicrm_outreach_campaigns'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.aicrm_outreach_campaigns FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.is_org_admin(organization_id));
GRANT SELECT ON tj.aicrm_outreach_campaigns TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.aicrm_sequence_enrollments'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.aicrm_sequence_enrollments'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: aicrm_sequence_enrollments'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.aicrm_sequence_enrollments FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.is_org_admin(organization_id));
GRANT SELECT ON tj.aicrm_sequence_enrollments TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.aicrm_sequence_steps'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.aicrm_sequence_steps'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: aicrm_sequence_steps'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.aicrm_sequence_steps FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.is_org_admin(organization_id));
GRANT SELECT ON tj.aicrm_sequence_steps TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.communication_templates'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.communication_templates'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: communication_templates'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.communication_templates FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.is_org_admin(organization_id));
GRANT SELECT ON tj.communication_templates TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_archive_log'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_archive_log'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_archive_log'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_archive_log FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.is_org_admin(organization_id));
GRANT SELECT ON tj.crm_archive_log TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_buying_groups'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_buying_groups'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_buying_groups'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_buying_groups FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.is_org_admin(organization_id));
GRANT SELECT ON tj.crm_buying_groups TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_coaching_queue'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_coaching_queue'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_coaching_queue'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_coaching_queue FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.is_org_admin(organization_id));
GRANT SELECT ON tj.crm_coaching_queue TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_custom_fields'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_custom_fields'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_custom_fields'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_custom_fields FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.is_org_admin(organization_id));
GRANT SELECT ON tj.crm_custom_fields TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_sla_rules'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_sla_rules'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_sla_rules'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_sla_rules FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.is_org_admin(organization_id));
GRANT SELECT ON tj.crm_sla_rules TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_temperature_history'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_temperature_history'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_temperature_history'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_temperature_history FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.is_org_admin(organization_id));
GRANT SELECT ON tj.crm_temperature_history TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.product_iq_brand_scopes'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.product_iq_brand_scopes'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: product_iq_brand_scopes'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.product_iq_brand_scopes FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.is_org_admin(organization_id));
GRANT SELECT ON tj.product_iq_brand_scopes TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.product_iq_governance_audit_log'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.product_iq_governance_audit_log'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: product_iq_governance_audit_log'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.product_iq_governance_audit_log FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.is_org_admin(organization_id));
GRANT SELECT ON tj.product_iq_governance_audit_log TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.product_iq_platform_roles'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.product_iq_platform_roles'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: product_iq_platform_roles'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.product_iq_platform_roles FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.is_org_admin(organization_id));
GRANT SELECT ON tj.product_iq_platform_roles TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.speciq_retailer_settings'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.speciq_retailer_settings'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: speciq_retailer_settings'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.speciq_retailer_settings FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.is_org_admin(organization_id));
GRANT SELECT ON tj.speciq_retailer_settings TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.organization_brands'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.organization_brands'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: organization_brands'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.organization_brands FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id));
GRANT SELECT ON tj.organization_brands TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_activity_goals'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_activity_goals'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_activity_goals'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_activity_goals FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.aiq_scope_allows(organization_id,user_id));
GRANT SELECT ON tj.crm_activity_goals TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_analytics_events'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_analytics_events'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_analytics_events'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_analytics_events FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.aiq_scope_allows(organization_id,user_id));
GRANT SELECT ON tj.crm_analytics_events TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_commissions'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_commissions'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_commissions'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_commissions FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.aiq_scope_allows(organization_id,user_id));
GRANT SELECT ON tj.crm_commissions TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_daily_five'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_daily_five'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_daily_five'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_daily_five FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.aiq_scope_allows(organization_id,user_id));
GRANT SELECT ON tj.crm_daily_five TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_emails'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_emails'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_emails'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_emails FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.aiq_scope_allows(organization_id,user_id));
GRANT SELECT ON tj.crm_emails TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.performance_observations'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.performance_observations'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: performance_observations'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.performance_observations FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.aiq_scope_allows(organization_id,user_id));
GRANT SELECT ON tj.performance_observations TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.performance_skill_state'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.performance_skill_state'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: performance_skill_state'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.performance_skill_state FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.aiq_scope_allows(organization_id,user_id));
GRANT SELECT ON tj.performance_skill_state TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.platform_ai_credits'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.platform_ai_credits'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: platform_ai_credits'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.platform_ai_credits FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(org_id) AND tj.is_org_admin(org_id));
GRANT SELECT ON tj.platform_ai_credits TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.platform_subscriptions'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.platform_subscriptions'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: platform_subscriptions'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.platform_subscriptions FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(org_id) AND tj.is_org_admin(org_id));
GRANT SELECT ON tj.platform_subscriptions TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.performance_competencies'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.performance_competencies'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: performance_competencies'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.performance_competencies FOR SELECT TO authenticated USING((organization_id IS NULL AND (SELECT tj_private.has_active_mapped_org())) OR tj_private.can_read_runtime_org(organization_id));
GRANT SELECT ON tj.performance_competencies TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_deals'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_deals'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_deals'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_deals FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.aiq_scope_allows(organization_id,owner_user_id) AND tj.aiq_store_allows(organization_id,location_id) AND deleted_at IS NULL);
GRANT SELECT ON tj.crm_deals TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_tasks'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_tasks'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_tasks'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_tasks FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.aiq_scope_allows(organization_id,assignee_user_id) AND deleted_at IS NULL AND (deal_id IS NULL OR EXISTS(SELECT 1 FROM tj.crm_deals d WHERE d.id=crm_tasks.deal_id AND d.organization_id=crm_tasks.organization_id)));
GRANT SELECT ON tj.crm_tasks TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_sla_events'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_sla_events'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_sla_events'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_sla_events FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND tj.aiq_scope_allows(organization_id,assigned_to));
GRANT SELECT ON tj.crm_sla_events TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_delivery_workflows'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_delivery_workflows'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_delivery_workflows'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_delivery_workflows FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND EXISTS(SELECT 1 FROM tj.crm_deals d WHERE d.id=crm_delivery_workflows.deal_id AND d.organization_id=crm_delivery_workflows.organization_id));
GRANT SELECT ON tj.crm_delivery_workflows TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_stage_history'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_stage_history'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_stage_history'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_stage_history FOR SELECT TO authenticated USING(tj_private.can_read_runtime_org(organization_id) AND EXISTS(SELECT 1 FROM tj.crm_deals d WHERE d.id=crm_stage_history.deal_id AND d.organization_id=crm_stage_history.organization_id));
GRANT SELECT ON tj.crm_stage_history TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_deal_participants'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_deal_participants'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_deal_participants'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_deal_participants FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM tj.crm_deals d JOIN tj.contacts c ON c.id=crm_deal_participants.contact_id AND c.organization_id=d.organization_id WHERE d.id=crm_deal_participants.deal_id));
GRANT SELECT ON tj.crm_deal_participants TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.crm_buying_group_members'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.crm_buying_group_members'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: crm_buying_group_members'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.crm_buying_group_members FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM tj.crm_buying_groups g JOIN tj.contacts c ON c.id=crm_buying_group_members.contact_id AND c.organization_id=g.organization_id WHERE g.id=crm_buying_group_members.buying_group_id));
GRANT SELECT ON tj.crm_buying_group_members TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.speciq_package_events'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.speciq_package_events'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: speciq_package_events'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.speciq_package_events FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM tj.speciq_packages p WHERE p.id=speciq_package_events.package_id AND p.deleted_at IS NULL AND tj_private.can_read_runtime_org(p.organization_id) AND tj.aiq_scope_allows(p.organization_id,p.created_by)));
GRANT SELECT ON tj.speciq_package_events TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.speciq_package_versions'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.speciq_package_versions'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: speciq_package_versions'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.speciq_package_versions FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM tj.speciq_packages p WHERE p.id=speciq_package_versions.package_id AND p.deleted_at IS NULL AND tj_private.can_read_runtime_org(p.organization_id) AND tj.aiq_scope_allows(p.organization_id,p.created_by)));
GRANT SELECT ON tj.speciq_package_versions TO authenticated;
DO $guard$ BEGIN IF NOT (SELECT relrowsecurity FROM pg_class WHERE oid='tj.profiles'::regclass) OR EXISTS(SELECT 1 FROM pg_policy WHERE polrelid='tj.profiles'::regclass) THEN RAISE EXCEPTION 'Review existing RLS: profiles'; END IF; END $guard$;
CREATE POLICY consolidation_app_read ON tj.profiles FOR SELECT TO authenticated USING(tj_private.can_read_source_profile(user_id));
GRANT SELECT ON tj.profiles TO authenticated;
CREATE POLICY consolidation_progress_insert ON tj.academy_progress FOR INSERT TO authenticated WITH CHECK(tj_private.is_source_self(user_id) AND (completed_at IS NULL OR completed_at<=now()+interval '5 minutes') AND EXISTS(SELECT 1 FROM tj.academy_chapters c WHERE c.id=chapter_id));
CREATE POLICY consolidation_progress_update ON tj.academy_progress FOR UPDATE TO authenticated USING(tj_private.is_source_self(user_id)) WITH CHECK(tj_private.is_source_self(user_id) AND (completed_at IS NULL OR completed_at<=now()+interval '5 minutes') AND EXISTS(SELECT 1 FROM tj.academy_chapters c WHERE c.id=chapter_id));
GRANT INSERT(user_id,chapter_id,completed_at),UPDATE(user_id,chapter_id,completed_at) ON tj.academy_progress TO authenticated;
CREATE POLICY consolidation_notification_read_receipt ON tj.academy_notifications FOR UPDATE TO authenticated USING(tj_private.is_source_self(user_id) AND (organization_id IS NULL OR tj_private.can_read_runtime_org(organization_id))) WITH CHECK(tj_private.is_source_self(user_id) AND (organization_id IS NULL OR tj_private.can_read_runtime_org(organization_id)));
GRANT UPDATE(read) ON tj.academy_notifications TO authenticated;
NOTIFY pgrst,'reload schema';
