create or replace function public.platform_intelligence_store_rollup(p_organization_id uuid,p_since timestamptz default now()-interval '30 days')
returns table(store_id uuid,store_name text,traffic_groups numeric,interactions bigint,no_sales bigint,sales bigint,revenue numeric,refunds bigint,refund_amount numeric,conversion_pct numeric,avg_ticket numeric,field_score numeric)
language sql security definer set search_path=public stable as $$
 with e as (select coalesce(canonical_event_type,event_type) et,entity_id,store_id,payload from public.intelligence_events where organization_id=p_organization_id and occurred_at>=coalesce(p_since,now()-interval '30 days')), a as (
  select store_id,coalesce(sum((payload->>'customer_groups')::numeric) filter(where et='traffic.observed'),0) traffic_groups,count(distinct entity_id) filter(where et in ('interaction.started','interaction.completed','interaction.no_sale','interaction.updated')) interactions,count(distinct entity_id) filter(where et='interaction.no_sale') no_sales,count(distinct entity_id) filter(where et='transaction.completed') sales,coalesce(sum((payload->>'amount')::numeric) filter(where et='transaction.completed'),0) revenue,count(distinct entity_id) filter(where et='transaction.refunded') refunds,coalesce(sum(abs((payload->>'amount')::numeric)) filter(where et='transaction.refunded'),0) refund_amount,round(avg((payload->>'overall_score')::numeric) filter(where et='field.score_recorded'),2) field_score from e where store_id is not null group by store_id)
 select a.store_id,l.name,a.traffic_groups,a.interactions,a.no_sales,a.sales,a.revenue,a.refunds,a.refund_amount,case when a.traffic_groups>0 then round((a.sales::numeric/a.traffic_groups)*100,2) end,case when a.sales>0 then round(a.revenue/a.sales,2) end,a.field_score from a left join public.org_locations l on l.id=a.store_id where exists(select 1 from public.organization_members m where m.organization_id=p_organization_id and m.user_id=auth.uid() and m.status='active') order by a.revenue desc nulls last;
$$;
revoke all on function public.platform_intelligence_store_rollup(uuid,timestamptz) from public,anon; grant execute on function public.platform_intelligence_store_rollup(uuid,timestamptz) to authenticated;

create or replace function public.platform_intelligence_employee_rollup(p_organization_id uuid,p_since timestamptz default now()-interval '30 days')
returns table(employee_id uuid,display_name text,interactions bigint,no_sales bigint,sales bigint,revenue numeric,conversion_pct numeric,avg_ticket numeric,learning_events bigint,coaching_reviews bigint)
language sql security definer set search_path=public stable as $$
 with e as (select coalesce(canonical_event_type,event_type) et,entity_id,actor_id,payload from public.intelligence_events where organization_id=p_organization_id and occurred_at>=coalesce(p_since,now()-interval '30 days') and actor_id is not null), a as (select actor_id,count(distinct entity_id) filter(where et in ('interaction.started','interaction.completed','interaction.no_sale','interaction.updated')) interactions,count(distinct entity_id) filter(where et='interaction.no_sale') no_sales,count(distinct entity_id) filter(where et='transaction.completed') sales,coalesce(sum((payload->>'amount')::numeric) filter(where et='transaction.completed'),0) revenue,count(*) filter(where et like 'learning.%' or et='field.training.completed') learning_events,count(*) filter(where et='coaching.review_completed') coaching_reviews from e group by actor_id), n as (select canonical_id,max(display_name) display_name from public.platform_identity_links where organization_id=p_organization_id and entity_type='employee' group by canonical_id)
 select a.actor_id,coalesce(n.display_name,a.actor_id::text),a.interactions,a.no_sales,a.sales,a.revenue,case when a.interactions>0 then round((a.sales::numeric/a.interactions)*100,2) end,case when a.sales>0 then round(a.revenue/a.sales,2) end,a.learning_events,a.coaching_reviews from a left join n on n.canonical_id=a.actor_id where exists(select 1 from public.organization_members m where m.organization_id=p_organization_id and m.user_id=auth.uid() and m.status='active') order by a.revenue desc nulls last;
$$;
revoke all on function public.platform_intelligence_employee_rollup(uuid,timestamptz) from public,anon; grant execute on function public.platform_intelligence_employee_rollup(uuid,timestamptz) to authenticated;