-- =============================================================================
-- HISTORICAL MARKER — brands_margin_periods_v1
-- Version: 20260721234042
-- Applied to production: yes (via MCP, original SQL not preserved in version control)
-- Original SQL: UNAVAILABLE — applied interactively, not recoverable
-- Domain: Brands, manufacturers, vendor assets
-- Objects created: brand_catalog, brand_training_cards, mfr_vendors, mfr_members, mfr_user_roles, mfr_invites, mfr_assets, manages_vendor() RPC, v_vendors view, vendor-assets storage bucket
-- Current schema reference: Query production with information_schema or pg_catalog
-- Execute in new environment: NO — this file contains no DDL
-- Execute against production: NO — already applied
-- 
-- This file exists solely to align the repository migration history with
-- supabase_migrations.schema_migrations in production. It does NOT recreate
-- the objects listed above. A separate baseline migration or manual schema
-- export is required to reproduce these objects in a new environment.
-- =============================================================================
