-- Preserve historical event names while adding a canonical v1 event contract.
alter table public.intelligence_events add column if not exists canonical_event_type text;
create index if not exists idx_intelligence_events_canonical_type_time on public.intelligence_events(canonical_event_type,occurred_at desc) where canonical_event_type is not null;

insert into public.platform_canonical_entity_types(key,name,description,intelligence_entity_type,active,metadata) values
('brand','Brand','Product/manufacturer brand','brand',true,'{}'),('deal','Deal','CRM deal/opportunity','deal',true,'{}'),('recommendation','Recommendation','AI recommendation','recommendation',true,'{}'),('coaching','Coaching','Coaching/review activity','coaching',true,'{}'),('field_finding','Field Finding','Field observation/finding','field_finding',true,'{}'),('field_action','Field Action','Field remediation/action','field_action',true,'{}') on conflict(key) do nothing;
insert into public.platform_canonical_event_types(key,name,description,subject_entity_type,outcome_relevant,coaching_relevant,active,metadata) values
('product.deleted','Product Deleted','Product removed/deactivated','product',false,false,true,'{}'),('brand.created','Brand Created','Brand created or registered','brand',false,false,true,'{}'),('brand.updated','Brand Updated','Brand data updated','brand',false,false,true,'{}'),('deal.updated','Deal Updated','CRM deal updated','deal',false,true,true,'{}'),('deal.stage_changed','Deal Stage Changed','CRM deal stage changed','deal',true,true,true,'{}'),('deal.won','Deal Won','CRM deal closed won','deal',true,true,true,'{}'),('deal.postmortem_recorded','Deal Postmortem Recorded','Deal postmortem captured','deal',true,true,true,'{}'),('recommendation.generated','Recommendation Generated','AI recommendation created','recommendation',false,true,true,'{}'),('recommendation.outcome_recorded','Recommendation Outcome Recorded','Outcome of AI recommendation recorded','recommendation',true,true,true,'{}'),('coaching.review_completed','Coaching Review Completed','Coaching review completed','coaching',true,true,true,'{}'),('field.visit_updated','Field Visit Updated','Field visit updated','field_visit',false,false,true,'{}'),('field.finding_updated','Field Finding Updated','Field finding updated','field_finding',false,false,true,'{}'),('field.competitive_intel_recorded','Competitive Intel Recorded','Field competitive intelligence recorded','field_finding',true,false,true,'{}'),('field.training_completed','Field Training Completed','Field training completed','learning',true,true,true,'{}'),('field.action_updated','Field Action Updated','Field action updated','field_action',false,false,true,'{}'),('field.action_resolved','Field Action Resolved','Field action resolved','field_action',true,false,true,'{}'),('interaction.updated','Interaction Updated','Customer interaction updated','interaction',false,true,true,'{}'),('interaction.waiting_updated','Waiting Customer Updated','Waiting customer state updated','interaction',false,true,true,'{}') on conflict(key) do nothing;

create table if not exists public.platform_event_type_aliases(source_event_type text primary key,canonical_event_type text not null,source_system text,active boolean not null default true,created_at timestamptz not null default now(),metadata jsonb not null default '{}'::jsonb);
alter table public.platform_event_type_aliases enable row level security; revoke all on public.platform_event_type_aliases from anon,authenticated; grant select,insert,update,delete on public.platform_event_type_aliases to service_role;
insert into public.platform_event_type_aliases(source_event_type,canonical_event_type,metadata) values
('ProductUpdated','product.updated','{"legacy":true}'),('ProductCreated','product.created','{"legacy":true}'),('ProductDeleted','product.deleted','{"legacy":true}'),('ProductRegistered','product.created','{"legacy":true}'),('BrandUpdated','brand.updated','{"legacy":true}'),('BrandRegistered','brand.created','{"legacy":true}'),('BrandCreated','brand.created','{"legacy":true}'),('RecommendationGenerated','recommendation.generated','{"legacy":true}'),('RecommendationOutcomeRecorded','recommendation.outcome_recorded','{"legacy":true}'),('DealUpdated','deal.updated','{"legacy":true}'),('dealupdated','deal.updated','{"legacy":true}'),('dealwon','deal.won','{"legacy":true}'),('DealStageChanged','deal.stage_changed','{"legacy":true}'),('DealPostmortemRecorded','deal.postmortem_recorded','{"legacy":true}'),('CustomerUpdated','customer.updated','{"legacy":true}'),('CustomerRegistered','customer.created','{"legacy":true}'),('CoachingReviewCompleted','coaching.review_completed','{"legacy":true}'),('FieldVisitUpdated','field.visit_updated','{"legacy":true}'),('FieldFindingUpdated','field.finding_updated','{"legacy":true}'),('CompetitiveIntelRecorded','field.competitive_intel_recorded','{"legacy":true}'),('FieldTrainingCompleted','field.training_completed','{"legacy":true}'),('FieldActionUpdated','field.action_updated','{"legacy":true}'),('FieldActionResolved','field.action_resolved','{"legacy":true}'),('CustomerInteractionUpdated','interaction.updated','{"legacy":true}'),('WaitingCustomerUpdated','interaction.waiting_updated','{"legacy":true}')
on conflict(source_event_type) do update set canonical_event_type=excluded.canonical_event_type,active=true;
update public.intelligence_events e set canonical_event_type=a.canonical_event_type,subject_entity_type=t.subject_entity_type,metadata=e.metadata||jsonb_build_object('legacy_event_type',e.event_type) from public.platform_event_type_aliases a join public.platform_canonical_event_types t on t.key=a.canonical_event_type where e.event_type=a.source_event_type and e.canonical_event_type is null;
update public.intelligence_events e set canonical_event_type=e.event_type,subject_entity_type=coalesce(e.subject_entity_type,t.subject_entity_type) from public.platform_canonical_event_types t where e.event_type=t.key and e.canonical_event_type is null;
update public.intelligence_events set processing_status='legacy_unmapped' where canonical_event_type is null and processing_status='ready';

-- The canonical emitter/feed/summary definitions are superseded by later Phase 3 migrations.