type Json = Record<string, any>;
type Persona = "TJ"|"Natalie"|"Leah"|"Caden"|"Asher"|"Katrina";
type ModelTier = "fast"|"standard"|"strong";
const TEAM: Persona[] = ["TJ","Natalie","Leah","Caden","Asher","Katrina"];
interface ComplexityResult { tier: ModelTier; reason: string; deterministic: boolean; deterministicType?: string }
export function classifyComplexity(message: string, historyLength: number): ComplexityResult {
  const lower = message.toLowerCase(), wordCount = message.split(/\s+/).length;
  if (/\brecall\b/.test(lower) && wordCount < 20) return { tier: "fast", reason: "recall_lookup", deterministic: true, deterministicType: "recall" };
  if (/\bwarranty\b/.test(lower) && !/explain|why|compare|better/i.test(lower) && wordCount < 20) return { tier: "fast", reason: "warranty_lookup", deterministic: true, deterministicType: "warranty" };
  if (/\b(phone|contact|call|number|email|support line)\b/.test(lower) && wordCount < 20) return { tier: "fast", reason: "contact_lookup", deterministic: true, deterministicType: "contact" };
  if (/\b(spec|dimension|width|height|depth|capacity|voltage|amperage)\b/.test(lower) && !/compare|vs|versus|better|recommend/i.test(lower) && wordCount < 25) return { tier: "fast", reason: "spec_lookup", deterministic: true, deterministicType: "spec" };
  if (/\b(install|rough.?in|clearance|cutout|electrical req|plumbing req|venting req)\b/.test(lower) && !/compare|recommend|should/i.test(lower) && wordCount < 25) return { tier: "fast", reason: "installation_lookup", deterministic: true, deterministicType: "installation" };
  if (/\b(map policy|map pricing|minimum advertised|price protection)\b/.test(lower) && wordCount < 20) return { tier: "fast", reason: "map_lookup", deterministic: true, deterministicType: "map_policy" };
  if (/\b(selling angle|selling point|why sell|how to sell|pitch for|position)\b/.test(lower) && wordCount < 25) return { tier: "fast", reason: "selling_angles_lookup", deterministic: true, deterministicType: "selling_angles" };
  if (/\b(cross.?reference|alternative|competitor|switch from|instead of)\b/.test(lower) && !/compare|which is better|recommend/i.test(lower) && wordCount < 25) return { tier: "fast", reason: "cross_ref_lookup", deterministic: true, deterministicType: "cross_reference" };
  if (/\b(lifecycle|end of life|discontinued|replacement model|replaced by)\b/.test(lower) && wordCount < 20) return { tier: "fast", reason: "lifecycle_lookup", deterministic: true, deterministicType: "lifecycle" };
  const strongSignals = ["analyze","analysis","coaching session","score my","evaluate my","role-play","roleplay","role play","transcript","performance review","post-mortem","lost the sale","won the sale","management coaching","training module","training course","compare my performance","what did i do wrong","how could i improve","strategy for","deep dive","walk me through","seven steps","11 steps","steps of selling","difficult customer","angry customer"];
  if (strongSignals.some(s => lower.includes(s))) return { tier: "strong", reason: "coaching_or_analysis", deterministic: false };
  if (wordCount > 80) return { tier: "standard", reason: "long_message", deterministic: false };
  if (historyLength > 8) return { tier: "standard", reason: "deep_conversation", deterministic: false };
  const standardSignals = ["explain why","help me understand","what should i say","objection","how do i handle","how would you","recommend","suggestion","which is better","compare","versus","vs","pros and cons","write me","draft a","create a","what's the difference","should i"];
  if (standardSignals.some(s => lower.includes(s))) return { tier: "standard", reason: "reasoning_needed", deterministic: false };
  return { tier: "fast", reason: "simple_request", deterministic: false };
}
export function route(message: string, max: number) { const q = message.toLowerCase(); const s: Record<Persona, number> = { TJ: 0, Natalie: 0, Leah: 0, Caden: 0, Asher: 0, Katrina: 0 }; const add = (p: Persona, words: string[], w: number) => words.forEach(x => { if (q.includes(x)) s[p] += w; }); const product = ["model","spec","feature","compare","price","product","brand","refrigerator","fridge","range","dishwasher","washer","dryer","appliance","oven","cooktop","freezer","microwave","hood"]; add("Natalie", product, 3); add("Asher", ["fit","install","dimension","width","height","depth","opening","clearance","electrical","gas","vent","water line","door swing"], 4); add("Leah", ["design","style","colour","color","finish","kitchen","aesthetic","layout","lifestyle","family"], 3); add("TJ", ["sell","sales","close","objection","customer","pitch","follow-up","quote","commission","deal","pipeline","crm"], 4); add("Caden", ["teach","training","learn","explain","lesson","quiz","module","progress","certif","academy"], 4); add("Katrina", ["service","repair","problem","issue","complaint","warranty","support","troubleshoot","broken","recall"], 4); if (Object.values(s).every(v => v === 0)) s.Natalie = 1; const ranked = (Object.entries(s) as [Persona, number][]).sort((a, b) => b[1] - a[1]); const people = ranked.filter(x => x[1] > 0).slice(0, max).map(x => x[0]); return { primary: people[0] ?? "Natalie", personas: people.length ? people : ["Natalie"], reason: ranked.filter(x => x[1] > 0).map(x => `${x[0]}:${x[1]}`).join(", "), productIntent: product.some(x => q.includes(x)) || s.Natalie > 0 || s.Asher > 0 }; }
export function memoryContext(m: Json, s: Json | null) { return ["CUSTOMER MEMORY (reported facts):", JSON.stringify({ conversation_id: m.conversation_id, stage: m.stage, profile: m.profile, contradictions: m.contradictions, completeness_score: m.completeness_score, next_discovery_question: m.next_discovery_question, missing_profile_fields: m.missing_profile_fields }, null, 2), s ? "SCORED RECOMMENDATIONS (stored evidence):\n" + JSON.stringify({ recommendations: s.recommendations, labelled_recommendations: s.labelled_recommendations, next_discovery_question: s.next_discovery_question }, null, 2).slice(0, 18000) : "No scored recommendation was run."].join("\n\n"); }
export function memorySummary(m: Json) { return { stage: m.stage, profile: m.profile, completeness_score: m.completeness_score, next_discovery_question: m.next_discovery_question, missing_profile_fields: m.missing_profile_fields, recommendation_ready: m.recommendation_ready, contradictions: m.contradictions }; }
