import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const gid=(v:any)=>String(v??'').split('/').pop()||String(v??'');
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors}); if(req.method!=='POST')return json({error:'POST required'},405);
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,auth=req.headers.get('Authorization')??'';
 const uc=createClient(url,anon,{global:{headers:{Authorization:auth}}}),db=createClient(url,service); const {data:{user}}=await uc.auth.getUser(); if(!user)return json({error:'unauthorized'},401);
 let b:any={}; try{b=await req.json()}catch{} const cid=String(b.connection_id??''); if(!cid)return json({error:'connection_id_required'},400);
 const {data:c}=await db.from('platform_connector_connections').select('id,organization_id,connector_id,credential_ref').eq('id',cid).maybeSingle(); if(!c)return json({error:'connection_not_found'},404);
 const {data:m}=await db.from('organization_members').select('role,status').eq('organization_id',c.organization_id).eq('user_id',user.id).eq('status','active').maybeSingle(); if(!m||!['owner','admin','super_admin'].includes(String(m.role)))return json({error:'admin_required'},403);
 const {data:co}=await db.from('platform_connectors').select('key').eq('id',c.connector_id).single(); if(co?.key!=='shopify')return json({error:'not_shopify_connection'},400);
 const {data:ss}=await db.from('shopify_stores').select('*').eq('platform_connection_id',cid).maybeSingle(); if(!ss)return json({error:'shopify_store_link_missing'},409);
 let token=''; if(c.credential_ref){const {data:s}=await db.rpc('platform_get_connector_secret',{p_id:c.credential_ref}); if(s){try{const x=JSON.parse(s);token=String(x.access_token??x.token??'')}catch{token=String(s)}}} if(!token&&ss.access_token&&!['VAULT','VAULTED','REDACTED','REVOKED'].includes(ss.access_token))token=ss.access_token; if(!token)return json({error:'shopify_token_missing'},409);
 const shop=ss.shop_domain,api='2026-07',endpoint=`https://${shop}/admin/api/${api}/graphql.json`; const scopes=String(ss.scopes??'').split(',').map((x:string)=>x.trim()); const hasAll=scopes.includes('read_all_orders'),hasUsers=scopes.includes('read_users');
 async function gql(q:string,vars:any={}){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','X-Shopify-Access-Token':token},body:JSON.stringify({query:q,variables:vars})});const x=await r.json();if(!r.ok||x.errors)throw new Error(x.errors?.map((e:any)=>e.message).join('; ')||`Shopify ${r.status}`);return x.data}
 async function ingest(type:string,id:string,name:string,payload:any,occurred?:string){const r=await fetch(`${url}/functions/v1/connector-ingest`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':auth,'apikey':anon},body:JSON.stringify({connection_id:cid,external_entity_type:type,external_id:id,canonical_name:name,payload,occurred_at:occurred??new Date().toISOString()})}); if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||`ingest ${type} failed`)}
 async function page(field:string,q:string,handle:(n:any)=>Promise<void>,vars:any={}){let after:null|string=null,count=0;for(let p=0;p<100;p++){const d=await gql(q,{...vars,after});const conn=d[field];for(const n of conn.nodes){await handle(n);count++}if(!conn.pageInfo.hasNextPage)break;after=conn.pageInfo.endCursor}return count}
 const {data:job}=await db.from('platform_sync_jobs').insert({connection_id:cid,job_type:'initial',direction:'inbound',status:'running',requested_by:user.id,started_at:new Date().toISOString()}).select('id').single(); const stats:any={api_version:api,locations:0,customers:0,products:0,inventory:0,orders:0,staff:0,performance_orders:0,errors:[]};
 try{
  stats.locations=await page('locations',`query($after:String){locations(first:100,after:$after,includeInactive:true){nodes{id name isActive address{address1 address2 city provinceCode zip countryCode}}pageInfo{hasNextPage endCursor}}}`,async n=>ingest('location',gid(n.id),n.name,n));
  stats.customers=await page('customers',`query($after:String){customers(first:100,after:$after){nodes{id displayName firstName lastName defaultEmailAddress{emailAddress} defaultPhoneNumber{phoneNumber} createdAt updatedAt}pageInfo{hasNextPage endCursor}}}`,async n=>ingest('customer',gid(n.id),n.displayName||gid(n.id),{...n,email:n.defaultEmailAddress?.emailAddress??null,phone:n.defaultPhoneNumber?.phoneNumber??null},n.updatedAt));
  stats.products=await page('products',`query($after:String){products(first:100,after:$after){nodes{id title handle vendor productType status createdAt updatedAt variants(first:100){nodes{id sku barcode price inventoryItem{id sku unitCost{amount currencyCode}}}}}pageInfo{hasNextPage endCursor}}}`,async n=>ingest('product',gid(n.id),n.title,n,n.updatedAt));
  stats.inventory=await page('inventoryItems',`query($after:String){inventoryItems(first:100,after:$after){nodes{id sku tracked unitCost{amount currencyCode} updatedAt inventoryLevels(first:100){nodes{id location{id name} quantities(names:["available","on_hand","committed"]){name quantity}}}}pageInfo{hasNextPage endCursor}}}`,async n=>{for(const l of n.inventoryLevels.nodes){const id=`${gid(n.id)}:${gid(l.location.id)}`;await ingest('inventory',id,n.sku||id,{id,inventoryItemId:gid(n.id),sku:n.sku,tracked:n.tracked,unitCost:n.unitCost,location:{id:gid(l.location.id),name:l.location.name},quantities:l.quantities},n.updatedAt)}});
  const since=new Date(Date.now()-(hasAll?3650:60)*86400000).toISOString();
  stats.orders=await page('orders',`query($after:String,$query:String!){orders(first:100,after:$after,sortKey:PROCESSED_AT,query:$query){nodes{id name createdAt updatedAt processedAt currencyCode displayFinancialStatus displayFulfillmentStatus sourceName staffMember{id name email} totalPriceSet{shopMoney{amount currencyCode}} subtotalPriceSet{shopMoney{amount}} totalDiscountsSet{shopMoney{amount}} customer{id displayName} retailLocation{id name} lineItems(first:100){nodes{id name title sku quantity vendor product{id} variant{id} originalUnitPriceSet{shopMoney{amount}} discountedTotalSet{shopMoney{amount}} staffMember{id name email}}} refunds{id createdAt totalRefundedSet{shopMoney{amount}}}}pageInfo{hasNextPage endCursor}}}`,async n=>{
    const lineItems=(n.lineItems?.nodes??[]).map((l:any)=>{const s=l.staffMember??n.staffMember;return {id:gid(l.id),title:l.title||l.name,name:l.name,sku:l.sku,quantity:l.quantity,vendor:l.vendor,product_id:l.product?gid(l.product.id):null,variant_id:l.variant?gid(l.variant.id):null,price:l.originalUnitPriceSet?.shopMoney?.amount,total_discount:Math.max(0,Number(l.originalUnitPriceSet?.shopMoney?.amount||0)*Number(l.quantity||0)-Number(l.discountedTotalSet?.shopMoney?.amount||0)),attributed_staffs:s?[{id:gid(s.id),name:s.name,email:s.email}]:[]}});
    const order:any={id:gid(n.id),name:n.name,created_at:n.createdAt,updated_at:n.updatedAt,processed_at:n.processedAt,currency:n.currencyCode,financial_status:n.displayFinancialStatus,fulfillment_status:n.displayFulfillmentStatus,source_name:n.sourceName,total_price:n.totalPriceSet?.shopMoney?.amount,subtotal_price:n.subtotalPriceSet?.shopMoney?.amount,total_discounts:n.totalDiscountsSet?.shopMoney?.amount,customer:n.customer?{id:gid(n.customer.id),name:n.customer.displayName}:null,location_id:n.retailLocation?gid(n.retailLocation.id):null,staff_member:n.staffMember?{id:gid(n.staffMember.id),name:n.staffMember.name,email:n.staffMember.email}:null,line_items:lineItems,refunds:n.refunds??[]};
    await ingest('order',gid(n.id),n.name,order,n.updatedAt);
    const raw=JSON.stringify(order),secret=Deno.env.get('SHOPIFY_API_SECRET')??''; if(secret){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(raw));const h=btoa(String.fromCharCode(...new Uint8Array(sig)));const br=await fetch(`${url}/functions/v1/shopify-performance-bridge`,{method:'POST',headers:{'Content-Type':'application/json','X-Shopify-Hmac-Sha256':h,'X-Shopify-Shop-Domain':shop},body:raw});if(br.ok)stats.performance_orders++}
    for(const r of n.refunds??[]){await ingest('refund',gid(r.id),`Refund ${gid(r.id)}`,{...r,order_id:gid(n.id)},r.createdAt)}
  },{query:`processed_at:>=${since}`});
  if(hasUsers){try{stats.staff=await page('staffMembers',`query($after:String){staffMembers(first:100,after:$after){nodes{id name firstName lastName email active isShopOwner accountType}pageInfo{hasNextPage endCursor}}}`,async n=>ingest('salesperson',gid(n.id),n.name,n))}catch(e){stats.errors.push({resource:'staffMembers',error:String((e as any)?.message??e)})}}
  const done=new Date().toISOString(); await db.from('shopify_stores').update({initial_sync_completed_at:done,initial_sync_stats:stats,last_sync_at:done,updated_at:done}).eq('id',ss.id); await db.from('platform_sync_jobs').update({status:stats.errors.length?'partial':'success',completed_at:done,stats}).eq('id',job.id); await db.from('platform_connector_connections').update({status:'active',auth_status:'valid',last_sync_at:done,last_success_at:done,last_error:stats.errors.length?`${stats.errors.length} optional resources failed`:null,updated_at:done}).eq('id',cid); return json({ok:true,...stats,order_window_days:hasAll?'all_authorized_history':60,staff_sync:hasUsers?'enabled':'not_authorized'});
 }catch(e){const msg=String((e as any)?.message??e);await db.from('platform_sync_jobs').update({status:'failed',completed_at:new Date().toISOString(),stats,error_details:{message:msg}}).eq('id',job.id);await db.from('platform_connector_connections').update({last_error:msg,last_sync_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',cid);return json({error:'shopify_initial_sync_failed',detail:msg,stats},502)}
});
